import type { AdminPermission } from "@/lib/admin-auth-types";
import { assertAccountAuthSameOrigin } from "@/lib/server/account-auth";
import { apiErrorResponse, beginApiRequest, jsonResponse, mutationHash, readJsonBody, requireIdempotencyKey } from "@/lib/server/api-guard";
import { requireAdminPermission } from "@/lib/server/admin-auth";
import { getAdminOperationsStore, type AdminListQuery, type AdminSourceSystem } from "@/lib/server/admin-store";

export function adminQuery(request:Request):AdminListQuery{const p=new URL(request.url).searchParams;const raw=Number(p.get("limit")??50);return{limit:Number.isInteger(raw)?Math.min(100,Math.max(1,raw)):50,status:p.get("status"),q:p.get("q"),sourceSystem:(p.get("sourceSystem") as AdminSourceSystem|null)};}
export async function adminRead(request:Request,permissions:readonly AdminPermission[],read:(store:Awaited<ReturnType<typeof getAdminOperationsStore>>)=>Promise<unknown>){const context=beginApiRequest(request);try{await requireAdminPermission(request,permissions);return jsonResponse(await read(await getAdminOperationsStore()),200,undefined,context);}catch(error){return apiErrorResponse(error,undefined,context);}}
export async function adminWrite(request:Request,permissions:readonly AdminPermission[],write:(store:Awaited<ReturnType<typeof getAdminOperationsStore>>,actor:{principalId:string;organizationId:string;idempotencyKey:string;payloadHash:string},input:Record<string,unknown>)=>Promise<{replayed:boolean}&Record<string,unknown>>){const context=beginApiRequest(request);try{assertAccountAuthSameOrigin(request);const auth=await requireAdminPermission(request,permissions);const input=await readJsonBody(request) as Record<string,unknown>;const result=await write(await getAdminOperationsStore(),{principalId:auth.principal.id,organizationId:auth.organization.id,idempotencyKey:requireIdempotencyKey(request),payloadHash:await mutationHash(input)},input);return jsonResponse(result,result.replayed?200:201,{"idempotency-replayed":String(result.replayed)},context);}catch(error){return apiErrorResponse(error,undefined,context);}}
