import type { AdminEntityOwnership, AdminListQuery, AdminProjectionItem, AdminProjectionName, AdminSourceSystem } from "./admin-store.ts";

type Row=Record<string,unknown>;
export interface AdminProjectionAdapter { all<T>(sql:string,values?:readonly unknown[]):Promise<T[]>; }
const missing=(error:unknown)=>/no such table|does not exist|D1_ERROR.*table|SQLITE_ERROR.*table/iu.test(error instanceof Error?error.message:String(error));
async function safeAll(db:AdminProjectionAdapter,sql:string,values:readonly unknown[]=[]){try{return await db.all<Row>(sql,values);}catch(error){if(missing(error))return[];throw error;}}
const anon={organizationId:null,accountId:null,legacyActorId:null,classification:"LEGACY_ANON" as const};
function own(row:Row):AdminEntityOwnership|typeof anon{return row.organization_id==null?anon:{sourceSystem:row.ownership_source_system as AdminSourceSystem,entityType:String(row.ownership_entity_type),entityId:String(row.id),organizationId:String(row.organization_id),accountId:String(row.account_id),legacyActorId:row.legacy_actor_id==null?null:String(row.legacy_actor_id),boundByPrincipalId:String(row.bound_by_principal_id),createdAt:String(row.ownership_created_at),updatedAt:String(row.ownership_updated_at),version:Number(row.ownership_version),classification:"BOUND"};}
const ownershipJoin=(source:string,type:string,alias="x",entityId=`${alias}.id`)=>`LEFT JOIN admin_entity_ownership own ON own.source_system='${source}' AND own.entity_type='${type}' AND own.entity_id=${entityId}`;
const ownershipCols="own.source_system ownership_source_system,own.entity_type ownership_entity_type,own.organization_id,own.account_id,own.legacy_actor_id,own.bound_by_principal_id,own.created_at ownership_created_at,own.updated_at ownership_updated_at,own.version ownership_version";
const item=(row:Row,sourceSystem:AdminSourceSystem,entityType:string,options:{title:string;subtitle?:string|null;actors?:unknown[];amount?:unknown;currency?:unknown;facts?:Record<string,unknown>}):AdminProjectionItem=>({sourceSystem,entityType,id:String(row.id),status:String(row.status),title:options.title,subtitle:options.subtitle??null,actorIds:(options.actors??[]).filter(v=>v!=null).map(String),amountCents:options.amount==null?null:Number(options.amount),currency:options.currency==null?null:String(options.currency),createdAt:row.created_at==null?null:String(row.created_at),updatedAt:row.updated_at==null?null:String(row.updated_at),facts:options.facts??{},ownership:own(row)});

async function raw(db:AdminProjectionAdapter,name:AdminProjectionName):Promise<AdminProjectionItem[]>{
  if(name==="supply-offers")return(await safeAll(db,`SELECT x.*,${ownershipCols} FROM supply_offers x ${ownershipJoin("SUPPLY_PILOT","SUPPLY_OFFER")} ORDER BY x.created_at DESC LIMIT 250`)).map(r=>item(r,"SUPPLY_PILOT","SUPPLY_OFFER",{title:String(r.product_name),subtitle:`${r.quantity} ${r.quantity_unit} · ${r.region}`,actors:[r.supplier_actor_id],facts:{resourceType:r.resource_type,supplierType:r.supplier_type,specification:r.specification,pricingUnit:r.pricing_unit,deliveryForm:r.delivery_form,version:Number(r.version)}}));
  if(name==="demands")return(await safeAll(db,`SELECT x.*,${ownershipCols} FROM marketplace_requests_v2 x ${ownershipJoin("MARKETPLACE","DEMAND")} ORDER BY x.created_at DESC LIMIT 250`)).map(r=>item(r,"MARKETPLACE","DEMAND",{title:String(r.title),subtitle:`${r.quantity} ${r.pricing_unit} · ${r.region}`,actors:[r.owner_actor_id],amount:r.cash_amount==null?null:Math.round(Number(r.cash_amount)*100),currency:r.cash_amount==null?null:"CNY",facts:{requestType:r.request_type,kind:r.kind,category:r.category,cashDirection:r.cash_direction,version:Number(r.version)}}));
  if(name==="matches")return(await safeAll(db,`SELECT x.*,${ownershipCols} FROM admin_work_items x ${ownershipJoin("ADMIN","MATCH","x")} WHERE x.work_type='DEMAND_MATCH' ORDER BY x.created_at DESC LIMIT 250`)).map(r=>item(r,"ADMIN","MATCH",{title:String(r.title),subtitle:String(r.summary),actors:[r.created_by,r.assignee_principal_id],facts:{priority:r.priority,metadata:JSON.parse(String(r.metadata_json)),version:Number(r.version)}}));
  if(name==="pools")return(await safeAll(db,`SELECT x.*,(SELECT COUNT(*) FROM supply_asset_members m WHERE m.pool_id=x.id) member_count,(SELECT COUNT(*) FROM supply_asset_members m WHERE m.pool_id=x.id AND m.status='VERIFIED') verified_count,${ownershipCols} FROM supply_asset_pools x ${ownershipJoin("SUPPLY_PILOT","ASSET_POOL")} ORDER BY x.created_at DESC LIMIT 250`)).map(r=>item(r,"SUPPLY_PILOT","ASSET_POOL",{title:String(r.name),subtitle:`${r.asset_kind} · ${r.region}`,actors:[r.supplier_actor_id],facts:{deliveryForm:r.delivery_form,specDigest:r.spec_digest,memberCount:Number(r.member_count),verifiedCount:Number(r.verified_count)}}));
  if(name==="verifications"){
    const [exchange,supply]=await Promise.all([
      safeAll(db,`SELECT x.*,x.result status,${ownershipCols} FROM exchange_verification_runs x ${ownershipJoin("EXCHANGE","VERIFICATION_RUN")} ORDER BY x.created_at DESC LIMIT 150`),
      safeAll(db,`SELECT x.*,${ownershipCols} FROM supply_verification_jobs x ${ownershipJoin("SUPPLY_PILOT","VERIFICATION_JOB")} ORDER BY x.created_at DESC LIMIT 150`),
    ]);
    return [...exchange.map(r=>item(r,"EXCHANGE","VERIFICATION_RUN",{title:`Verification ${r.id}`,subtitle:String(r.evidence_summary),actors:[r.operator_actor_id],facts:{resourceAssetId:r.resource_asset_id,method:r.method,validUntil:r.valid_until}})),...supply.map(r=>item(r,"SUPPLY_PILOT","VERIFICATION_JOB",{title:`Verification ${r.id}`,subtitle:`Pool ${r.pool_id}`,actors:[r.requested_by,r.reviewed_by],facts:{poolId:r.pool_id,memberId:r.member_id,validUntil:r.valid_until,completedAt:r.completed_at}}))];
  }
  if(name==="orders"){
    const [exchange,supply]=await Promise.all([
      safeAll(db,`SELECT x.*,${ownershipCols} FROM exchange_orders x ${ownershipJoin("EXCHANGE","ORDER")} ORDER BY x.created_at DESC LIMIT 150`),
      safeAll(db,`SELECT x.*,${ownershipCols} FROM supply_trial_orders x ${ownershipJoin("SUPPLY_PILOT","ORDER")} ORDER BY x.created_at DESC LIMIT 150`),
    ]);
    const lifecycle=new Map((await safeAll(db,"SELECT order_id,phase,state_reason,version lifecycle_version,updated_at lifecycle_updated_at FROM exchange_order_lifecycle")).map(r=>[String(r.order_id),r]));
    return [...exchange.map(r=>{const life=lifecycle.get(String(r.id));return item(r,"EXCHANGE","ORDER",{title:`Order ${r.id}`,subtitle:`${r.rate_units} ${r.rate_unit_code}`,actors:[r.buyer_actor_id,r.supplier_actor_id],amount:r.total_amount_cents,currency:r.currency,facts:{startAt:r.start_at,endAt:r.end_at,listingVersionId:r.listing_version_id,version:Number(r.version),lifecyclePhase:life?.phase??null,lifecycleReason:life?.state_reason??null,lifecycleVersion:life==null?null:Number(life.lifecycle_version)}});}),...supply.map(r=>item(r,"SUPPLY_PILOT","ORDER",{title:`Trial order ${r.id}`,subtitle:`${r.gpu_count} GPU × ${r.duration_hours}h`,actors:[r.buyer_actor_id,r.supplier_actor_id],amount:r.amount_cents,currency:r.currency,facts:{promotionId:r.promotion_id,startAt:r.start_at,endAt:r.end_at,version:Number(r.version)}}))];
  }
  const [exchange,supply]=await Promise.all([
    safeAll(db,`SELECT x.*,${ownershipCols} FROM exchange_payment_intents x ${ownershipJoin("EXCHANGE","PAYMENT_INTENT")} ORDER BY x.created_at DESC LIMIT 150`),
    safeAll(db,`SELECT x.order_id id,x.*,o.amount_cents,o.currency,o.buyer_actor_id,o.supplier_actor_id,${ownershipCols} FROM supply_trial_payments x JOIN supply_trial_orders o ON o.id=x.order_id ${ownershipJoin("SUPPLY_PILOT","PAYMENT","x","x.order_id")} ORDER BY x.created_at DESC LIMIT 150`),
  ]);
  const settlements=new Map((await safeAll(db,"SELECT id,order_id,status,gross_amount_cents,net_supplier_payable_cents,funds_moved,version FROM exchange_settlements")).map(r=>[String(r.order_id),r]));
  return [...exchange.map(r=>{const settlement=settlements.get(String(r.order_id));return item(r,"EXCHANGE","PAYMENT_INTENT",{title:`Payment ${r.id}`,subtitle:`Order ${r.order_id}`,amount:r.amount_cents,currency:r.currency,facts:{orderId:r.order_id,provider:r.provider,environment:r.environment,providerPaymentId:r.provider_payment_id,version:Number(r.version),settlement:settlement==null?null:{id:settlement.id,status:settlement.status,grossAmountCents:Number(settlement.gross_amount_cents),netSupplierPayableCents:Number(settlement.net_supplier_payable_cents),fundsMoved:Boolean(settlement.funds_moved),version:Number(settlement.version)}}});}),...supply.map(r=>item(r,"SUPPLY_PILOT","PAYMENT",{title:`Payment for ${r.order_id}`,subtitle:String(r.provider),actors:[r.buyer_actor_id,r.supplier_actor_id],amount:r.amount_cents,currency:r.currency,facts:{orderId:r.order_id,providerOrderRef:r.provider_order_ref,providerTransactionRef:r.provider_transaction_ref,version:Number(r.version)}}))];
}

export async function readAdminProjection(db:AdminProjectionAdapter,name:AdminProjectionName,query:AdminListQuery={}):Promise<AdminProjectionItem[]>{const q=query.q?.trim().toLowerCase();return(await raw(db,name)).filter(v=>(!query.status||v.status===query.status)&&(!query.sourceSystem||v.sourceSystem===query.sourceSystem)&&(!q||`${v.id} ${v.title} ${v.subtitle??""} ${v.actorIds.join(" ")}`.toLowerCase().includes(q))).sort((a,b)=>String(b.updatedAt??b.createdAt??"").localeCompare(String(a.updatedAt??a.createdAt??""))).slice(0,Math.min(100,Math.max(1,Number(query.limit??50)||50)));}
