import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { DatabaseSync } from "node:sqlite";
import test from "node:test";
import { decideAndExecuteRefund, retryApprovedRefund } from "../lib/server/admin-refund-executor.ts";
import type { AdminMutationContext, AdminOperationsStore } from "../lib/server/admin-store.ts";
import { createSqliteAdminOperationsStore } from "../lib/server/admin-store-sqlite.ts";
import type { SupplyStore } from "../lib/server/supply-store.ts";

const context=(principalId:string,key:string)=>({principalId,idempotencyKey:`refund-test-${key.padEnd(16,"x")}`,payloadHash:`sha256:${key.padEnd(64,"0").slice(0,64)}`});
function fixture(){const directory=mkdtempSync(join(tmpdir(),"kai-admin-refund-"));const path=join(directory,"test.sqlite");const db=new DatabaseSync(path);db.exec("CREATE TABLE supply_trial_orders(id TEXT PRIMARY KEY,amount_cents INTEGER,currency TEXT)");db.exec("CREATE TABLE supply_trial_payments(order_id TEXT PRIMARY KEY,status TEXT,provider TEXT,provider_order_ref TEXT,provider_transaction_ref TEXT,version INTEGER,created_at TEXT,updated_at TEXT)");db.prepare("INSERT INTO supply_trial_orders VALUES(?,?,?)").run("order-1",6400,"CNY");db.prepare("INSERT INTO supply_trial_payments VALUES(?,?,?,?,?,?,?,?)").run("order-1","CAPTURED","ALIPAY","order-1","ali-trade-1",2,"2026-08-01","2026-08-01");db.close();return{path,cleanup:()=>rmSync(directory,{recursive:true,force:true})};}
function fakeSupply(events:Array<Record<string,unknown>>){return {async getTrialOrder(){const refunded=events.reduce((total,event)=>total+Number(event.amountCents??0),0);return {order:{id:"order-1",amountCents:6400},payment:{provider:"ALIPAY",status:refunded===6400?"REFUNDED":"CAPTURED",providerTransactionRef:"ali-trade-1"},paymentEvents:events,delivery:null};},async applyTrialPaymentEvent(_orderId:unknown,_context:unknown,input:Record<string,unknown>){const existing=events.find((event)=>event.providerEventRef===input.providerEventRef);if(existing)return {record:{payment:{status:"REFUNDED"},event:existing},replayed:true};const event={...input,operation:"REFUND",outcome:"APPLIED",providerTransactionRef:"ali-trade-1"};events.push(event);return {record:{payment:{status:"REFUNDED"},event},replayed:false};}} as unknown as SupplyStore;}

test("independent approval calls Alipay then applies the domain refund event",async()=>{const f=fixture();const store=await createSqliteAdminOperationsStore(f.path);try{const requested=await store.requestRefund(context("finance-requester","request"),{sourceSystem:"SUPPLY_PILOT",entityType:"PAYMENT",entityId:"order-1",amountCents:1600,expectedVersion:2,reason:"Customer approved partial refund"});const providerCalls:Array<Record<string,unknown>>=[],events:Array<Record<string,unknown>>=[];const result=await decideAndExecuteRefund(store,requested.record.id,context("finance-approver","approve"),{expectedVersion:1,decision:"APPROVED",reason:"Independent evidence has been reviewed"},{supplyStore:fakeSupply(events),refundTrade:async(orderId,refundRequestId,amountCents)=>{providerCalls.push({orderId,refundRequestId,amountCents});return{code:"10000",fund_change:"Y",trade_no:"ali-trade-1"};},queryRefund:async()=>({})});assert.equal(result.record.execution?.status,"SUCCEEDED");assert.equal(providerCalls.length,1);assert.equal(events.length,1);assert.equal(events[0].amountCents,1600);assert.equal(events[0].providerEventRef,result.record.execution?.refundRequestId);assert.notEqual(result.record.requestedBy,result.record.decidedBy);}finally{store.close();f.cleanup();}});

test("provider failure is persisted and an approved case can be retried without a second refund id",async()=>{const f=fixture();const store=await createSqliteAdminOperationsStore(f.path);try{const requested=await store.requestRefund(context("finance-requester","request2"),{sourceSystem:"SUPPLY_PILOT",entityType:"PAYMENT",entityId:"order-1",amountCents:800,expectedVersion:2,reason:"Customer approved partial refund"});const events:Array<Record<string,unknown>>=[];const failed=await decideAndExecuteRefund(store,requested.record.id,context("finance-approver","approve2"),{expectedVersion:1,decision:"APPROVED",reason:"Independent evidence has been reviewed"},{supplyStore:fakeSupply(events),refundTrade:async()=>{throw Object.assign(new Error("timeout"),{code:"ALIPAY_TIMEOUT"});},queryRefund:async()=>({})});assert.equal(failed.record.execution?.status,"FAILED");const requestId=failed.record.execution?.refundRequestId;const retried=await retryApprovedRefund(store,requested.record.id,context("finance-approver","retry2"),{reason:"Retry after provider connectivity recovered"},{supplyStore:fakeSupply(events),refundTrade:async()=>({code:"10000",fund_change:"Y",trade_no:"ali-trade-1"}),queryRefund:async()=>({})});assert.equal(retried.record.execution?.status,"SUCCEEDED");assert.equal(retried.record.execution?.attemptCount,2);assert.equal(retried.record.execution?.refundRequestId,requestId);assert.equal(events.length,1);}finally{store.close();f.cleanup();}});

test("retry converges to succeeded when the domain refund committed before execution status persistence failed",async()=>{const f=fixture();const store=await createSqliteAdminOperationsStore(f.path);try{const requested=await store.requestRefund(context("finance-requester","request3"),{sourceSystem:"SUPPLY_PILOT",entityType:"PAYMENT",entityId:"order-1",amountCents:6400,expectedVersion:2,reason:"Customer approved complete refund"});const events:Array<Record<string,unknown>>=[],providerCalls:string[]=[];let failSuccessWrite=true;const faultStore={...store,async finishRefundExecution(caseId:string,actor:AdminMutationContext,input:Parameters<AdminOperationsStore["finishRefundExecution"]>[2]){if(input.status==="SUCCEEDED"&&failSuccessWrite){failSuccessWrite=false;throw new Error("injected execution status write failure");}return store.finishRefundExecution(caseId,actor,input);}} as AdminOperationsStore;const dependencies={supplyStore:fakeSupply(events),refundTrade:async(_orderId:string,refundRequestId:string)=>{providerCalls.push(refundRequestId);return{code:"10000",fund_change:"Y",trade_no:"ali-trade-1"};},queryRefund:async()=>({})};const first=await decideAndExecuteRefund(faultStore,requested.record.id,context("finance-approver","approve3"),{expectedVersion:1,decision:"APPROVED",reason:"Independent evidence has been reviewed"},dependencies);assert.equal(first.record.execution?.status,"FAILED");assert.equal(events.length,1);const requestId=first.record.execution?.refundRequestId;const retried=await retryApprovedRefund(faultStore,requested.record.id,context("finance-approver","retry3"),{reason:"Recover execution status after committed refund"},dependencies);assert.equal(retried.record.execution?.status,"SUCCEEDED");assert.equal(retried.record.execution?.refundRequestId,requestId);assert.equal(events.length,1,"the domain refund event must not be duplicated");assert.equal(providerCalls.length,1,"the provider refund must not be repeated");}finally{store.close();f.cleanup();}});
