#!/bin/sh
set -eu

if [ "$#" -lt 3 ]; then
  printf '%s\n' "usage: run-production-schema-gate.sh <candidate-release-env> node <approved-verifier> [approved arguments]" >&2
  exit 64
fi

CANDIDATE_RELEASE_ENV=$1
shift
APP_ENV=/etc/kai-cloud/kai-cloud-app.env
COMPOSE_FILE=/etc/kai-cloud/kai-cloud-schema-gate.compose.yml
RUNNER_FILE=/usr/local/lib/kai-cloud/run-production-schema-gate.sh
RELEASE_ENV_DIR=/var/lib/kai-cloud-releases

case "$CANDIDATE_RELEASE_ENV" in
  /var/lib/kai-cloud-releases/kai-cloud-release-*.env) ;;
  *)
    printf '%s\n' "candidate release env must be an immutable 40-character release artifact" >&2
    exit 64
    ;;
esac
if ! printf '%s\n' "${CANDIDATE_RELEASE_ENV##*/}" | grep -Eq '^kai-cloud-release-[0-9a-f]{40}\.env$'; then
  printf '%s\n' "candidate release env filename is invalid" >&2
  exit 64
fi
CANDIDATE_RELEASE_SHA=${CANDIDATE_RELEASE_ENV##*/kai-cloud-release-}
CANDIDATE_RELEASE_SHA=${CANDIDATE_RELEASE_SHA%.env}

if [ ! -d "$RELEASE_ENV_DIR" ] || [ -L "$RELEASE_ENV_DIR" ] || [ "$(readlink -f "$RELEASE_ENV_DIR")" != "$RELEASE_ENV_DIR" ] || [ "$(stat -c '%u:%g' "$RELEASE_ENV_DIR")" != "0:0" ] || [ -n "$(find "$RELEASE_ENV_DIR" -maxdepth 0 -perm /022 -print -quit)" ]; then
  printf '%s\n' "release artifact directory must be a non-writable root:root directory" >&2
  exit 77
fi
if [ ! -f "$CANDIDATE_RELEASE_ENV" ] || [ -L "$CANDIDATE_RELEASE_ENV" ] || [ "$(readlink -f "$CANDIDATE_RELEASE_ENV")" != "$CANDIDATE_RELEASE_ENV" ] || [ "$(id -u)" -ne 0 ]; then
  printf '%s\n' "candidate release env must be a root-operated regular file" >&2
  exit 77
fi
if [ "$(stat -c '%u:%g:%a' "$CANDIDATE_RELEASE_ENV")" != "0:0:600" ]; then
  printf '%s\n' "candidate release env must be mode 0600 root:root" >&2
  exit 77
fi
if ! LC_ALL=C awk -F= '
  BEGIN {
    allowed["KAI_IMAGE"] = 1
    allowed["KAI_RELEASE_SHA"] = 1
    allowed["KAI_IMAGE_PLATFORM"] = 1
    allowed["KAI_STATE_ROOT"] = 1
    allowed["KAI_UPDATE_CONTAINER_PREFIX"] = 1
    allowed["KAI_BACKUP_CONTAINER_PREFIX"] = 1
    allowed["KAI_BACKUP_RETENTION_HOURLY"] = 1
    allowed["KAI_BACKUP_RETENTION_DAILY"] = 1
    allowed["KAI_BACKUP_RETENTION_MONTHLY"] = 1
    allowed["KAI_BACKUP_RETENTION_MAX_AGE_DAYS"] = 1
  }
  /^# Generated by scripts\/ops\/promote-release\.mjs; contains no credentials\.$/ {
    comments += 1
    next
  }
  /^$/ { next }
  {
    if (NF != 2 || !($1 in allowed) || seen[$1]++ || $2 == "" || $0 ~ /[[:space:][:cntrl:]]/) failed = 1
    values[$1] = $2
    entries += 1
  }
  END {
    if (comments != 1 || entries != 10) failed = 1
    for (key in allowed) if (seen[key] != 1) failed = 1
    if (values["KAI_IMAGE_PLATFORM"] != "linux/amd64") failed = 1
    if (values["KAI_STATE_ROOT"] != "/opt/kai-cloud-3051") failed = 1
    if (values["KAI_UPDATE_CONTAINER_PREFIX"] != "kai-cloud-market-update-3051") failed = 1
    if (values["KAI_BACKUP_CONTAINER_PREFIX"] != "kai-cloud-backup-3051") failed = 1
    if (values["KAI_BACKUP_RETENTION_HOURLY"] != "48") failed = 1
    if (values["KAI_BACKUP_RETENTION_DAILY"] != "30") failed = 1
    if (values["KAI_BACKUP_RETENTION_MONTHLY"] != "0") failed = 1
    if (values["KAI_BACKUP_RETENTION_MAX_AGE_DAYS"] != "30") failed = 1
    exit failed ? 1 : 0
  }
' "$CANDIDATE_RELEASE_ENV"; then
  printf '%s\n' "candidate release env must contain exactly the generated production release policy" >&2
  exit 77
fi
CANDIDATE_ENV_SHA=$(sed -n 's/^KAI_RELEASE_SHA=//p' "$CANDIDATE_RELEASE_ENV")
CANDIDATE_IMAGE=$(sed -n 's/^KAI_IMAGE=//p' "$CANDIDATE_RELEASE_ENV")
if [ "$CANDIDATE_ENV_SHA" != "$CANDIDATE_RELEASE_SHA" ]; then
  printf '%s\n' "candidate release SHA must match its immutable filename" >&2
  exit 77
fi
if ! printf '%s\n' "$CANDIDATE_IMAGE" | grep -Eq '^[a-z0-9]+([._-][a-z0-9]+)*(:[0-9]+)?(/[a-z0-9]+([._-][a-z0-9]+)*)*@sha256:[0-9a-f]{64}$' || [ "${CANDIDATE_IMAGE##*@sha256:}" = "0000000000000000000000000000000000000000000000000000000000000000" ]; then
  printf '%s\n' "candidate image must be a non-placeholder immutable repository digest" >&2
  exit 77
fi
if [ ! -f "$APP_ENV" ] || [ -L "$APP_ENV" ] || [ "$(stat -c '%u:%g:%a' "$APP_ENV")" != "0:0:640" ]; then
  printf '%s\n' "application env must be mode 0640 root:root" >&2
  exit 77
fi
if [ ! -f "$COMPOSE_FILE" ] || [ -L "$COMPOSE_FILE" ] || [ "$(stat -c '%u:%g:%a' "$COMPOSE_FILE")" != "0:0:644" ]; then
  printf '%s\n' "schema gate Compose file must be the fixed mode 0644 root:root installation" >&2
  exit 77
fi
if [ ! -f "$RUNNER_FILE" ] || [ -L "$RUNNER_FILE" ] || [ "$(readlink -f "$0")" != "$RUNNER_FILE" ] || [ "$(stat -c '%u:%g:%a' "$RUNNER_FILE")" != "0:0:755" ]; then
  printf '%s\n' "schema gate runner must be the fixed mode 0755 root:root installation" >&2
  exit 77
fi
if grep -Eq '^(KAI_IMAGE|KAI_RELEASE_SHA|KAI_IMAGE_PLATFORM|KAI_STATE_ROOT|KAI_UPDATE_CONTAINER_PREFIX|KAI_BACKUP_CONTAINER_PREFIX|KAI_BACKUP_RETENTION_HOURLY|KAI_BACKUP_RETENTION_DAILY|KAI_BACKUP_RETENTION_MONTHLY|KAI_BACKUP_RETENTION_MAX_AGE_DAYS)=' "$APP_ENV"; then
  printf '%s\n' "application env must not redefine release-owned keys" >&2
  exit 77
fi

case "$*" in
  "node scripts/ops/verify-qixiang-card-hour-schema.mjs"|\
  "node scripts/ops/verify-qixiang-card-hour-schema.mjs --allow-uninitialized"|\
  "node scripts/ops/verify-qixiang-card-hour-schema.mjs --apply --confirm APPLY_0033_QIXIANG_CARD_HOUR_TOPUPS"|\
  "node scripts/ops/verify-card-hour-topup-appeals-schema.mjs"|\
  "node scripts/ops/verify-card-hour-topup-appeals-schema.mjs --allow-uninitialized"|\
  "node scripts/ops/verify-card-hour-topup-appeals-schema.mjs --apply --confirm APPLY_0036_CARD_HOUR_TOPUP_APPEALS"|\
  "node scripts/ops/verify-card-hour-topup-appeal-reads-schema.mjs"|\
  "node scripts/ops/verify-card-hour-topup-appeal-reads-schema.mjs --apply --confirm APPLY_0037_CARD_HOUR_TOPUP_APPEAL_READS"|\
  "node scripts/ops/verify-card-hour-topup-reconciliation-schema.mjs"|\
  "node scripts/ops/verify-card-hour-topup-reconciliation-schema.mjs --apply --confirm APPLY_0038_CARD_HOUR_TOPUP_RECONCILIATION") ;;
  *)
    printf '%s\n' "schema gate command is not allowlisted" >&2
    exit 64
    ;;
esac

exec env -i \
  HOME=/root \
  PATH=/usr/sbin:/usr/bin:/sbin:/bin \
  DOCKER_CONFIG=/root/.docker \
  /usr/bin/docker compose \
  --project-name kai-cloud-schema-gate \
  --env-file "$APP_ENV" \
  --env-file "$CANDIDATE_RELEASE_ENV" \
  -f "$COMPOSE_FILE" \
  run --rm --no-deps schema-gate "$@"
