"use client";

import { useCallback, useEffect, useState } from "react";
import { AdminApiError, adminGetJson, adminGetRows, adminPostAction } from "@/components/admin-api-client";
import { AdminEmpty, AdminError, AdminLoading } from "@/components/admin-states";
import { useLocale } from "@/components/locale-provider";
import type { Locale } from "@/lib/i18n";
import type { AdminManualAppealCase, ManualAppealResolution, ManualAppealStatus } from "@/lib/server/admin-store";

type TransitionAction = "TRIAGE" | "REQUEST_BUYER" | "REQUEST_SUPPLIER" | "START_REVIEW" | "PROPOSE_RESOLUTION" | "RESOLVE" | "CLOSE" | "REOPEN_REVIEW";
type ManualAppealsCopy = { statuses: Record<ManualAppealStatus,string>; transitions: Record<TransitionAction,string>; outcomes: Record<ManualAppealResolution,string>; kicker:string; title:string; description:string; loading:string; refresh:string; safeError:string; requestId:string; emptyTitle:string; emptyDescription:string; source:string; subject:string; status:string; updated:string; operation:string; view:string; version:string; created:string; resolution:string; none:string; partySummary:string; timeline:string; caseAction:string; chooseAction:string; noAction:string; visibility:string; parties:string; adminOnly:string; message:string; recordMessage:string; adminLabel:string; partiesLabel:string; proofReadOnly:string; proofVerified:string; proofPending:string; offlineOngoing:string; verifiedAt:string; proofCaution:string; noProof:string; completed:string; publicRecorded:string; privateRecorded:string; conflict:string; updatedNotice:string; timelineCreate:string; timelineTransition:string; timelineMessage:string; timelineAssign:string; timelineRefundCreated:string; timelineProofSubmitted:string; timelineProofVerified:string; timelineOfflineTransition:string; timelineFallback:string };
const STATUS_ZH = { OPEN:"待分流",TRIAGED:"已受理",AWAITING_BUYER:"等待买家补充",AWAITING_SUPPLIER:"等待供应商回复",UNDER_REVIEW:"复核中",RESOLUTION_PROPOSED:"处理建议待确认",RESOLVED:"处理建议已记录",CLOSED:"已关闭" } satisfies Record<ManualAppealStatus,string>;
const TRANSITIONS_ZH = { TRIAGE:"受理并分流",REQUEST_BUYER:"请求买家补充",REQUEST_SUPPLIER:"请求供应商回复",START_REVIEW:"开始平台复核",PROPOSE_RESOLUTION:"提出处理建议",RESOLVE:"记录处理结论",CLOSE:"关闭案件",REOPEN_REVIEW:"重新进入复核" } satisfies Record<TransitionAction,string>;
const OUTCOMES_ZH = { NO_ACTION:"建议维持现状",REDELIVERY_RECOMMENDED:"建议重新交付",CANCEL_REQUEST_RECOMMENDED:"建议取消申请",OFFLINE_REFUND_RECOMMENDED:"建议线下退款",OTHER:"其他处理建议" } satisfies Record<ManualAppealResolution,string>;
const STATUS_EN = { OPEN:"Open",TRIAGED:"Triaged",AWAITING_BUYER:"Awaiting buyer",AWAITING_SUPPLIER:"Awaiting supplier",UNDER_REVIEW:"Under review",RESOLUTION_PROPOSED:"Resolution proposed",RESOLVED:"Resolution recorded",CLOSED:"Closed" } satisfies Record<ManualAppealStatus,string>;
const TRANSITIONS_EN = { TRIAGE:"Triage",REQUEST_BUYER:"Request buyer details",REQUEST_SUPPLIER:"Request supplier reply",START_REVIEW:"Start review",PROPOSE_RESOLUTION:"Propose resolution",RESOLVE:"Record resolution",CLOSE:"Close case",REOPEN_REVIEW:"Reopen review" } satisfies Record<TransitionAction,string>;
const OUTCOMES_EN = { NO_ACTION:"Keep current state",REDELIVERY_RECOMMENDED:"Recommend redelivery",CANCEL_REQUEST_RECOMMENDED:"Recommend cancellation",OFFLINE_REFUND_RECOMMENDED:"Recommend offline refund",OTHER:"Other recommendation" } satisfies Record<ManualAppealResolution,string>;
const BASE_EN = { statuses:STATUS_EN,transitions:TRANSITIONS_EN,outcomes:OUTCOMES_EN,kicker:"Manual appeals",title:"Manual Appeal Cases",description:"Appeals, recommendations, and offline refund evidence remain separate. This page cannot automatically refund, move card-hours, or change payment status.",loading:"Loading…",refresh:"Refresh cases",safeError:"Appeal cases cannot be processed right now.",requestId:"Request ID",emptyTitle:"No appeal cases",emptyDescription:"Buyer appeals about manual delivery appear here.",source:"Source request",subject:"Subject",status:"Status",updated:"Updated",operation:"Action",view:"View and handle",version:"Version",created:"Created",resolution:"Recommendation",none:"Not formed",partySummary:"Party-visible explanation",timeline:"Appeal timeline",caseAction:"Case action",chooseAction:"Choose action",noAction:"No state action is available for this case.",visibility:"Message visibility",parties:"Buyer and supplier",adminOnly:"Administrators only",message:"Case message",recordMessage:"Record message",adminLabel:"Admin only",partiesLabel:"Visible to parties",proofReadOnly:"Offline evidence (read only)",proofVerified:"Offline refund proof verified",proofPending:"Offline refund proof pending",offlineOngoing:"Offline record in progress",verifiedAt:"Independent verification: ",proofCaution:"This does not prove funds were returned or received.",noProof:"No independently verified offline refund evidence exists; funds cannot be treated as returned.",completed:"Completed",publicRecorded:"Party-visible message recorded.",privateRecorded:"Internal administrator message recorded.",conflict:"The case changed elsewhere. Review the latest version before resubmitting.",updatedNotice:"Case updated to “{status}”.",timelineCreate:"Buyer submitted appeal",timelineTransition:"Status updated to “{status}”",timelineMessage:"Case message added",timelineAssign:"Case assigned",timelineRefundCreated:"Offline record created",timelineProofSubmitted:"Offline proof submitted",timelineProofVerified:"Offline proof independently verified",timelineOfflineTransition:"Offline record status updated",timelineFallback:"Case progress updated" } satisfies Omit<ManualAppealsCopy,"statuses"|"transitions"|"outcomes"> & Pick<ManualAppealsCopy,"statuses"|"transitions"|"outcomes">;
const zh: ManualAppealsCopy = { ...BASE_EN,statuses:STATUS_ZH,transitions:TRANSITIONS_ZH,outcomes:OUTCOMES_ZH,kicker:"人工申诉",title:"人工申诉案件",description:"申诉、处理建议和线下退款凭证彼此独立；本页不提供自动退款、卡时移动或支付状态修改。",loading:"读取中…",refresh:"刷新案件",safeError:"申诉案件暂时无法处理。",requestId:"请求编号",emptyTitle:"暂无申诉案件",emptyDescription:"买家针对人工交付申请发起申诉后，案件会出现在这里。",source:"来源申请",subject:"主题",status:"状态",updated:"更新时间",operation:"操作",view:"查看与处理",version:"版本",created:"创建",resolution:"处理建议",none:"尚未形成",partySummary:"双方可见处理说明",timeline:"申诉处理时间线",caseAction:"案件动作",chooseAction:"选择案件动作",noAction:"该案件当前没有可执行状态动作。",visibility:"消息可见范围",parties:"买家与供应商可见",adminOnly:"仅管理员可见",message:"处理消息",recordMessage:"记录消息",adminLabel:"仅管理员",partiesLabel:"双方可见",proofReadOnly:"线下处理凭证（只读）",proofVerified:"线下退款凭证已核验",proofPending:"线下退款凭证待核验",offlineOngoing:"线下处理记录进行中",verifiedAt:"独立核验时间：",proofCaution:"不得据此认定资金已经退回或到账。",noProof:"当前没有独立核验后的线下退款凭证，不能认定资金已经退回。",completed:"操作完成",publicRecorded:"公开处理消息已记录。",privateRecorded:"管理员内部消息已记录。",conflict:"案件已被其他操作更新，请确认最新版本后重新提交。",updatedNotice:"案件已更新为“{status}”。",timelineCreate:"买家提交申诉",timelineTransition:"状态更新为“{status}”",timelineMessage:"新增案件消息",timelineAssign:"案件完成分配",timelineRefundCreated:"线下处理记录已创建",timelineProofSubmitted:"线下处理凭证已提交核验",timelineProofVerified:"线下处理凭证已完成独立核验",timelineOfflineTransition:"线下处理记录状态已更新",timelineFallback:"案件处理进度已更新" };
const MANUAL_APPEALS_COPY = {
  "zh-CN": zh,
  "zh-TW": { ...zh, title:"人工申訴案件",description:"申訴、處理建議與線下退款憑證彼此獨立；本頁不提供自動退款、卡時移動或付款狀態修改。",refresh:"重新整理案件",safeError:"目前無法處理申訴案件。",requestId:"請求編號" },
  en: BASE_EN,
  ja: { ...BASE_EN,title:"手動納品の申立て",description:"申立て、提案、オフライン返金証憑は分離され、このページでは返金・カード時移動・支払い変更はできません。",refresh:"案件を更新",safeError:"現在案件を処理できません。",requestId:"リクエスト ID" },
  ko: { ...BASE_EN,title:"수동 제공 이의제기",description:"이의제기, 권고안, 오프라인 환불 증빙은 분리되며 이 페이지에서 자동 환불, 카드시간 이동 또는 결제 상태 변경은 불가합니다.",refresh:"새로고침",safeError:"현재 사건을 처리할 수 없습니다.",requestId:"요청 ID" },
  fr: { ...BASE_EN,title:"Contestations manuelles",description:"Contestations, recommandations et preuves hors ligne restent séparées. Aucun remboursement, transfert d’heures-carte ou changement de paiement n’est possible ici.",refresh:"Actualiser",safeError:"Les dossiers ne peuvent pas être traités actuellement.",requestId:"ID de requête" },
  th: { ...BASE_EN,title:"คำร้องการส่งมอบโดยเจ้าหน้าที่",description:"คำร้อง คำแนะนำ และหลักฐานคืนเงินออฟไลน์แยกจากกัน หน้านี้ไม่คืนเงิน ย้ายชั่วโมงการ์ด หรือแก้สถานะการชำระ",refresh:"รีเฟรช",safeError:"ยังไม่สามารถดำเนินการเรื่องได้",requestId:"รหัสคำขอ" },
  vi: { ...BASE_EN,title:"Khiếu nại bàn giao thủ công",description:"Khiếu nại, đề xuất và chứng từ hoàn tiền ngoại tuyến tách biệt. Trang này không hoàn tiền, chuyển giờ-thẻ hay đổi trạng thái thanh toán.",refresh:"Làm mới",safeError:"Hiện không thể xử lý vụ việc.",requestId:"ID yêu cầu" },
  id: { ...BASE_EN,title:"Banding Penyerahan Manual",description:"Banding, rekomendasi, dan bukti refund luring tetap terpisah. Halaman ini tidak dapat melakukan refund, memindahkan jam-kartu, atau mengubah pembayaran.",refresh:"Muat ulang",safeError:"Kasus belum dapat diproses.",requestId:"ID permintaan" },
  ms: { ...BASE_EN,title:"Rayuan Penyerahan Manual",description:"Rayuan, cadangan dan bukti bayaran balik luar talian kekal berasingan. Halaman ini tidak boleh membayar balik, memindah jam-kad atau mengubah bayaran.",refresh:"Muat semula",safeError:"Kes belum dapat diproses.",requestId:"ID permintaan" },
} satisfies Record<Locale,ManualAppealsCopy>;
const allowedActions: Record<ManualAppealStatus, TransitionAction[]> = {
  OPEN: ["TRIAGE"], TRIAGED: ["REQUEST_BUYER", "REQUEST_SUPPLIER", "START_REVIEW"], AWAITING_BUYER: ["START_REVIEW"], AWAITING_SUPPLIER: ["START_REVIEW"],
  UNDER_REVIEW: ["REQUEST_BUYER", "REQUEST_SUPPLIER", "PROPOSE_RESOLUTION"], RESOLUTION_PROPOSED: ["RESOLVE", "REOPEN_REVIEW"], RESOLVED: ["CLOSE", "REOPEN_REVIEW"], CLOSED: [],
};
function dateTime(value: string | null, locale: Locale) { if (!value) return "—"; const date = new Date(value); return Number.isNaN(date.getTime()) ? "—" : date.toLocaleString(locale); }
function recordFrom(payload: Record<string, unknown>) { if (!payload.record || typeof payload.record !== "object" || Array.isArray(payload.record)) throw new AdminApiError("申诉接口返回格式无效。", 200, "INVALID_RESPONSE"); return payload.record as AdminManualAppealCase; }
function timelineLabel(item: AdminManualAppealCase["timeline"][number], copy: ManualAppealsCopy) {
  if (item.type === "CREATE") return copy.timelineCreate;
  if (item.type === "TRANSITION" && item.toStatus) return copy.timelineTransition.replace("{status}", copy.statuses[item.toStatus]);
  if (item.type === "MESSAGE_ADDED") return copy.timelineMessage;
  if (item.type === "ASSIGN") return copy.timelineAssign;
  if (item.type === "REFUND_RECORD_CREATED") return copy.timelineRefundCreated;
  if (item.type === "REFUND_PROOF_SUBMITTED") return copy.timelineProofSubmitted;
  if (item.type === "REFUND_PROOF_VERIFIED") return copy.timelineProofVerified;
  if (item.type === "OFFLINE_REFUND_TRANSITION") return copy.timelineOfflineTransition;
  return copy.timelineFallback;
}

export function AdminManualAppeals() {
  const { locale } = useLocale(); const copy = MANUAL_APPEALS_COPY[locale];
  const [rows, setRows] = useState<AdminManualAppealCase[]>([]); const [selected, setSelected] = useState<AdminManualAppealCase | null>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState<unknown>(null); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const [action, setAction] = useState<TransitionAction | "">(""); const [outcome, setOutcome] = useState<ManualAppealResolution>("NO_ACTION"); const [resolutionSummary, setResolutionSummary] = useState("");
  const [messageBody, setMessageBody] = useState(""); const [visibility, setVisibility] = useState<"PARTIES" | "ADMIN_ONLY">("PARTIES");
  const load = useCallback(async () => {
    setLoading(true); setError(null);
    try { const records = await adminGetRows({ path: "/api/v1/admin/appeals" }) as unknown as AdminManualAppealCase[]; setRows(records); setSelected((current) => current ? records.find((record) => record.id === current.id) ?? current : null); }
    catch (reason) { setError(reason); } finally { setLoading(false); }
  }, []);
  useEffect(() => { const frame = window.requestAnimationFrame(() => { void load(); }); return () => window.cancelAnimationFrame(frame); }, [load]);
  async function selectCase(caseId: string) { setError(null); setNotice(""); try { const record = recordFrom(await adminGetJson(`/api/v1/admin/appeals/${encodeURIComponent(caseId)}`)); setSelected(record); setAction(allowedActions[record.status][0] ?? ""); } catch (reason) { setError(reason); } }
  function updateRecord(record: AdminManualAppealCase) { setSelected(record); setRows((current) => current.map((item) => item.id === record.id ? record : item)); setAction(allowedActions[record.status][0] ?? ""); }
  async function transition() {
    if (!selected || !action) return; setBusy(true); setError(null); setNotice("");
    const proposing = action === "PROPOSE_RESOLUTION";
    try {
      const record = recordFrom(await adminPostAction(`/api/v1/admin/appeals/${encodeURIComponent(selected.id)}/transition`, { action, expectedVersion: selected.version, resolutionOutcome: proposing ? outcome : undefined, resolutionSummary: proposing ? resolutionSummary.trim() : undefined }));
      updateRecord(record); setResolutionSummary(""); setNotice(copy.updatedNotice.replace("{status}", copy.statuses[record.status]));
    } catch (reason) { setError(reason); } finally { setBusy(false); }
  }
  async function addMessage() {
    if (!selected || !messageBody.trim()) return; setBusy(true); setError(null); setNotice("");
    try { const record = recordFrom(await adminPostAction(`/api/v1/admin/appeals/${encodeURIComponent(selected.id)}/messages`, { body: messageBody.trim(), visibility, expectedVersion: selected.version })); updateRecord(record); setMessageBody(""); setNotice(visibility === "PARTIES" ? copy.publicRecorded : copy.privateRecorded); }
    catch (reason) {
      if (reason instanceof AdminApiError && reason.status === 409) {
        await selectCase(selected.id);
        setNotice(copy.conflict);
      } else setError(reason);
    } finally { setBusy(false); }
  }

  return <section className="admin-appeals" aria-labelledby="admin-appeals-title">
    <header className="admin-manual-delivery-head"><div><p className="admin-kicker">{copy.kicker}</p><h1 id="admin-appeals-title">{copy.title}</h1><span>{copy.description}</span></div><button className="admin-button secondary" disabled={loading} onClick={() => void load()} type="button">{loading ? copy.loading : copy.refresh}</button></header>
    {loading && rows.length === 0 ? <AdminLoading /> : null}{error ? <AdminError message={`${copy.safeError}${error instanceof AdminApiError && error.requestId ? ` (${copy.requestId}: ${error.requestId})` : ""}`} onRetry={() => void load()} /> : null}
    {!loading && !error && rows.length === 0 ? <AdminEmpty description={copy.emptyDescription} title={copy.emptyTitle} /> : null}
    {rows.length ? <div className="admin-table-wrap"><table className="admin-table"><caption>{copy.title}</caption><thead><tr><th>ID</th><th>{copy.source}</th><th>{copy.subject}</th><th>{copy.status}</th><th>{copy.updated}</th><th>{copy.operation}</th></tr></thead><tbody>{rows.map((record) => <tr key={record.id}><td className="admin-mono">{record.caseNumber}</td><td className="admin-mono">{record.sourceId}</td><td>{record.subject}</td><td><span className={`admin-status ${record.status === "CLOSED" ? "success" : "warning"}`}>{copy.statuses[record.status]}</span></td><td>{dateTime(record.updatedAt, locale)}</td><td><button className="admin-button secondary" onClick={() => void selectCase(record.id)} type="button">{copy.view}</button></td></tr>)}</tbody></table></div> : null}
    {selected ? <section className="admin-action-panel admin-appeal-detail"><div><p className="admin-kicker">{selected.caseNumber}</p><h2>{selected.subject}</h2><span>{selected.sourceId} · {copy.statuses[selected.status]} · {copy.version} {selected.version}</span><p>{selected.description}</p><dl className="admin-manual-timeline"><div><dt>{copy.created}</dt><dd>{dateTime(selected.createdAt, locale)}</dd></div><div><dt>{copy.updated}</dt><dd>{dateTime(selected.updatedAt, locale)}</dd></div><div><dt>{copy.resolution}</dt><dd>{selected.partySafeResolutionOutcome ? copy.outcomes[selected.partySafeResolutionOutcome] : copy.none}</dd></div></dl>{selected.partySafeResolutionSummary ? <p><small>{copy.partySummary}</small><br />{selected.partySafeResolutionSummary}</p> : null}<ol className="admin-appeal-timeline" aria-label={copy.timeline}>{selected.timeline.map((item) => <li key={item.id}><strong>{timelineLabel(item, copy)}</strong><time dateTime={item.occurredAt}>{dateTime(item.occurredAt, locale)}</time></li>)}</ol></div>
      <div className="admin-action-fields">
        {allowedActions[selected.status].length ? <><label><span>{copy.caseAction}</span><select value={action} onChange={(event) => setAction(event.target.value as TransitionAction)}>{allowedActions[selected.status].map((value) => <option key={value} value={value}>{copy.transitions[value]}</option>)}</select></label>{action === "PROPOSE_RESOLUTION" ? <><label><span>{copy.resolution}</span><select value={outcome} onChange={(event) => setOutcome(event.target.value as ManualAppealResolution)}>{Object.entries(copy.outcomes).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label><span>{copy.partySummary}</span><textarea value={resolutionSummary} onChange={(event) => setResolutionSummary(event.target.value)} /></label></> : null}<button className="admin-button primary" disabled={busy || (action === "PROPOSE_RESOLUTION" && resolutionSummary.trim().length < 10)} onClick={() => void transition()} type="button">{busy ? copy.loading : action ? copy.transitions[action] : copy.chooseAction}</button></> : <p>{copy.noAction}</p>}
        <label><span>{copy.visibility}</span><select value={visibility} onChange={(event) => setVisibility(event.target.value as "PARTIES" | "ADMIN_ONLY")}><option value="PARTIES">{copy.parties}</option><option value="ADMIN_ONLY">{copy.adminOnly}</option></select></label><label><span>{copy.message}</span><textarea value={messageBody} onChange={(event) => setMessageBody(event.target.value)} /></label><button className="admin-button secondary" disabled={busy || !messageBody.trim()} onClick={() => void addMessage()} type="button">{copy.recordMessage}</button>
        <div className="admin-appeal-messages">{selected.messages.map((message) => <p key={message.id}><strong>{message.authorType} · {message.visibility === "ADMIN_ONLY" ? copy.adminLabel : copy.partiesLabel}</strong><span>{message.body}</span><time dateTime={message.createdAt}>{dateTime(message.createdAt, locale)}</time></p>)}</div>
        {selected.offlineRefunds.length ? <div className="admin-appeal-refunds"><strong>{copy.proofReadOnly}</strong>{selected.offlineRefunds.map((item) => { const verified = item.status === "INDEPENDENTLY_VERIFIED" && Boolean(item.proofVerifiedAt); return <p key={item.id}><strong>{verified ? copy.proofVerified : item.status === "PROOF_SUBMITTED" ? copy.proofPending : copy.offlineOngoing}</strong><span>{verified ? `${copy.verifiedAt}${dateTime(item.proofVerifiedAt, locale)}` : copy.proofCaution}</span></p>; })}</div> : <p className="admin-inline-warning">{copy.noProof}</p>}
        {notice ? <div className="admin-inline-success" role="status"><strong>{copy.completed}</strong><span>{notice}</span></div> : null}
      </div></section> : null}
  </section>;
}
