"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import { AdminApiError, adminGetJson, adminPostAction } from "@/components/admin-api-client";
import { AdminEmpty, AdminError, AdminLoading } from "@/components/admin-states";
import { useLocale } from "@/components/locale-provider";
import { formatCardHourDisplayMicros } from "@/lib/card-hours";
import type { Locale } from "@/lib/i18n";
import type { CardHourTopupAppealRecord, CardHourTopupAppealStatus } from "@/lib/server/card-hour-store";

type Action = "START_REVIEW" | "RESOLVE" | "CLOSE";
type TopupAppealsCopy = {
  statuses: Record<CardHourTopupAppealStatus, string>; actions: Record<Action, string>; kicker: string; title: string; description: string; loading: string; refresh: string; status: string; allStatuses: string; order: string; organization: string; organizationPlaceholder: string; pageSize: string; records: string; apply: string; reset: string; safeError: string; requestId: string; emptyTitle: string; emptyDescription: string; amountCardHours: string; orderStatus: string; updated: string; operation: string; view: string; paginationAria: string; pageOf: string; previous: string; next: string; version: string; organizationAccount: string; topup: string; cardHours: string; currentOrderStatus: string; createdUpdated: string; resolution: string; closed: string; warning: string; processing: string; completed: string; updatedNotice: string;
};
const TOPUP_APPEALS_COPY = {
  "zh-CN": { statuses: { OPEN: "待人工受理", UNDER_REVIEW: "人工核对中", RESOLVED: "已形成结论", CLOSED: "已关闭" }, actions: { START_REVIEW: "开始人工核对", RESOLVE: "记录核对结论", CLOSE: "关闭案件" }, kicker: "付款申诉", title: "充值异常申诉", description: "按付款单人工核对；本页不提供修改支付状态、手工入账或自动退款能力。", loading: "读取中…", refresh: "刷新案件", status: "案件状态", allStatuses: "全部状态", order: "付款单", organization: "组织", organizationPlaceholder: "组织 ID", pageSize: "每页数量", records: "条", apply: "应用筛选", reset: "重置", safeError: "充值申诉暂时无法处理。", requestId: "请求编号", emptyTitle: "暂无充值申诉", emptyDescription: "用户针对付款单发起充值异常申诉后，案件会出现在这里。", amountCardHours: "金额 / 卡时", orderStatus: "付款单状态", updated: "更新时间", operation: "操作", view: "查看与处理", paginationAria: "充值申诉分页", pageOf: "第 {page} / {pages} 页 · 共 {total} 条", previous: "上一页", next: "下一页", version: "版本", organizationAccount: "组织 / 账号", topup: "充值", cardHours: "卡时", currentOrderStatus: "当前付款单状态", createdUpdated: "创建 / 更新", resolution: "人工核对结论", closed: "案件已经关闭，没有可执行动作。", warning: "任何案件动作都不会修改付款单、卡时余额或退款状态；资金处理必须走独立人工流程。", processing: "处理中…", completed: "操作完成", updatedNotice: "案件已更新为“{status}”。" },
  "zh-TW": { statuses: { OPEN: "待人工受理", UNDER_REVIEW: "人工核對中", RESOLVED: "已形成結論", CLOSED: "已關閉" }, actions: { START_REVIEW: "開始人工核對", RESOLVE: "記錄核對結論", CLOSE: "關閉案件" }, kicker: "付款申訴", title: "充值異常申訴", description: "依付款單人工核對；本頁不提供修改付款狀態、手工入帳或自動退款。", loading: "讀取中…", refresh: "重新整理案件", status: "案件狀態", allStatuses: "全部狀態", order: "付款單", organization: "組織", organizationPlaceholder: "組織 ID", pageSize: "每頁數量", records: "筆", apply: "套用篩選", reset: "重設", safeError: "目前無法處理充值申訴。", requestId: "請求編號", emptyTitle: "暫無充值申訴", emptyDescription: "使用者針對付款單發起充值異常申訴後，案件會顯示在此。", amountCardHours: "金額 / 卡時", orderStatus: "付款單狀態", updated: "更新時間", operation: "操作", view: "查看與處理", paginationAria: "充值申訴分頁", pageOf: "第 {page} / {pages} 頁 · 共 {total} 筆", previous: "上一頁", next: "下一頁", version: "版本", organizationAccount: "組織 / 帳號", topup: "充值", cardHours: "卡時", currentOrderStatus: "目前付款單狀態", createdUpdated: "建立 / 更新", resolution: "人工核對結論", closed: "案件已關閉，沒有可執行動作。", warning: "任何案件動作都不會修改付款單、卡時餘額或退款狀態；資金處理必須走獨立人工流程。", processing: "處理中…", completed: "操作完成", updatedNotice: "案件已更新為「{status}」。" },
  en: { statuses: { OPEN: "Awaiting intake", UNDER_REVIEW: "Under manual review", RESOLVED: "Resolution recorded", CLOSED: "Closed" }, actions: { START_REVIEW: "Start manual review", RESOLVE: "Record review outcome", CLOSE: "Close case" }, kicker: "Payment appeals", title: "Top-up Appeals", description: "Review each payment order manually. This page cannot change payment state, credit balances, or issue automatic refunds.", loading: "Loading…", refresh: "Refresh cases", status: "Case status", allStatuses: "All statuses", order: "Payment order", organization: "Organization", organizationPlaceholder: "Organization ID", pageSize: "Rows per page", records: "records", apply: "Apply filters", reset: "Reset", safeError: "Top-up appeals cannot be processed right now.", requestId: "Request ID", emptyTitle: "No top-up appeals", emptyDescription: "Cases appear here after a user appeals a payment order.", amountCardHours: "Amount / card-hours", orderStatus: "Payment status", updated: "Updated", operation: "Action", view: "View and handle", paginationAria: "Top-up appeal pagination", pageOf: "Page {page} / {pages} · {total} total", previous: "Previous", next: "Next", version: "Version", organizationAccount: "Organization / account", topup: "Top-up", cardHours: "card-hours", currentOrderStatus: "Current payment status", createdUpdated: "Created / updated", resolution: "Manual review outcome", closed: "This case is closed and has no available action.", warning: "Case actions never change the payment order, card-hour balance, or refund state. Funds must be handled in a separate manual process.", processing: "Processing…", completed: "Completed", updatedNotice: "Case updated to “{status}”." },
  ja: { statuses: { OPEN: "受付待ち", UNDER_REVIEW: "手動確認中", RESOLVED: "結論記録済み", CLOSED: "終了" }, actions: { START_REVIEW: "手動確認を開始", RESOLVE: "確認結果を記録", CLOSE: "案件を終了" }, kicker: "支払い申立て", title: "チャージ異常申立て", description: "支払い注文ごとに手動確認します。このページでは支払い状態、残高、返金を変更できません。", loading: "読込中…", refresh: "案件を更新", status: "案件状態", allStatuses: "すべて", order: "支払い注文", organization: "組織", organizationPlaceholder: "組織 ID", pageSize: "表示件数", records: "件", apply: "絞り込み", reset: "リセット", safeError: "現在、申立てを処理できません。", requestId: "リクエスト ID", emptyTitle: "申立てはありません", emptyDescription: "支払い注文への申立てが送信されるとここに表示されます。", amountCardHours: "金額 / カード時", orderStatus: "支払い状態", updated: "更新日", operation: "操作", view: "確認・処理", paginationAria: "申立てページ", pageOf: "{page} / {pages} ページ · 全 {total} 件", previous: "前へ", next: "次へ", version: "バージョン", organizationAccount: "組織 / アカウント", topup: "チャージ", cardHours: "カード時", currentOrderStatus: "現在の支払い状態", createdUpdated: "作成 / 更新", resolution: "手動確認結果", closed: "この案件は終了しており操作できません。", warning: "案件操作で支払い注文、カード時残高、返金状態は変更されません。資金処理は別の手動手順で行います。", processing: "処理中…", completed: "完了", updatedNotice: "案件を「{status}」に更新しました。" },
  ko: { statuses: { OPEN: "접수 대기", UNDER_REVIEW: "수동 검토 중", RESOLVED: "결론 기록됨", CLOSED: "종료" }, actions: { START_REVIEW: "수동 검토 시작", RESOLVE: "검토 결과 기록", CLOSE: "사건 종료" }, kicker: "결제 이의제기", title: "충전 이상 이의제기", description: "결제 주문별로 수동 검토합니다. 이 페이지는 결제 상태, 잔액 또는 환불을 변경하지 않습니다.", loading: "불러오는 중…", refresh: "사건 새로고침", status: "사건 상태", allStatuses: "전체 상태", order: "결제 주문", organization: "조직", organizationPlaceholder: "조직 ID", pageSize: "페이지 크기", records: "건", apply: "필터 적용", reset: "초기화", safeError: "현재 충전 이의제기를 처리할 수 없습니다.", requestId: "요청 ID", emptyTitle: "충전 이의제기 없음", emptyDescription: "사용자가 결제 주문에 이의를 제기하면 여기에 표시됩니다.", amountCardHours: "금액 / 카드시간", orderStatus: "결제 상태", updated: "업데이트", operation: "작업", view: "보기 및 처리", paginationAria: "충전 이의제기 페이지", pageOf: "{page} / {pages} 페이지 · 총 {total}건", previous: "이전", next: "다음", version: "버전", organizationAccount: "조직 / 계정", topup: "충전", cardHours: "카드시간", currentOrderStatus: "현재 결제 상태", createdUpdated: "생성 / 업데이트", resolution: "수동 검토 결과", closed: "종료된 사건으로 실행 가능한 작업이 없습니다.", warning: "사건 작업은 결제 주문, 카드시간 잔액 또는 환불 상태를 변경하지 않습니다. 자금 처리는 별도 수동 절차를 거쳐야 합니다.", processing: "처리 중…", completed: "완료", updatedNotice: "사건이 “{status}” 상태로 업데이트되었습니다." },
  fr: { statuses: { OPEN: "À prendre en charge", UNDER_REVIEW: "Examen manuel", RESOLVED: "Conclusion enregistrée", CLOSED: "Clos" }, actions: { START_REVIEW: "Commencer l’examen", RESOLVE: "Enregistrer la conclusion", CLOSE: "Clore le dossier" }, kicker: "Contestations de paiement", title: "Contestations de recharge", description: "Examen manuel par ordre de paiement. Cette page ne modifie ni le paiement, ni le solde, ni les remboursements.", loading: "Chargement…", refresh: "Actualiser", status: "État du dossier", allStatuses: "Tous", order: "Ordre de paiement", organization: "Organisation", organizationPlaceholder: "ID d’organisation", pageSize: "Par page", records: "éléments", apply: "Appliquer", reset: "Réinitialiser", safeError: "Les contestations ne peuvent pas être traitées actuellement.", requestId: "ID de requête", emptyTitle: "Aucune contestation", emptyDescription: "Les contestations d’un ordre de paiement apparaissent ici.", amountCardHours: "Montant / heures-carte", orderStatus: "État du paiement", updated: "Mis à jour", operation: "Action", view: "Voir et traiter", paginationAria: "Pagination des contestations", pageOf: "Page {page} / {pages} · {total} au total", previous: "Précédent", next: "Suivant", version: "Version", organizationAccount: "Organisation / compte", topup: "Recharge", cardHours: "heures-carte", currentOrderStatus: "État actuel du paiement", createdUpdated: "Créé / mis à jour", resolution: "Conclusion de l’examen", closed: "Ce dossier est clos et ne permet plus d’action.", warning: "Les actions ne modifient jamais l’ordre, le solde ou le remboursement. Les fonds suivent une procédure manuelle séparée.", processing: "Traitement…", completed: "Terminé", updatedNotice: "Dossier mis à jour : « {status} »." },
  th: { statuses: { OPEN: "รอรับเรื่อง", UNDER_REVIEW: "กำลังตรวจสอบ", RESOLVED: "บันทึกผลแล้ว", CLOSED: "ปิดแล้ว" }, actions: { START_REVIEW: "เริ่มตรวจสอบ", RESOLVE: "บันทึกผลตรวจสอบ", CLOSE: "ปิดเรื่อง" }, kicker: "คำร้องการชำระเงิน", title: "คำร้องปัญหาการเติมเงิน", description: "ตรวจสอบด้วยเจ้าหน้าที่ตามรายการชำระเงิน หน้านี้ไม่แก้ไขสถานะการชำระ ยอดคงเหลือ หรือคืนเงินอัตโนมัติ", loading: "กำลังโหลด…", refresh: "รีเฟรชเรื่อง", status: "สถานะเรื่อง", allStatuses: "ทุกสถานะ", order: "รายการชำระเงิน", organization: "องค์กร", organizationPlaceholder: "รหัสองค์กร", pageSize: "จำนวนต่อหน้า", records: "รายการ", apply: "ใช้ตัวกรอง", reset: "รีเซ็ต", safeError: "ยังไม่สามารถดำเนินการคำร้องได้", requestId: "รหัสคำขอ", emptyTitle: "ไม่มีคำร้อง", emptyDescription: "คำร้องต่อรายการชำระเงินจะแสดงที่นี่", amountCardHours: "จำนวนเงิน / ชั่วโมงการ์ด", orderStatus: "สถานะการชำระ", updated: "อัปเดต", operation: "การทำงาน", view: "ดูและดำเนินการ", paginationAria: "หน้าคำร้องเติมเงิน", pageOf: "หน้า {page} / {pages} · รวม {total} รายการ", previous: "ก่อนหน้า", next: "ถัดไป", version: "เวอร์ชัน", organizationAccount: "องค์กร / บัญชี", topup: "เติมเงิน", cardHours: "ชั่วโมงการ์ด", currentOrderStatus: "สถานะการชำระปัจจุบัน", createdUpdated: "สร้าง / อัปเดต", resolution: "ผลตรวจสอบ", closed: "เรื่องปิดแล้วและไม่มีการทำงานที่ทำได้", warning: "การทำงานกับเรื่องจะไม่แก้ไขรายการชำระ ยอดชั่วโมงการ์ด หรือสถานะคืนเงิน การเงินต้องใช้กระบวนการแยกต่างหาก", processing: "กำลังดำเนินการ…", completed: "เสร็จสิ้น", updatedNotice: "อัปเดตเรื่องเป็น “{status}” แล้ว" },
  vi: { statuses: { OPEN: "Chờ tiếp nhận", UNDER_REVIEW: "Đang kiểm tra", RESOLVED: "Đã ghi kết luận", CLOSED: "Đã đóng" }, actions: { START_REVIEW: "Bắt đầu kiểm tra", RESOLVE: "Ghi kết luận", CLOSE: "Đóng vụ việc" }, kicker: "Khiếu nại thanh toán", title: "Khiếu nại nạp tiền", description: "Kiểm tra thủ công theo đơn thanh toán. Trang này không thay đổi thanh toán, số dư hoặc hoàn tiền.", loading: "Đang tải…", refresh: "Làm mới", status: "Trạng thái", allStatuses: "Tất cả", order: "Đơn thanh toán", organization: "Tổ chức", organizationPlaceholder: "ID tổ chức", pageSize: "Mỗi trang", records: "mục", apply: "Áp dụng", reset: "Đặt lại", safeError: "Hiện không thể xử lý khiếu nại nạp tiền.", requestId: "ID yêu cầu", emptyTitle: "Không có khiếu nại", emptyDescription: "Khiếu nại về đơn thanh toán sẽ xuất hiện tại đây.", amountCardHours: "Số tiền / giờ-thẻ", orderStatus: "Trạng thái thanh toán", updated: "Cập nhật", operation: "Thao tác", view: "Xem và xử lý", paginationAria: "Phân trang khiếu nại", pageOf: "Trang {page} / {pages} · tổng {total} mục", previous: "Trước", next: "Sau", version: "Phiên bản", organizationAccount: "Tổ chức / tài khoản", topup: "Nạp tiền", cardHours: "giờ-thẻ", currentOrderStatus: "Trạng thái thanh toán hiện tại", createdUpdated: "Tạo / cập nhật", resolution: "Kết luận kiểm tra", closed: "Vụ việc đã đóng và không còn thao tác.", warning: "Thao tác vụ việc không thay đổi đơn thanh toán, số dư giờ-thẻ hoặc hoàn tiền. Tiền phải được xử lý theo quy trình thủ công riêng.", processing: "Đang xử lý…", completed: "Hoàn tất", updatedNotice: "Đã cập nhật vụ việc thành “{status}”." },
  id: { statuses: { OPEN: "Menunggu penerimaan", UNDER_REVIEW: "Dalam tinjauan", RESOLVED: "Hasil dicatat", CLOSED: "Ditutup" }, actions: { START_REVIEW: "Mulai tinjauan", RESOLVE: "Catat hasil", CLOSE: "Tutup kasus" }, kicker: "Banding pembayaran", title: "Banding Isi Ulang", description: "Tinjau manual per pesanan pembayaran. Halaman ini tidak mengubah pembayaran, saldo, atau refund.", loading: "Memuat…", refresh: "Muat ulang kasus", status: "Status kasus", allStatuses: "Semua status", order: "Pesanan pembayaran", organization: "Organisasi", organizationPlaceholder: "ID organisasi", pageSize: "Per halaman", records: "catatan", apply: "Terapkan", reset: "Atur ulang", safeError: "Banding isi ulang belum dapat diproses.", requestId: "ID permintaan", emptyTitle: "Tidak ada banding", emptyDescription: "Banding atas pesanan pembayaran akan muncul di sini.", amountCardHours: "Jumlah / jam-kartu", orderStatus: "Status pembayaran", updated: "Diperbarui", operation: "Tindakan", view: "Lihat dan tangani", paginationAria: "Halaman banding", pageOf: "Halaman {page} / {pages} · total {total}", previous: "Sebelumnya", next: "Berikutnya", version: "Versi", organizationAccount: "Organisasi / akun", topup: "Isi ulang", cardHours: "jam-kartu", currentOrderStatus: "Status pembayaran saat ini", createdUpdated: "Dibuat / diperbarui", resolution: "Hasil tinjauan", closed: "Kasus ditutup dan tidak memiliki tindakan.", warning: "Tindakan kasus tidak mengubah pesanan, saldo jam-kartu, atau refund. Dana harus ditangani melalui proses manual terpisah.", processing: "Memproses…", completed: "Selesai", updatedNotice: "Kasus diperbarui ke “{status}”." },
  ms: { statuses: { OPEN: "Menunggu penerimaan", UNDER_REVIEW: "Dalam semakan", RESOLVED: "Hasil direkodkan", CLOSED: "Ditutup" }, actions: { START_REVIEW: "Mula semakan", RESOLVE: "Rekod hasil", CLOSE: "Tutup kes" }, kicker: "Rayuan bayaran", title: "Rayuan Tambah Nilai", description: "Semak secara manual mengikut pesanan bayaran. Halaman ini tidak mengubah bayaran, baki atau bayaran balik.", loading: "Memuatkan…", refresh: "Muat semula kes", status: "Status kes", allStatuses: "Semua status", order: "Pesanan bayaran", organization: "Organisasi", organizationPlaceholder: "ID organisasi", pageSize: "Setiap halaman", records: "rekod", apply: "Gunakan", reset: "Tetapkan semula", safeError: "Rayuan tambah nilai belum dapat diproses.", requestId: "ID permintaan", emptyTitle: "Tiada rayuan", emptyDescription: "Rayuan terhadap pesanan bayaran akan muncul di sini.", amountCardHours: "Jumlah / jam-kad", orderStatus: "Status bayaran", updated: "Dikemas kini", operation: "Tindakan", view: "Lihat dan urus", paginationAria: "Halaman rayuan", pageOf: "Halaman {page} / {pages} · jumlah {total}", previous: "Sebelumnya", next: "Seterusnya", version: "Versi", organizationAccount: "Organisasi / akaun", topup: "Tambah nilai", cardHours: "jam-kad", currentOrderStatus: "Status bayaran semasa", createdUpdated: "Dicipta / dikemas kini", resolution: "Hasil semakan", closed: "Kes ditutup dan tiada tindakan tersedia.", warning: "Tindakan kes tidak mengubah pesanan, baki jam-kad atau bayaran balik. Dana mesti diurus melalui proses manual berasingan.", processing: "Memproses…", completed: "Selesai", updatedNotice: "Kes dikemas kini kepada “{status}”." },
} satisfies Record<Locale, TopupAppealsCopy>;
const allowedAction: Record<CardHourTopupAppealStatus, Action | null> = { OPEN: "START_REVIEW", UNDER_REVIEW: "RESOLVE", RESOLVED: "CLOSE", CLOSED: null };
function dateTime(value: string, locale: Locale) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "—" : date.toLocaleString(locale); }
function money(cents: number, locale: Locale) { return new Intl.NumberFormat(locale, { style: "currency", currency: "CNY" }).format(cents / 100); }
function safeError(error: unknown, copy: TopupAppealsCopy) { const requestId = error instanceof AdminApiError ? error.requestId : undefined; return `${copy.safeError}${requestId ? ` (${copy.requestId}: ${requestId})` : ""}`; }

export function AdminCardHourTopupAppeals() {
  const { locale } = useLocale();
  const copy = TOPUP_APPEALS_COPY[locale];
  const [records, setRecords] = useState<CardHourTopupAppealRecord[]>([]);
  const [selected, setSelected] = useState<CardHourTopupAppealRecord | null>(null);
  const [resolutionNote, setResolutionNote] = useState("");
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<unknown>(null);
  const [notice, setNotice] = useState("");
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(20);
  const [total, setTotal] = useState(0);
  const [totalPages, setTotalPages] = useState(1);
  const [draftStatus, setDraftStatus] = useState("");
  const [draftOrderId, setDraftOrderId] = useState("");
  const [draftOrganizationId, setDraftOrganizationId] = useState("");
  const [filters, setFilters] = useState({ status: "", orderId: "", organizationId: "" });
  const load = useCallback(async () => {
    setLoading(true); setError(null);
    try {
      const params = new URLSearchParams({ page: String(page), pageSize: String(pageSize) });
      if (filters.status) params.set("status", filters.status);
      if (filters.orderId) params.set("orderId", filters.orderId);
      if (filters.organizationId) params.set("organizationId", filters.organizationId);
      const payload = await adminGetJson(`/api/v1/admin/card-hour-topup-appeals?${params.toString()}`);
      const rows = Array.isArray(payload.records) ? payload.records as CardHourTopupAppealRecord[] : [];
      setRecords(rows); setTotal(Number(payload.total ?? 0)); setTotalPages(Math.max(1, Number(payload.totalPages ?? 1)));
      setSelected((current) => current ? rows.find((item) => item.id === current.id) ?? null : null);
    } catch (reason) { setError(reason); } finally { setLoading(false); }
  }, [filters, page, pageSize]);
  useEffect(() => { const frame = window.requestAnimationFrame(() => { void load(); }); return () => window.cancelAnimationFrame(frame); }, [load]);
  function applyFilters(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setPage(1); setFilters({ status: draftStatus, orderId: draftOrderId.trim(), organizationId: draftOrganizationId.trim() });
  }
  function resetFilters() {
    setDraftStatus(""); setDraftOrderId(""); setDraftOrganizationId(""); setPage(1); setFilters({ status: "", orderId: "", organizationId: "" });
  }
  async function transition() {
    if (!selected) return;
    const action = allowedAction[selected.status];
    if (!action) return;
    setBusy(true); setError(null); setNotice("");
    try {
      const payload = await adminPostAction("/api/v1/admin/card-hour-topup-appeals", { appealId: selected.id, action, expectedVersion: selected.version, resolutionNote: action === "RESOLVE" ? resolutionNote.trim() : undefined });
      const updated = payload.record as CardHourTopupAppealRecord;
      setRecords((current) => current.map((item) => item.id === updated.id ? updated : item)); setSelected(updated); setResolutionNote(""); setNotice(copy.updatedNotice.replace("{status}", copy.statuses[updated.status]));
    } catch (reason) { setError(reason); } finally { setBusy(false); }
  }
  return <section className="admin-appeals" aria-labelledby="admin-topup-appeals-title">
    <header className="admin-manual-delivery-head"><div><p className="admin-kicker">{copy.kicker}</p><h1 id="admin-topup-appeals-title">{copy.title}</h1><span>{copy.description}</span></div><button className="admin-button secondary" disabled={loading} onClick={() => void load()} type="button">{loading ? copy.loading : copy.refresh}</button></header>
    <form className="admin-filterbar admin-topup-appeal-filters" onSubmit={applyFilters}>
      <label className="admin-select-filter"><span>{copy.status}</span><select onChange={(event) => setDraftStatus(event.target.value)} value={draftStatus}><option value="">{copy.allStatuses}</option>{Object.entries(copy.statuses).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>
      <label className="admin-search"><span>{copy.order}</span><input maxLength={96} onChange={(event) => setDraftOrderId(event.target.value)} placeholder="KAI_CH_…" type="search" value={draftOrderId} /></label>
      <label className="admin-search"><span>{copy.organization}</span><input maxLength={128} onChange={(event) => setDraftOrganizationId(event.target.value)} placeholder={copy.organizationPlaceholder} type="search" value={draftOrganizationId} /></label>
      <label className="admin-select-filter"><span>{copy.pageSize}</span><select onChange={(event) => { setPage(1); setPageSize(Number(event.target.value)); }} value={pageSize}><option value="10">10 {copy.records}</option><option value="20">20 {copy.records}</option><option value="50">50 {copy.records}</option></select></label>
      <div className="admin-filter-actions"><button className="admin-button primary" disabled={loading} type="submit">{copy.apply}</button><button className="admin-button secondary" disabled={loading} onClick={resetFilters} type="button">{copy.reset}</button></div>
    </form>
    {loading && records.length === 0 ? <AdminLoading /> : null}{error ? <AdminError message={safeError(error, copy)} onRetry={() => void load()} /> : null}
    {!loading && !error && records.length === 0 ? <AdminEmpty description={copy.emptyDescription} title={copy.emptyTitle} /> : null}
    {records.length ? <><div className="admin-table-wrap"><table className="admin-table"><caption>{copy.title}</caption><thead><tr><th>{copy.status}</th><th>{copy.order}</th><th>{copy.organization}</th><th>{copy.amountCardHours}</th><th>{copy.orderStatus}</th><th>{copy.status}</th><th>{copy.updated}</th><th>{copy.operation}</th></tr></thead><tbody>{records.map((record) => <tr key={record.id}><td className="admin-mono">{record.caseNumber}</td><td className="admin-mono">{record.topupOrderId}</td><td className="admin-mono">{record.organizationId}</td><td>{money(record.amountCents, locale)} / {formatCardHourDisplayMicros(record.cardHourMicros)}</td><td>{record.topupStatus}</td><td><span className={`admin-status ${record.status === "CLOSED" ? "success" : "warning"}`}>{copy.statuses[record.status]}</span></td><td>{dateTime(record.updatedAt, locale)}</td><td><button className="admin-button secondary" onClick={() => { setSelected(record); setResolutionNote(""); setNotice(""); }} type="button">{copy.view}</button></td></tr>)}</tbody></table></div><nav aria-label={copy.paginationAria} className="admin-pagination"><span>{copy.pageOf.replace("{page}", String(page)).replace("{pages}", String(totalPages)).replace("{total}", String(total))}</span><div><button className="admin-button secondary" disabled={loading || page <= 1} onClick={() => setPage((value) => Math.max(1, value - 1))} type="button">{copy.previous}</button><button className="admin-button secondary" disabled={loading || page >= totalPages} onClick={() => setPage((value) => Math.min(totalPages, value + 1))} type="button">{copy.next}</button></div></nav></> : null}
    {selected ? <section className="admin-action-panel admin-appeal-detail"><div><p className="admin-kicker">{selected.caseNumber}</p><h2>{selected.topupOrderId}</h2><span>{copy.statuses[selected.status]} · {copy.version} {selected.version}</span><p>{selected.description}</p><dl className="admin-manual-timeline"><div><dt>{copy.organizationAccount}</dt><dd>{selected.organizationId}<br />{selected.accountId}</dd></div><div><dt>{copy.topup}</dt><dd>{formatCardHourDisplayMicros(selected.cardHourMicros)} {copy.cardHours} · {money(selected.amountCents, locale)}</dd></div><div><dt>{copy.currentOrderStatus}</dt><dd>{selected.topupStatus}</dd></div><div><dt>{copy.createdUpdated}</dt><dd>{dateTime(selected.createdAt, locale)}<br />{dateTime(selected.updatedAt, locale)}</dd></div></dl>{selected.resolutionNote ? <p><small>{copy.resolution}</small><br />{selected.resolutionNote}</p> : null}</div><div className="admin-action-fields">{allowedAction[selected.status] === "RESOLVE" ? <label><span>{copy.resolution}</span><textarea maxLength={2000} onChange={(event) => setResolutionNote(event.target.value)} value={resolutionNote} /></label> : null}{allowedAction[selected.status] ? <button className="admin-button primary" disabled={busy || (allowedAction[selected.status] === "RESOLVE" && resolutionNote.trim().length < 10)} onClick={() => void transition()} type="button">{busy ? copy.processing : copy.actions[allowedAction[selected.status]!]}</button> : <p>{copy.closed}</p>}<p className="admin-inline-warning">{copy.warning}</p>{notice ? <div className="admin-inline-success" role="status"><strong>{copy.completed}</strong><span>{notice}</span></div> : null}</div></section> : null}
  </section>;
}
