-- Additive manual commercial order sidecar. Real payout remains CLOSED.
CREATE TABLE IF NOT EXISTS admin_manual_order_fee_tiers (policy_version TEXT NOT NULL,tier_code TEXT NOT NULL,minimum_lifetime_micros INTEGER NOT NULL CHECK(minimum_lifetime_micros>=0),platform_fee_bps INTEGER NOT NULL CHECK(platform_fee_bps BETWEEN 20 AND 100),created_at TEXT NOT NULL,PRIMARY KEY(policy_version,tier_code),UNIQUE(policy_version,minimum_lifetime_micros));
INSERT OR IGNORE INTO admin_manual_order_fee_tiers(policy_version,tier_code,minimum_lifetime_micros,platform_fee_bps,created_at) VALUES ('MANUAL-2026-01','STARTER',0,100,'2026-08-21T00:00:00.000Z'),('MANUAL-2026-01','GROWTH',10000000000,80,'2026-08-21T00:00:00.000Z'),('MANUAL-2026-01','SCALE',50000000000,60,'2026-08-21T00:00:00.000Z'),('MANUAL-2026-01','VOLUME',200000000000,40,'2026-08-21T00:00:00.000Z'),('MANUAL-2026-01','STRATEGIC',1000000000000,20,'2026-08-21T00:00:00.000Z');
CREATE TABLE IF NOT EXISTS admin_manual_commercial_orders (id TEXT PRIMARY KEY,demand_id TEXT NOT NULL UNIQUE,buyer_organization_id TEXT NOT NULL,buyer_account_id TEXT NOT NULL,supplier_organization_id TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('OFFERED','CARD_HOURS_HELD','PREPARING','READY','CONNECTION_CONFIRMED','AWAITING_ACCEPTANCE','COMPLETED','CANCELLED')),current_offer_version INTEGER NOT NULL DEFAULT 1 CHECK(current_offer_version>0),accepted_offer_version INTEGER,actual_card_hour_micros INTEGER,version INTEGER NOT NULL DEFAULT 1 CHECK(version>0),created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(demand_id) REFERENCES admin_catalog_purchase_intent_snapshots(demand_id));
CREATE INDEX IF NOT EXISTS admin_manual_orders_buyer_idx ON admin_manual_commercial_orders(buyer_organization_id,updated_at DESC);
CREATE INDEX IF NOT EXISTS admin_manual_orders_supplier_idx ON admin_manual_commercial_orders(supplier_organization_id,updated_at DESC);
CREATE TABLE IF NOT EXISTS admin_manual_order_offer_versions (order_id TEXT NOT NULL,offer_version INTEGER NOT NULL,quoted_card_hour_micros INTEGER NOT NULL CHECK(quoted_card_hour_micros>0),service_summary TEXT NOT NULL,expected_delivery_at TEXT,snapshot_json TEXT NOT NULL,fee_policy_version TEXT NOT NULL,fee_tier_code TEXT NOT NULL,platform_fee_bps INTEGER NOT NULL CHECK(platform_fee_bps BETWEEN 20 AND 100),created_by_principal_id TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(order_id,offer_version),FOREIGN KEY(order_id) REFERENCES admin_manual_commercial_orders(id));
CREATE TABLE IF NOT EXISTS admin_manual_order_holds (id TEXT PRIMARY KEY,order_id TEXT NOT NULL UNIQUE,buyer_organization_id TEXT NOT NULL,buyer_account_id TEXT NOT NULL,amount_micros INTEGER NOT NULL CHECK(amount_micros>0),captured_micros INTEGER,released_micros INTEGER,status TEXT NOT NULL CHECK(status IN ('HELD','CAPTURED','RELEASED')),created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(order_id) REFERENCES admin_manual_commercial_orders(id));
CREATE TABLE IF NOT EXISTS admin_manual_order_hold_events (id TEXT PRIMARY KEY,hold_id TEXT NOT NULL,event_type TEXT NOT NULL CHECK(event_type IN ('HELD','CAPTURED','RELEASED')),amount_micros INTEGER NOT NULL CHECK(amount_micros>=0),payload_digest TEXT NOT NULL,occurred_at TEXT NOT NULL,UNIQUE(hold_id,event_type),FOREIGN KEY(hold_id) REFERENCES admin_manual_order_holds(id));
CREATE TABLE IF NOT EXISTS admin_manual_order_settlement_eligibility (id TEXT PRIMARY KEY,order_id TEXT NOT NULL UNIQUE,supplier_organization_id TEXT NOT NULL,captured_card_hour_micros INTEGER NOT NULL CHECK(captured_card_hour_micros>0),gross_cny_cents INTEGER NOT NULL CHECK(gross_cny_cents>0),policy_version TEXT NOT NULL,tier_code TEXT NOT NULL,platform_fee_bps INTEGER NOT NULL CHECK(platform_fee_bps BETWEEN 20 AND 100),platform_fee_cny_cents INTEGER NOT NULL CHECK(platform_fee_cny_cents>0),supplier_receivable_cny_cents INTEGER NOT NULL CHECK(supplier_receivable_cny_cents>0),status TEXT NOT NULL CHECK(status='ELIGIBLE'),payout_status TEXT NOT NULL CHECK(payout_status='CLOSED'),created_at TEXT NOT NULL,FOREIGN KEY(order_id) REFERENCES admin_manual_commercial_orders(id));
