import type { Metadata } from "next";
import Link from "next/link";
import { Children, cloneElement, isValidElement, type ReactElement, type ReactNode } from "react";
import type { Locale } from "@/lib/i18n";
import { getRequestLocale } from "@/lib/server/request-locale";
import styles from "../guides.module.css";

const HOST_AGENT_VERSION = "1.9.7";
const AGENT_VERSION = HOST_AGENT_VERSION;
const ARCHIVE = `kai-host-agent-${AGENT_VERSION}.tgz`;

const metadataCopy: Record<Locale, { title: string; description: string }> = {
  "zh-CN": { title: "Host Agent 安装教程", description: "下载、校验、安装并配对 KAI Host Agent，让单张 RTX 4090 或 H100 完成真实验真。" },
  "zh-TW": { title: "Host Agent 安裝教學", description: "下載、校驗、安裝並配對 KAI Host Agent，讓單張 RTX 4090 或 H100 完成真實驗證。" },
  en: { title: "Host Agent installation guide", description: "Download, verify, install, and pair KAI Host Agent to verify one real RTX 4090 or H100." },
  ja: { title: "Host Agent インストールガイド", description: "KAI Host Agent をダウンロード、検証、インストール、ペアリングして RTX 4090 または H100 を実機検証します。" },
  ko: { title: "Host Agent 설치 가이드", description: "KAI Host Agent를 다운로드, 검증, 설치 및 페어링하여 RTX 4090 또는 H100 한 장을 실제 검증합니다." },
  fr: { title: "Guide d’installation de Host Agent", description: "Téléchargez, vérifiez, installez et associez KAI Host Agent pour valider une RTX 4090 ou H100 réelle." },
  th: { title: "คู่มือติดตั้ง Host Agent", description: "ดาวน์โหลด ตรวจสอบ ติดตั้ง และจับคู่ KAI Host Agent เพื่อยืนยัน RTX 4090 หรือ H100 จริงหนึ่งใบ" },
  vi: { title: "Hướng dẫn cài Host Agent", description: "Tải xuống, xác minh, cài đặt và ghép nối KAI Host Agent để xác thực một RTX 4090 hoặc H100 thực." },
  id: { title: "Panduan instalasi Host Agent", description: "Unduh, verifikasi, instal, dan pasangkan KAI Host Agent untuk memverifikasi satu RTX 4090 atau H100 nyata." },
  ms: { title: "Panduan pemasangan Host Agent", description: "Muat turun, sahkan, pasang dan gandingkan KAI Host Agent untuk mengesahkan satu RTX 4090 atau H100 sebenar." },
};

export async function generateMetadata(): Promise<Metadata> {
  return metadataCopy[await getRequestLocale()];
}

const EN: Record<string, string> = {
  "Host Agent 安装与配对": "Host Agent installation and pairing", "上架要求": "Listing requirements", "进入供应商控制台": "Open supplier console",
  "先校验安装包，再让一台真实 GPU 接入平台。": "Verify the package before connecting a real GPU to the platform.",
  "安装包由当前网站版本自动生成，不包含密钥、账号、配对码或服务器配置。不要使用第三方脚本，也不要把下载命令直接管道给 root shell。": "The package is generated by this site version and contains no keys, accounts, pairing codes, or server configuration. Do not use third-party scripts or pipe download commands directly into a root shell.",
  "安装包": "Package", "完整性": "Integrity", "下载 SHA-256 校验文件": "Download SHA-256 checksum", "校验失败时立即停止": "Stop immediately if verification fails",
  "下载": "Download",
  "准备一台首期支持的主机": "Prepare a supported host",
  "首期每个 Agent 只托管一张 RTX 4090 或 H100，禁止 MIG 和多租户切片。多卡服务器必须先用 `nvidia-smi` 明确选择一张物理卡；其余 GPU 不会被 Agent 使用。机器必须具备 NVIDIA 驱动、Docker Engine、NVIDIA Container Toolkit、稳定公网地址和最多 200 个预留端口。": "Initially, each Agent manages one RTX 4090 or H100. MIG and multi-tenant slicing are prohibited. On multi-GPU servers, select one physical card with `nvidia-smi`; other GPUs are not used. The host requires NVIDIA drivers, Docker Engine, NVIDIA Container Toolkit, a stable public address, and up to 200 reserved ports.",
  "不会在普通云服务器上假装 GPU": "No fake GPU on a generic cloud server",
  "安装器会检查 `nvidia-smi`、Docker Unix Socket、Node.js 和 systemd；缺失任意一项都会退出，不会登记虚假设备。": "The installer checks `nvidia-smi`, the Docker Unix Socket, Node.js, and systemd. It exits if any requirement is missing and never registers a fake device.",
  "校验并审阅安装包": "Verify and review the package",
  "只有 `sha256sum` 返回 OK、文件清单与页面版本一致时才继续。安装包内的 `release-manifest.json` 还记录每个源文件的摘要和网站提交版本。": "Continue only when `sha256sum` returns OK and the file list matches the page version. `release-manifest.json` records each source digest and the site revision.",
  "先做只读体检，再安装受限服务": "Run read-only preflight before installing the restricted service",
  "体检不安装服务、不改配置，也不会启动容器；它只检查 Ubuntu、系统级 Node.js、单卡 GPU、Docker NVIDIA Runtime、可用容量和整段本机端口。输出中的 `controlPlaneReachability: PENDING` 是正常的，公网入口必须等配对后由 Cloud 发起一次性挑战复验。安装完成时，只有本机 root Actuator 会启动；联网的 Host Agent 仍保持停止。": "Preflight installs nothing, changes no configuration, and starts no containers. It checks Ubuntu, system Node.js, one GPU, Docker NVIDIA Runtime, capacity, and the full local port range. `controlPlaneReachability: PENDING` is expected until Cloud runs a one-time challenge after pairing. Installation starts only the local root Actuator; the networked Host Agent remains stopped.",
  "用五分钟一次性凭证完成配对": "Pair with a five-minute one-time credential", "完成供应商审核": "Complete supplier review", "登录后进入供应商控制台，提交主体与设备权属资料，等待管理员批准。": "Open the supplier console after signing in, submit identity and device ownership evidence, and wait for approval.",
  "签发配对内容": "Issue pairing content", "在“资源 → 登记新资源”签发一次性 JSON。它只在五分钟内有效，成功注册后立即失效。": "Issue one-time JSON under Resources → Register resource. It is valid for five minutes and expires immediately after registration.",
  "通过私有文件配对": "Pair through a private file", "把 JSON 放进 Agent 专属目录并设为 `0600`。Agent 会拒绝相对路径、软链接、其他所有者或可被组/其他用户读取的文件。": "Place the JSON in the Agent directory with mode `0600`. The Agent rejects relative paths, symlinks, wrong ownership, or group/world-readable files.",
  "只有最后一条命令返回 `connection.verified` 才表示 Cloud 已接受设备的第一条签名连接检查。此命令以 OFFLINE 状态报告，不会领取验真或租赁任务；网页会自动显示“连接已验证，等待启动服务”。": "Only `connection.verified` from the final command means Cloud accepted the device’s first signed connection check. It reports OFFLINE and claims no verification or rental work; the page then shows that connection is verified and service startup is pending.",
  "配置平台批准的不可变镜像": "Configure a platform-approved immutable image",
  "从供应商控制台复制完整的 `ghcr.io/...@sha256:...` 镜像摘要，先按摘要拉取，再把 `KAI_HOSTING_APPROVED_IMAGES` 和配对时同一张卡的 `KAI_HOST_GPU_UUID` 写入 `/etc/kai-host-actuator.env`。`latest`、普通 tag 和任意第三方仓库都会被拒绝；未被 root 配置批准的 GPU 同样无法分配。": "Copy the full `ghcr.io/...@sha256:...` digest from the supplier console and pull by digest. Write `KAI_HOSTING_APPROVED_IMAGES` and the paired card’s `KAI_HOST_GPU_UUID` to `/etc/kai-host-actuator.env`. `latest`, ordinary tags, third-party registries, and unapproved GPUs are rejected.",
  "回到控制台完成验真": "Return to the console to complete verification",
  "先配置批准镜像并启动常驻服务。网页看到在线心跳后再创建验真任务；平台会核对 GPU 身份、CUDA、显存、存储、不可变工作负载镜像、网络和端口可达性。证据过期、镜像策略变化、规格变化、Agent 离线或清理失败会自动暂停报价；清理失败的设备保持 DRAINING，不能再次出租。": "Configure the approved image and start the service. Create a verification task only after the page shows an online heartbeat. The platform checks GPU identity, CUDA, memory, storage, immutable image, network, and ports. Expired evidence, policy or specification changes, an offline Agent, or cleanup failure pauses offers; a failed cleanup stays DRAINING and cannot be rented again.",
  "查看设备与验真状态 →": "View device and verification status →",
};

const CORE: Record<Exclude<Locale, "zh-CN" | "en">, Record<string, string>> = {
  "zh-TW": { "Host Agent 安装与配对": "Host Agent 安裝與配對", "上架要求": "上架要求", "进入供应商控制台": "進入供應商控制台", "先校验安装包，再让一台真实 GPU 接入平台。": "先校驗安裝包，再讓一台真實 GPU 接入平台。", "安装包": "安裝包", "完整性": "完整性", "下载": "下載", "下载 SHA-256 校验文件": "下載 SHA-256 校驗檔", "校验失败时立即停止": "校驗失敗時立即停止", "准备一台首期支持的主机": "準備一台首期支援的主機", "不会在普通云服务器上假装 GPU": "不會在一般雲端伺服器上假裝 GPU", "校验并审阅安装包": "校驗並審閱安裝包", "先做只读体检，再安装受限服务": "先做唯讀檢查，再安裝受限服務", "用五分钟一次性凭证完成配对": "用五分鐘一次性憑證完成配對", "完成供应商审核": "完成供應商審核", "签发配对内容": "簽發配對內容", "通过私有文件配对": "透過私有檔案配對", "配置平台批准的不可变镜像": "設定平台批准的不可變映像", "回到控制台完成验真": "回到控制台完成驗證", "查看设备与验真状态 →": "查看裝置與驗證狀態 →" },
  ja: { "Host Agent 安装与配对": "Host Agent のインストールとペアリング", "上架要求": "掲載要件", "进入供应商控制台": "サプライヤーコンソール", "先校验安装包，再让一台真实 GPU 接入平台。": "パッケージを検証してから実機 GPU を接続します。", "安装包": "パッケージ", "完整性": "完全性", "下载": "ダウンロード", "下载 SHA-256 校验文件": "SHA-256 チェックサムをダウンロード", "校验失败时立即停止": "検証失敗時は直ちに停止", "准备一台首期支持的主机": "対応ホストを準備", "不会在普通云服务器上假装 GPU": "一般的なクラウド上で GPU を偽装しません", "校验并审阅安装包": "パッケージを検証・確認", "先做只读体检，再安装受限服务": "読み取り専用検査後に制限サービスを導入", "用五分钟一次性凭证完成配对": "5分間有効の資格情報でペアリング", "完成供应商审核": "サプライヤー審査を完了", "签发配对内容": "ペアリング情報を発行", "通过私有文件配对": "非公開ファイルでペアリング", "配置平台批准的不可变镜像": "承認済み不変イメージを設定", "回到控制台完成验真": "コンソールで検証を完了", "查看设备与验真状态 →": "デバイスと検証状態を見る →" },
  ko: { "Host Agent 安装与配对": "Host Agent 설치 및 페어링", "上架要求": "등록 요건", "进入供应商控制台": "공급자 콘솔", "先校验安装包，再让一台真实 GPU 接入平台。": "패키지를 검증한 뒤 실제 GPU를 플랫폼에 연결합니다.", "安装包": "설치 패키지", "完整性": "무결성", "下载": "다운로드", "下载 SHA-256 校验文件": "SHA-256 체크섬 다운로드", "校验失败时立即停止": "검증 실패 시 즉시 중지", "准备一台首期支持的主机": "지원 호스트 준비", "不会在普通云服务器上假装 GPU": "일반 클라우드에서 GPU를 가장하지 않습니다", "校验并审阅安装包": "패키지 검증 및 검토", "先做只读体检，再安装受限服务": "읽기 전용 점검 후 제한 서비스 설치", "用五分钟一次性凭证完成配对": "5분 일회용 자격 증명으로 페어링", "完成供应商审核": "공급자 심사 완료", "签发配对内容": "페어링 내용 발급", "通过私有文件配对": "비공개 파일로 페어링", "配置平台批准的不可变镜像": "승인된 불변 이미지 구성", "回到控制台完成验真": "콘솔에서 검증 완료", "查看设备与验真状态 →": "장치 및 검증 상태 보기 →" },
  fr: { "Host Agent 安装与配对": "Installation et association de Host Agent", "上架要求": "Conditions de publication", "进入供应商控制台": "Console fournisseur", "先校验安装包，再让一台真实 GPU 接入平台。": "Vérifiez le paquet avant de connecter un GPU réel.", "安装包": "Paquet", "完整性": "Intégrité", "下载": "Télécharger", "下载 SHA-256 校验文件": "Télécharger la somme SHA-256", "校验失败时立即停止": "Arrêter immédiatement si la vérification échoue", "准备一台首期支持的主机": "Préparer un hôte compatible", "不会在普通云服务器上假装 GPU": "Aucun faux GPU sur un serveur cloud ordinaire", "校验并审阅安装包": "Vérifier et examiner le paquet", "先做只读体检，再安装受限服务": "Effectuer le contrôle en lecture seule avant l’installation", "用五分钟一次性凭证完成配对": "Associer avec un identifiant unique de cinq minutes", "完成供应商审核": "Terminer la vérification fournisseur", "签发配对内容": "Émettre le contenu d’association", "通过私有文件配对": "Associer via un fichier privé", "配置平台批准的不可变镜像": "Configurer une image immuable approuvée", "回到控制台完成验真": "Terminer la vérification dans la console", "查看设备与验真状态 →": "Voir l’appareil et sa vérification →" },
  th: { "Host Agent 安装与配对": "ติดตั้งและจับคู่ Host Agent", "上架要求": "ข้อกำหนดการลงรายการ", "进入供应商控制台": "คอนโซลผู้ให้บริการ", "先校验安装包，再让一台真实 GPU 接入平台。": "ตรวจสอบแพ็กเกจก่อนเชื่อมต่อ GPU จริง", "安装包": "แพ็กเกจ", "完整性": "ความถูกต้อง", "下载": "ดาวน์โหลด", "下载 SHA-256 校验文件": "ดาวน์โหลดไฟล์ตรวจสอบ SHA-256", "校验失败时立即停止": "หยุดทันทีหากตรวจสอบไม่ผ่าน", "准备一台首期支持的主机": "เตรียมโฮสต์ที่รองรับ", "不会在普通云服务器上假装 GPU": "ไม่จำลอง GPU บนเซิร์ฟเวอร์คลาวด์ทั่วไป", "校验并审阅安装包": "ตรวจสอบและทบทวนแพ็กเกจ", "先做只读体检，再安装受限服务": "ตรวจแบบอ่านอย่างเดียวก่อนติดตั้งบริการ", "用五分钟一次性凭证完成配对": "จับคู่ด้วยข้อมูลใช้ครั้งเดียวห้านาที", "完成供应商审核": "ผ่านการตรวจผู้ให้บริการ", "签发配对内容": "ออกข้อมูลจับคู่", "通过私有文件配对": "จับคู่ผ่านไฟล์ส่วนตัว", "配置平台批准的不可变镜像": "ตั้งค่าอิมเมจคงที่ที่อนุมัติ", "回到控制台完成验真": "กลับไปยืนยันในคอนโซล", "查看设备与验真状态 →": "ดูอุปกรณ์และสถานะการยืนยัน →" },
  vi: { "Host Agent 安装与配对": "Cài đặt và ghép nối Host Agent", "上架要求": "Yêu cầu đăng", "进入供应商控制台": "Bảng điều khiển nhà cung cấp", "先校验安装包，再让一台真实 GPU 接入平台。": "Xác minh gói trước khi kết nối GPU thực.", "安装包": "Gói cài đặt", "完整性": "Tính toàn vẹn", "下载": "Tải xuống", "下载 SHA-256 校验文件": "Tải tệp kiểm tra SHA-256", "校验失败时立即停止": "Dừng ngay nếu xác minh thất bại", "准备一台首期支持的主机": "Chuẩn bị máy chủ được hỗ trợ", "不会在普通云服务器上假装 GPU": "Không giả lập GPU trên máy chủ đám mây thông thường", "校验并审阅安装包": "Xác minh và xem xét gói", "先做只读体检，再安装受限服务": "Kiểm tra chỉ đọc trước khi cài dịch vụ", "用五分钟一次性凭证完成配对": "Ghép nối bằng thông tin dùng một lần trong năm phút", "完成供应商审核": "Hoàn tất xét duyệt nhà cung cấp", "签发配对内容": "Cấp nội dung ghép nối", "通过私有文件配对": "Ghép nối qua tệp riêng tư", "配置平台批准的不可变镜像": "Cấu hình image bất biến đã duyệt", "回到控制台完成验真": "Hoàn tất xác minh trong bảng điều khiển", "查看设备与验真状态 →": "Xem thiết bị và trạng thái xác minh →" },
  id: { "Host Agent 安装与配对": "Instalasi dan pemasangan Host Agent", "上架要求": "Persyaratan listing", "进入供应商控制台": "Konsol pemasok", "先校验安装包，再让一台真实 GPU 接入平台。": "Verifikasi paket sebelum menghubungkan GPU nyata.", "安装包": "Paket", "完整性": "Integritas", "下载": "Unduh", "下载 SHA-256 校验文件": "Unduh checksum SHA-256", "校验失败时立即停止": "Hentikan segera jika verifikasi gagal", "准备一台首期支持的主机": "Siapkan host yang didukung", "不会在普通云服务器上假装 GPU": "Tidak memalsukan GPU pada server cloud biasa", "校验并审阅安装包": "Verifikasi dan tinjau paket", "先做只读体检，再安装受限服务": "Jalankan pemeriksaan baca-saja sebelum instalasi", "用五分钟一次性凭证完成配对": "Pasangkan dengan kredensial sekali pakai lima menit", "完成供应商审核": "Selesaikan tinjauan pemasok", "签发配对内容": "Terbitkan konten pemasangan", "通过私有文件配对": "Pasangkan melalui file privat", "配置平台批准的不可变镜像": "Konfigurasikan image tetap yang disetujui", "回到控制台完成验真": "Selesaikan verifikasi di konsol", "查看设备与验真状态 →": "Lihat perangkat dan status verifikasi →" },
  ms: { "Host Agent 安装与配对": "Pemasangan dan penggandingan Host Agent", "上架要求": "Syarat penyenaraian", "进入供应商控制台": "Konsol pembekal", "先校验安装包，再让一台真实 GPU 接入平台。": "Sahkan pakej sebelum menyambungkan GPU sebenar.", "安装包": "Pakej", "完整性": "Integriti", "下载": "Muat turun", "下载 SHA-256 校验文件": "Muat turun semakan SHA-256", "校验失败时立即停止": "Hentikan segera jika pengesahan gagal", "准备一台首期支持的主机": "Sediakan hos yang disokong", "不会在普通云服务器上假装 GPU": "Tidak memalsukan GPU pada pelayan awan biasa", "校验并审阅安装包": "Sahkan dan semak pakej", "先做只读体检，再安装受限服务": "Jalankan pemeriksaan baca sahaja sebelum pemasangan", "用五分钟一次性凭证完成配对": "Gandingkan dengan kelayakan sekali guna lima minit", "完成供应商审核": "Lengkapkan semakan pembekal", "签发配对内容": "Keluarkan kandungan gandingan", "通过私有文件配对": "Gandingkan melalui fail peribadi", "配置平台批准的不可变镜像": "Konfigurasi imej kekal yang diluluskan", "回到控制台完成验真": "Lengkapkan pengesahan di konsol", "查看设备与验真状态 →": "Lihat peranti dan status pengesahan →" },
};

const BODY: Record<Exclude<Locale, "zh-CN" | "en">, Record<string, string>> = {
  "zh-TW": {
    "安装包由当前网站版本自动生成，不包含密钥、账号、配对码或服务器配置。不要使用第三方脚本，也不要把下载命令直接管道给 root shell。": "安裝包由目前網站版本自動產生，不包含金鑰、帳號、配對碼或伺服器設定。請勿使用第三方指令碼，也不要將下載命令直接導向 root shell。",
    "首期每个 Agent 只托管一张 RTX 4090 或 H100，禁止 MIG 和多租户切片。多卡服务器必须先用 `nvidia-smi` 明确选择一张物理卡；其余 GPU 不会被 Agent 使用。机器必须具备 NVIDIA 驱动、Docker Engine、NVIDIA Container Toolkit、稳定公网地址和最多 200 个预留端口。": "首期每個 Agent 僅託管一張 RTX 4090 或 H100，禁止 MIG 與多租戶切片。多卡伺服器必須先用 `nvidia-smi` 明確選擇一張實體卡；其餘 GPU 不會由 Agent 使用。主機必須具備 NVIDIA 驅動程式、Docker Engine、NVIDIA Container Toolkit、穩定公網位址，以及最多 200 個預留連接埠。",
    "安装器会检查 `nvidia-smi`、Docker Unix Socket、Node.js 和 systemd；缺失任意一项都会退出，不会登记虚假设备。": "安裝程式會檢查 `nvidia-smi`、Docker Unix Socket、Node.js 與 systemd；缺少任何一項都會退出，不會登記虛假裝置。",
    "只有 `sha256sum` 返回 OK、文件清单与页面版本一致时才继续。安装包内的 `release-manifest.json` 还记录每个源文件的摘要和网站提交版本。": "只有在 `sha256sum` 回傳 OK，且檔案清單與頁面版本一致時才繼續。安裝包內的 `release-manifest.json` 也會記錄每個原始檔的摘要與網站提交版本。",
    "体检不安装服务、不改配置，也不会启动容器；它只检查 Ubuntu、系统级 Node.js、单卡 GPU、Docker NVIDIA Runtime、可用容量和整段本机端口。输出中的 `controlPlaneReachability: PENDING` 是正常的，公网入口必须等配对后由 Cloud 发起一次性挑战复验。安装完成时，只有本机 root Actuator 会启动；联网的 Host Agent 仍保持停止。": "檢查不會安裝服務、變更設定或啟動容器；只會檢查 Ubuntu、系統層級 Node.js、單卡 GPU、Docker NVIDIA Runtime、可用容量與完整的本機連接埠區段。輸出中的 `controlPlaneReachability: PENDING` 是正常狀態，公網入口須在配對後由 Cloud 發起一次性挑戰複驗。安裝完成時僅啟動本機 root Actuator；聯網的 Host Agent 仍維持停止。",
    "登录后进入供应商控制台，提交主体与设备权属资料，等待管理员批准。": "登入後進入供應商控制台，提交主體與裝置權屬資料，等待管理員核准。",
    "在“资源 → 登记新资源”签发一次性 JSON。它只在五分钟内有效，成功注册后立即失效。": "在「資源 → 登記新資源」簽發一次性 JSON。它僅在五分鐘內有效，成功註冊後立即失效。",
    "把 JSON 放进 Agent 专属目录并设为 `0600`。Agent 会拒绝相对路径、软链接、其他所有者或可被组/其他用户读取的文件。": "將 JSON 放入 Agent 專屬目錄並設為 `0600`。Agent 會拒絕相對路徑、符號連結、其他擁有者，或群組／其他使用者可讀取的檔案。",
    "只有最后一条命令返回 `connection.verified` 才表示 Cloud 已接受设备的第一条签名连接检查。此命令以 OFFLINE 状态报告，不会领取验真或租赁任务；网页会自动显示“连接已验证，等待启动服务”。": "只有最後一條命令回傳 `connection.verified`，才表示 Cloud 已接受裝置的第一筆簽章連線檢查。此命令會以 OFFLINE 狀態回報，不會領取驗證或租賃任務；網頁會自動顯示「連線已驗證，等待啟動服務」。",
    "从供应商控制台复制完整的 `ghcr.io/...@sha256:...` 镜像摘要，先按摘要拉取，再把 `KAI_HOSTING_APPROVED_IMAGES` 和配对时同一张卡的 `KAI_HOST_GPU_UUID` 写入 `/etc/kai-host-actuator.env`。`latest`、普通 tag 和任意第三方仓库都会被拒绝；未被 root 配置批准的 GPU 同样无法分配。": "從供應商控制台複製完整的 `ghcr.io/...@sha256:...` 映像摘要，先依摘要拉取，再將 `KAI_HOSTING_APPROVED_IMAGES` 與配對時同一張卡的 `KAI_HOST_GPU_UUID` 寫入 `/etc/kai-host-actuator.env`。`latest`、一般 tag 與任何第三方倉庫都會被拒絕；未經 root 設定核准的 GPU 也無法分配。",
    "先配置批准镜像并启动常驻服务。网页看到在线心跳后再创建验真任务；平台会核对 GPU 身份、CUDA、显存、存储、不可变工作负载镜像、网络和端口可达性。证据过期、镜像策略变化、规格变化、Agent 离线或清理失败会自动暂停报价；清理失败的设备保持 DRAINING，不能再次出租。": "先設定核准映像並啟動常駐服務。網頁顯示線上心跳後再建立驗證任務；平台會核對 GPU 身分、CUDA、顯存、儲存、不可變工作負載映像、網路與連接埠可達性。證據過期、映像政策或規格變更、Agent 離線或清理失敗都會自動暫停報價；清理失敗的裝置會保持 DRAINING，無法再次出租。",
  },
  ja: {
    "安装包由当前网站版本自动生成，不包含密钥、账号、配对码或服务器配置。不要使用第三方脚本，也不要把下载命令直接管道给 root shell。": "インストールパッケージは現在のサイト版から自動生成され、鍵、アカウント、ペアリングコード、サーバー設定は含みません。第三者スクリプトを使わず、ダウンロードコマンドを root shell に直接パイプしないでください。",
    "首期每个 Agent 只托管一张 RTX 4090 或 H100，禁止 MIG 和多租户切片。多卡服务器必须先用 `nvidia-smi` 明确选择一张物理卡；其余 GPU 不会被 Agent 使用。机器必须具备 NVIDIA 驱动、Docker Engine、NVIDIA Container Toolkit、稳定公网地址和最多 200 个预留端口。": "初期は各 Agent が管理するのは RTX 4090 または H100 1枚のみで、MIG とマルチテナント分割は禁止です。複数 GPU サーバーでは `nvidia-smi` で物理 GPU を1枚明示的に選択し、他の GPU は Agent が使用しません。NVIDIA ドライバー、Docker Engine、NVIDIA Container Toolkit、安定した公開アドレス、最大200個の予約ポートが必要です。",
    "安装器会检查 `nvidia-smi`、Docker Unix Socket、Node.js 和 systemd；缺失任意一项都会退出，不会登记虚假设备。": "インストーラーは `nvidia-smi`、Docker Unix Socket、Node.js、systemd を確認します。いずれかが欠けると終了し、架空のデバイスは登録しません。",
    "只有 `sha256sum` 返回 OK、文件清单与页面版本一致时才继续。安装包内的 `release-manifest.json` 还记录每个源文件的摘要和网站提交版本。": "`sha256sum` が OK を返し、ファイル一覧がページのバージョンと一致する場合にのみ続行します。パッケージ内の `release-manifest.json` には各ソースファイルのダイジェストとサイトのコミット版も記録されています。",
    "体检不安装服务、不改配置，也不会启动容器；它只检查 Ubuntu、系统级 Node.js、单卡 GPU、Docker NVIDIA Runtime、可用容量和整段本机端口。输出中的 `controlPlaneReachability: PENDING` 是正常的，公网入口必须等配对后由 Cloud 发起一次性挑战复验。安装完成时，只有本机 root Actuator 会启动；联网的 Host Agent 仍保持停止。": "事前検査はサービスをインストールせず、設定を変更せず、コンテナも起動しません。Ubuntu、システム Node.js、単一 GPU、Docker NVIDIA Runtime、空き容量、ローカルポート範囲全体だけを確認します。出力の `controlPlaneReachability: PENDING` は正常で、公開入口はペアリング後に Cloud の一度限りのチャレンジで再検証します。インストール後に起動するのはローカル root Actuator のみで、ネットワーク Host Agent は停止したままです。",
    "登录后进入供应商控制台，提交主体与设备权属资料，等待管理员批准。": "ログイン後にサプライヤーコンソールを開き、本人・法人情報とデバイス所有権資料を提出して管理者の承認を待ちます。",
    "在“资源 → 登记新资源”签发一次性 JSON。它只在五分钟内有效，成功注册后立即失效。": "「リソース → 新規リソース登録」で一度限りの JSON を発行します。有効期間は5分で、登録成功後すぐに失効します。",
    "把 JSON 放进 Agent 专属目录并设为 `0600`。Agent 会拒绝相对路径、软链接、其他所有者或可被组/其他用户读取的文件。": "JSON を Agent 専用ディレクトリに置き、権限を `0600` にします。Agent は相対パス、シンボリックリンク、別所有者、グループまたは他ユーザーが読めるファイルを拒否します。",
    "只有最后一条命令返回 `connection.verified` 才表示 Cloud 已接受设备的第一条签名连接检查。此命令以 OFFLINE 状态报告，不会领取验真或租赁任务；网页会自动显示“连接已验证，等待启动服务”。": "最後のコマンドが `connection.verified` を返した場合のみ、Cloud がデバイスの最初の署名付き接続確認を受理したことを示します。このコマンドは OFFLINE として報告し、検証やレンタルのタスクは取得しません。ページには接続確認済みでサービス開始待ちと自動表示されます。",
    "从供应商控制台复制完整的 `ghcr.io/...@sha256:...` 镜像摘要，先按摘要拉取，再把 `KAI_HOSTING_APPROVED_IMAGES` 和配对时同一张卡的 `KAI_HOST_GPU_UUID` 写入 `/etc/kai-host-actuator.env`。`latest`、普通 tag 和任意第三方仓库都会被拒绝；未被 root 配置批准的 GPU 同样无法分配。": "サプライヤーコンソールから完全な `ghcr.io/...@sha256:...` イメージダイジェストをコピーし、ダイジェスト指定で pull します。次に `KAI_HOSTING_APPROVED_IMAGES` と、ペアリングした同じカードの `KAI_HOST_GPU_UUID` を `/etc/kai-host-actuator.env` に書き込みます。`latest`、通常の tag、第三者レジストリ、root 設定で未承認の GPU は拒否されます。",
    "先配置批准镜像并启动常驻服务。网页看到在线心跳后再创建验真任务；平台会核对 GPU 身份、CUDA、显存、存储、不可变工作负载镜像、网络和端口可达性。证据过期、镜像策略变化、规格变化、Agent 离线或清理失败会自动暂停报价；清理失败的设备保持 DRAINING，不能再次出租。": "承認済みイメージを設定して常駐サービスを起動します。ページでオンラインのハートビートを確認してから検証タスクを作成してください。プラットフォームは GPU ID、CUDA、メモリ、ストレージ、不変ワークロードイメージ、ネットワーク、ポート到達性を確認します。証拠の期限切れ、イメージポリシーや仕様の変更、Agent のオフライン、クリーンアップ失敗時はオファーが自動停止し、失敗したデバイスは DRAINING のまま再レンタルできません。",
  },
  ko: {
    "安装包由当前网站版本自动生成，不包含密钥、账号、配对码或服务器配置。不要使用第三方脚本，也不要把下载命令直接管道给 root shell。": "설치 패키지는 현재 사이트 버전에서 자동 생성되며 키, 계정, 페어링 코드 또는 서버 설정을 포함하지 않습니다. 타사 스크립트를 사용하거나 다운로드 명령을 root shell에 직접 파이프하지 마세요.",
    "首期每个 Agent 只托管一张 RTX 4090 或 H100，禁止 MIG 和多租户切片。多卡服务器必须先用 `nvidia-smi` 明确选择一张物理卡；其余 GPU 不会被 Agent 使用。机器必须具备 NVIDIA 驱动、Docker Engine、NVIDIA Container Toolkit、稳定公网地址和最多 200 个预留端口。": "초기에는 Agent 하나당 RTX 4090 또는 H100 한 장만 관리하며 MIG와 멀티테넌트 분할은 금지됩니다. 다중 GPU 서버에서는 `nvidia-smi`로 물리 카드 한 장을 명시적으로 선택해야 하며 나머지 GPU는 Agent가 사용하지 않습니다. NVIDIA 드라이버, Docker Engine, NVIDIA Container Toolkit, 안정적인 공인 주소와 최대 200개의 예약 포트가 필요합니다.",
    "安装器会检查 `nvidia-smi`、Docker Unix Socket、Node.js 和 systemd；缺失任意一项都会退出，不会登记虚假设备。": "설치 프로그램은 `nvidia-smi`, Docker Unix Socket, Node.js, systemd를 확인합니다. 하나라도 없으면 종료하며 허위 장치를 등록하지 않습니다.",
    "只有 `sha256sum` 返回 OK、文件清单与页面版本一致时才继续。安装包内的 `release-manifest.json` 还记录每个源文件的摘要和网站提交版本。": "`sha256sum`이 OK를 반환하고 파일 목록이 페이지 버전과 일치할 때만 계속합니다. 패키지의 `release-manifest.json`에는 각 소스 파일의 다이제스트와 사이트 커밋 버전도 기록됩니다.",
    "体检不安装服务、不改配置，也不会启动容器；它只检查 Ubuntu、系统级 Node.js、单卡 GPU、Docker NVIDIA Runtime、可用容量和整段本机端口。输出中的 `controlPlaneReachability: PENDING` 是正常的，公网入口必须等配对后由 Cloud 发起一次性挑战复验。安装完成时，只有本机 root Actuator 会启动；联网的 Host Agent 仍保持停止。": "사전 점검은 서비스를 설치하거나 설정을 바꾸거나 컨테이너를 시작하지 않습니다. Ubuntu, 시스템 Node.js, 단일 GPU, Docker NVIDIA Runtime, 사용 가능 용량 및 전체 로컬 포트 범위만 확인합니다. 출력의 `controlPlaneReachability: PENDING`은 정상이며 공개 진입점은 페어링 후 Cloud의 일회성 챌린지로 재검증합니다. 설치 후에는 로컬 root Actuator만 시작되고 네트워크 Host Agent는 중지 상태를 유지합니다.",
    "登录后进入供应商控制台，提交主体与设备权属资料，等待管理员批准。": "로그인 후 공급자 콘솔에서 주체 정보와 장치 소유권 자료를 제출하고 관리자 승인을 기다립니다.",
    "在“资源 → 登记新资源”签发一次性 JSON。它只在五分钟内有效，成功注册后立即失效。": "‘리소스 → 새 리소스 등록’에서 일회용 JSON을 발급합니다. 5분 동안만 유효하며 등록에 성공하면 즉시 만료됩니다.",
    "把 JSON 放进 Agent 专属目录并设为 `0600`。Agent 会拒绝相对路径、软链接、其他所有者或可被组/其他用户读取的文件。": "JSON을 Agent 전용 디렉터리에 넣고 `0600`으로 설정합니다. Agent는 상대 경로, 심볼릭 링크, 다른 소유자 또는 그룹·다른 사용자가 읽을 수 있는 파일을 거부합니다.",
    "只有最后一条命令返回 `connection.verified` 才表示 Cloud 已接受设备的第一条签名连接检查。此命令以 OFFLINE 状态报告，不会领取验真或租赁任务；网页会自动显示“连接已验证，等待启动服务”。": "마지막 명령이 `connection.verified`를 반환해야만 Cloud가 장치의 첫 서명 연결 확인을 수락한 것입니다. 이 명령은 OFFLINE 상태로 보고하며 검증이나 임대 작업을 가져오지 않습니다. 페이지에는 연결 확인 완료 및 서비스 시작 대기가 자동으로 표시됩니다.",
    "从供应商控制台复制完整的 `ghcr.io/...@sha256:...` 镜像摘要，先按摘要拉取，再把 `KAI_HOSTING_APPROVED_IMAGES` 和配对时同一张卡的 `KAI_HOST_GPU_UUID` 写入 `/etc/kai-host-actuator.env`。`latest`、普通 tag 和任意第三方仓库都会被拒绝；未被 root 配置批准的 GPU 同样无法分配。": "공급자 콘솔에서 전체 `ghcr.io/...@sha256:...` 이미지 다이제스트를 복사해 다이제스트로 pull한 뒤 `KAI_HOSTING_APPROVED_IMAGES`와 페어링한 동일 카드의 `KAI_HOST_GPU_UUID`를 `/etc/kai-host-actuator.env`에 기록합니다. `latest`, 일반 tag, 타사 레지스트리 및 root 설정에서 승인되지 않은 GPU는 거부됩니다.",
    "先配置批准镜像并启动常驻服务。网页看到在线心跳后再创建验真任务；平台会核对 GPU 身份、CUDA、显存、存储、不可变工作负载镜像、网络和端口可达性。证据过期、镜像策略变化、规格变化、Agent 离线或清理失败会自动暂停报价；清理失败的设备保持 DRAINING，不能再次出租。": "승인된 이미지를 구성하고 상주 서비스를 시작합니다. 페이지에서 온라인 하트비트를 확인한 뒤 검증 작업을 생성하세요. 플랫폼은 GPU ID, CUDA, 메모리, 스토리지, 불변 워크로드 이미지, 네트워크 및 포트 도달성을 확인합니다. 증거 만료, 이미지 정책·사양 변경, Agent 오프라인 또는 정리 실패 시 오퍼가 자동 중지되며 정리에 실패한 장치는 DRAINING 상태로 남아 다시 임대할 수 없습니다.",
  },
  fr: {
    "安装包由当前网站版本自动生成，不包含密钥、账号、配对码或服务器配置。不要使用第三方脚本，也不要把下载命令直接管道给 root shell。": "Le paquet est généré automatiquement à partir de la version actuelle du site et ne contient ni clé, ni compte, ni code d’association, ni configuration serveur. N’utilisez pas de script tiers et ne redirigez pas une commande de téléchargement directement vers un shell root.",
    "首期每个 Agent 只托管一张 RTX 4090 或 H100，禁止 MIG 和多租户切片。多卡服务器必须先用 `nvidia-smi` 明确选择一张物理卡；其余 GPU 不会被 Agent 使用。机器必须具备 NVIDIA 驱动、Docker Engine、NVIDIA Container Toolkit、稳定公网地址和最多 200 个预留端口。": "Au lancement, chaque Agent ne gère qu’une RTX 4090 ou H100 ; MIG et le découpage multi-locataire sont interdits. Sur un serveur multi-GPU, sélectionnez explicitement une carte physique avec `nvidia-smi` ; les autres GPU ne seront pas utilisés. L’hôte doit disposer des pilotes NVIDIA, de Docker Engine, de NVIDIA Container Toolkit, d’une adresse publique stable et de 200 ports réservés au maximum.",
    "安装器会检查 `nvidia-smi`、Docker Unix Socket、Node.js 和 systemd；缺失任意一项都会退出，不会登记虚假设备。": "Le programme d’installation contrôle `nvidia-smi`, le socket Unix de Docker, Node.js et systemd. Il s’arrête si un élément manque et n’enregistre jamais de faux appareil.",
    "只有 `sha256sum` 返回 OK、文件清单与页面版本一致时才继续。安装包内的 `release-manifest.json` 还记录每个源文件的摘要和网站提交版本。": "Ne continuez que si `sha256sum` renvoie OK et si la liste des fichiers correspond à la version de la page. Le fichier `release-manifest.json` consigne aussi l’empreinte de chaque source et la révision du site.",
    "体检不安装服务、不改配置，也不会启动容器；它只检查 Ubuntu、系统级 Node.js、单卡 GPU、Docker NVIDIA Runtime、可用容量和整段本机端口。输出中的 `controlPlaneReachability: PENDING` 是正常的，公网入口必须等配对后由 Cloud 发起一次性挑战复验。安装完成时，只有本机 root Actuator 会启动；联网的 Host Agent 仍保持停止。": "Le précontrôle n’installe aucun service, ne modifie aucune configuration et ne démarre aucun conteneur. Il vérifie uniquement Ubuntu, Node.js système, un seul GPU, Docker NVIDIA Runtime, la capacité disponible et toute la plage de ports locale. `controlPlaneReachability: PENDING` est normal : l’accès public sera revérifié par un défi unique de Cloud après l’association. À la fin de l’installation, seul l’Actuator root local démarre ; le Host Agent réseau reste arrêté.",
    "登录后进入供应商控制台，提交主体与设备权属资料，等待管理员批准。": "Après connexion, ouvrez la console fournisseur, transmettez les informations d’identité et de propriété de l’appareil, puis attendez l’approbation d’un administrateur.",
    "在“资源 → 登记新资源”签发一次性 JSON。它只在五分钟内有效，成功注册后立即失效。": "Dans « Ressources → Enregistrer une ressource », émettez un JSON à usage unique. Il reste valable cinq minutes et expire dès l’enregistrement réussi.",
    "把 JSON 放进 Agent 专属目录并设为 `0600`。Agent 会拒绝相对路径、软链接、其他所有者或可被组/其他用户读取的文件。": "Placez le JSON dans le répertoire privé de l’Agent avec le mode `0600`. L’Agent refuse les chemins relatifs, liens symboliques, propriétaires différents et fichiers lisibles par le groupe ou d’autres utilisateurs.",
    "只有最后一条命令返回 `connection.verified` 才表示 Cloud 已接受设备的第一条签名连接检查。此命令以 OFFLINE 状态报告，不会领取验真或租赁任务；网页会自动显示“连接已验证，等待启动服务”。": "Seul le retour `connection.verified` de la dernière commande confirme que Cloud a accepté le premier contrôle de connexion signé de l’appareil. La commande signale l’état OFFLINE et ne récupère aucune tâche de vérification ou de location ; la page indique automatiquement que la connexion est vérifiée et attend le démarrage du service.",
    "从供应商控制台复制完整的 `ghcr.io/...@sha256:...` 镜像摘要，先按摘要拉取，再把 `KAI_HOSTING_APPROVED_IMAGES` 和配对时同一张卡的 `KAI_HOST_GPU_UUID` 写入 `/etc/kai-host-actuator.env`。`latest`、普通 tag 和任意第三方仓库都会被拒绝；未被 root 配置批准的 GPU 同样无法分配。": "Copiez l’empreinte complète `ghcr.io/...@sha256:...` depuis la console fournisseur et récupérez l’image par empreinte. Écrivez ensuite `KAI_HOSTING_APPROVED_IMAGES` et le `KAI_HOST_GPU_UUID` de la même carte associée dans `/etc/kai-host-actuator.env`. `latest`, les tags ordinaires, les registres tiers et les GPU non approuvés par la configuration root sont refusés.",
    "先配置批准镜像并启动常驻服务。网页看到在线心跳后再创建验真任务；平台会核对 GPU 身份、CUDA、显存、存储、不可变工作负载镜像、网络和端口可达性。证据过期、镜像策略变化、规格变化、Agent 离线或清理失败会自动暂停报价；清理失败的设备保持 DRAINING，不能再次出租。": "Configurez l’image approuvée et démarrez le service permanent. Créez la tâche de vérification seulement après l’apparition du signal en ligne. La plateforme contrôle l’identité du GPU, CUDA, la mémoire, le stockage, l’image immuable, le réseau et les ports. Une preuve expirée, un changement de politique ou de spécification, un Agent hors ligne ou un échec de nettoyage suspend les offres ; l’appareil reste DRAINING et ne peut plus être loué tant que le nettoyage échoue.",
  },
  th: {
    "安装包由当前网站版本自动生成，不包含密钥、账号、配对码或服务器配置。不要使用第三方脚本，也不要把下载命令直接管道给 root shell。": "แพ็กเกจติดตั้งสร้างอัตโนมัติจากเว็บไซต์เวอร์ชันปัจจุบัน และไม่มีคีย์ บัญชี รหัสจับคู่ หรือการตั้งค่าเซิร์ฟเวอร์ อย่าใช้สคริปต์ของบุคคลที่สามหรือส่งคำสั่งดาวน์โหลดเข้า root shell โดยตรง",
    "首期每个 Agent 只托管一张 RTX 4090 或 H100，禁止 MIG 和多租户切片。多卡服务器必须先用 `nvidia-smi` 明确选择一张物理卡；其余 GPU 不会被 Agent 使用。机器必须具备 NVIDIA 驱动、Docker Engine、NVIDIA Container Toolkit、稳定公网地址和最多 200 个预留端口。": "ระยะแรก Agent แต่ละตัวดูแล RTX 4090 หรือ H100 เพียงหนึ่งใบ ห้ามใช้ MIG และการแบ่งแบบหลายผู้เช่า เซิร์ฟเวอร์หลาย GPU ต้องเลือกการ์ดจริงหนึ่งใบด้วย `nvidia-smi` อย่างชัดเจน ส่วน GPU อื่นจะไม่ถูกใช้ เครื่องต้องมีไดรเวอร์ NVIDIA, Docker Engine, NVIDIA Container Toolkit, ที่อยู่สาธารณะที่เสถียร และพอร์ตสำรองไม่เกิน 200 พอร์ต",
    "安装器会检查 `nvidia-smi`、Docker Unix Socket、Node.js 和 systemd；缺失任意一项都会退出，不会登记虚假设备。": "ตัวติดตั้งตรวจสอบ `nvidia-smi`, Docker Unix Socket, Node.js และ systemd หากขาดรายการใดจะหยุดทันทีและไม่ลงทะเบียนอุปกรณ์ปลอม",
    "只有 `sha256sum` 返回 OK、文件清单与页面版本一致时才继续。安装包内的 `release-manifest.json` 还记录每个源文件的摘要和网站提交版本。": "ดำเนินการต่อเมื่อ `sha256sum` คืนค่า OK และรายการไฟล์ตรงกับเวอร์ชันบนหน้าเท่านั้น `release-manifest.json` ในแพ็กเกจยังบันทึกไดเจสต์ของไฟล์ต้นฉบับแต่ละไฟล์และรุ่นคอมมิตของเว็บไซต์",
    "体检不安装服务、不改配置，也不会启动容器；它只检查 Ubuntu、系统级 Node.js、单卡 GPU、Docker NVIDIA Runtime、可用容量和整段本机端口。输出中的 `controlPlaneReachability: PENDING` 是正常的，公网入口必须等配对后由 Cloud 发起一次性挑战复验。安装完成时，只有本机 root Actuator 会启动；联网的 Host Agent 仍保持停止。": "การตรวจเบื้องต้นไม่ติดตั้งบริการ ไม่เปลี่ยนการตั้งค่า และไม่เริ่มคอนเทนเนอร์ โดยตรวจเฉพาะ Ubuntu, Node.js ระดับระบบ, GPU หนึ่งใบ, Docker NVIDIA Runtime, ความจุที่ใช้ได้ และช่วงพอร์ตภายในทั้งหมด ค่า `controlPlaneReachability: PENDING` เป็นปกติ จุดเข้าสาธารณะจะได้รับการทดสอบซ้ำด้วยคำท้าครั้งเดียวจาก Cloud หลังจับคู่ เมื่อติดตั้งเสร็จจะเริ่มเฉพาะ root Actuator ภายใน ส่วน Host Agent ที่เชื่อมเครือข่ายยังคงหยุดอยู่",
    "登录后进入供应商控制台，提交主体与设备权属资料，等待管理员批准。": "หลังเข้าสู่ระบบ ให้เปิดคอนโซลผู้ให้บริการ ส่งข้อมูลตัวตนและหลักฐานสิทธิ์ในอุปกรณ์ แล้วรอผู้ดูแลอนุมัติ",
    "在“资源 → 登记新资源”签发一次性 JSON。它只在五分钟内有效，成功注册后立即失效。": "ออก JSON ใช้ครั้งเดียวที่ “ทรัพยากร → ลงทะเบียนทรัพยากรใหม่” ใช้ได้ห้านาทีและหมดอายุทันทีเมื่อลงทะเบียนสำเร็จ",
    "把 JSON 放进 Agent 专属目录并设为 `0600`。Agent 会拒绝相对路径、软链接、其他所有者或可被组/其他用户读取的文件。": "วาง JSON ในไดเรกทอรีส่วนตัวของ Agent และตั้งเป็น `0600` Agent จะปฏิเสธพาธสัมพัทธ์ ลิงก์สัญลักษณ์ เจ้าของอื่น หรือไฟล์ที่กลุ่มและผู้ใช้อื่นอ่านได้",
    "只有最后一条命令返回 `connection.verified` 才表示 Cloud 已接受设备的第一条签名连接检查。此命令以 OFFLINE 状态报告，不会领取验真或租赁任务；网页会自动显示“连接已验证，等待启动服务”。": "เฉพาะเมื่อคำสั่งสุดท้ายคืนค่า `connection.verified` จึงหมายความว่า Cloud ยอมรับการตรวจการเชื่อมต่อที่ลงลายมือชื่อครั้งแรก คำสั่งนี้รายงานสถานะ OFFLINE และจะไม่รับงานตรวจสอบหรือให้เช่า หน้าเว็บจะแสดงอัตโนมัติว่าตรวจสอบการเชื่อมต่อแล้วและกำลังรอเริ่มบริการ",
    "从供应商控制台复制完整的 `ghcr.io/...@sha256:...` 镜像摘要，先按摘要拉取，再把 `KAI_HOSTING_APPROVED_IMAGES` 和配对时同一张卡的 `KAI_HOST_GPU_UUID` 写入 `/etc/kai-host-actuator.env`。`latest`、普通 tag 和任意第三方仓库都会被拒绝；未被 root 配置批准的 GPU 同样无法分配。": "คัดลอกไดเจสต์อิมเมจ `ghcr.io/...@sha256:...` แบบเต็มจากคอนโซลผู้ให้บริการ แล้ว pull ด้วยไดเจสต์ จากนั้นเขียน `KAI_HOSTING_APPROVED_IMAGES` และ `KAI_HOST_GPU_UUID` ของการ์ดเดียวกับที่จับคู่ลงใน `/etc/kai-host-actuator.env` ระบบจะปฏิเสธ `latest`, tag ทั่วไป, รีจิสทรีบุคคลที่สาม และ GPU ที่ไม่ได้รับอนุมัติในการตั้งค่า root",
    "先配置批准镜像并启动常驻服务。网页看到在线心跳后再创建验真任务；平台会核对 GPU 身份、CUDA、显存、存储、不可变工作负载镜像、网络和端口可达性。证据过期、镜像策略变化、规格变化、Agent 离线或清理失败会自动暂停报价；清理失败的设备保持 DRAINING，不能再次出租。": "ตั้งค่าอิมเมจที่อนุมัติและเริ่มบริการประจำก่อน สร้างงานตรวจสอบหลังหน้าเว็บแสดง heartbeat ออนไลน์ แพลตฟอร์มจะตรวจตัวตน GPU, CUDA, หน่วยความจำ, พื้นที่เก็บข้อมูล, อิมเมจเวิร์กโหลดแบบคงที่, เครือข่าย และการเข้าถึงพอร์ต หลักฐานหมดอายุ นโยบายอิมเมจหรือสเปกเปลี่ยน Agent ออฟไลน์ หรือการล้างล้มเหลวจะพักข้อเสนออัตโนมัติ อุปกรณ์ที่ล้างไม่สำเร็จจะคงสถานะ DRAINING และให้เช่าอีกไม่ได้",
  },
  vi: {
    "安装包由当前网站版本自动生成，不包含密钥、账号、配对码或服务器配置。不要使用第三方脚本，也不要把下载命令直接管道给 root shell。": "Gói cài đặt được tạo tự động từ phiên bản website hiện tại và không chứa khóa, tài khoản, mã ghép nối hay cấu hình máy chủ. Không dùng script bên thứ ba hoặc chuyển trực tiếp lệnh tải xuống vào root shell.",
    "首期每个 Agent 只托管一张 RTX 4090 或 H100，禁止 MIG 和多租户切片。多卡服务器必须先用 `nvidia-smi` 明确选择一张物理卡；其余 GPU 不会被 Agent 使用。机器必须具备 NVIDIA 驱动、Docker Engine、NVIDIA Container Toolkit、稳定公网地址和最多 200 个预留端口。": "Trong giai đoạn đầu, mỗi Agent chỉ quản lý một RTX 4090 hoặc H100; cấm MIG và chia sẻ đa đối tượng thuê. Với máy chủ nhiều GPU, phải chọn rõ một card vật lý bằng `nvidia-smi`; các GPU còn lại sẽ không được Agent sử dụng. Máy cần có trình điều khiển NVIDIA, Docker Engine, NVIDIA Container Toolkit, địa chỉ công khai ổn định và tối đa 200 cổng dành riêng.",
    "安装器会检查 `nvidia-smi`、Docker Unix Socket、Node.js 和 systemd；缺失任意一项都会退出，不会登记虚假设备。": "Trình cài đặt kiểm tra `nvidia-smi`, Docker Unix Socket, Node.js và systemd. Thiếu bất kỳ mục nào sẽ thoát và không đăng ký thiết bị giả.",
    "只有 `sha256sum` 返回 OK、文件清单与页面版本一致时才继续。安装包内的 `release-manifest.json` 还记录每个源文件的摘要和网站提交版本。": "Chỉ tiếp tục khi `sha256sum` trả về OK và danh sách tệp khớp phiên bản trên trang. `release-manifest.json` trong gói cũng ghi digest của từng tệp nguồn và bản commit của website.",
    "体检不安装服务、不改配置，也不会启动容器；它只检查 Ubuntu、系统级 Node.js、单卡 GPU、Docker NVIDIA Runtime、可用容量和整段本机端口。输出中的 `controlPlaneReachability: PENDING` 是正常的，公网入口必须等配对后由 Cloud 发起一次性挑战复验。安装完成时，只有本机 root Actuator 会启动；联网的 Host Agent 仍保持停止。": "Kiểm tra sơ bộ không cài dịch vụ, không đổi cấu hình và không khởi động container. Nó chỉ kiểm tra Ubuntu, Node.js hệ thống, một GPU, Docker NVIDIA Runtime, dung lượng khả dụng và toàn bộ dải cổng cục bộ. `controlPlaneReachability: PENDING` là bình thường; lối vào công khai phải được Cloud xác minh lại bằng thử thách một lần sau khi ghép nối. Khi cài xong, chỉ root Actuator cục bộ chạy; Host Agent có mạng vẫn dừng.",
    "登录后进入供应商控制台，提交主体与设备权属资料，等待管理员批准。": "Sau khi đăng nhập, mở bảng điều khiển nhà cung cấp, gửi thông tin chủ thể và bằng chứng sở hữu thiết bị rồi chờ quản trị viên phê duyệt.",
    "在“资源 → 登记新资源”签发一次性 JSON。它只在五分钟内有效，成功注册后立即失效。": "Tại “Tài nguyên → Đăng ký tài nguyên mới”, phát hành JSON dùng một lần. JSON chỉ có hiệu lực năm phút và hết hạn ngay khi đăng ký thành công.",
    "把 JSON 放进 Agent 专属目录并设为 `0600`。Agent 会拒绝相对路径、软链接、其他所有者或可被组/其他用户读取的文件。": "Đặt JSON trong thư mục riêng của Agent và đặt quyền `0600`. Agent từ chối đường dẫn tương đối, liên kết mềm, chủ sở hữu khác hoặc tệp mà nhóm/người dùng khác có thể đọc.",
    "只有最后一条命令返回 `connection.verified` 才表示 Cloud 已接受设备的第一条签名连接检查。此命令以 OFFLINE 状态报告，不会领取验真或租赁任务；网页会自动显示“连接已验证，等待启动服务”。": "Chỉ khi lệnh cuối trả về `connection.verified` thì Cloud mới chấp nhận lần kiểm tra kết nối có chữ ký đầu tiên của thiết bị. Lệnh báo trạng thái OFFLINE và không nhận tác vụ xác minh hay cho thuê; trang sẽ tự hiển thị kết nối đã xác minh và đang chờ khởi động dịch vụ.",
    "从供应商控制台复制完整的 `ghcr.io/...@sha256:...` 镜像摘要，先按摘要拉取，再把 `KAI_HOSTING_APPROVED_IMAGES` 和配对时同一张卡的 `KAI_HOST_GPU_UUID` 写入 `/etc/kai-host-actuator.env`。`latest`、普通 tag 和任意第三方仓库都会被拒绝；未被 root 配置批准的 GPU 同样无法分配。": "Sao chép digest đầy đủ `ghcr.io/...@sha256:...` từ bảng điều khiển nhà cung cấp và pull theo digest. Sau đó ghi `KAI_HOSTING_APPROVED_IMAGES` cùng `KAI_HOST_GPU_UUID` của đúng card đã ghép nối vào `/etc/kai-host-actuator.env`. `latest`, tag thông thường, registry bên thứ ba và GPU chưa được cấu hình root phê duyệt đều bị từ chối.",
    "先配置批准镜像并启动常驻服务。网页看到在线心跳后再创建验真任务；平台会核对 GPU 身份、CUDA、显存、存储、不可变工作负载镜像、网络和端口可达性。证据过期、镜像策略变化、规格变化、Agent 离线或清理失败会自动暂停报价；清理失败的设备保持 DRAINING，不能再次出租。": "Trước tiên cấu hình image đã duyệt và khởi động dịch vụ thường trú. Chỉ tạo tác vụ xác minh sau khi trang hiển thị heartbeat trực tuyến. Nền tảng kiểm tra danh tính GPU, CUDA, bộ nhớ, lưu trữ, image workload bất biến, mạng và khả năng truy cập cổng. Bằng chứng hết hạn, thay đổi chính sách image hoặc thông số, Agent ngoại tuyến hay dọn dẹp thất bại sẽ tự động tạm dừng chào giá; thiết bị dọn dẹp thất bại giữ trạng thái DRAINING và không thể cho thuê lại.",
  },
  id: {
    "安装包由当前网站版本自动生成，不包含密钥、账号、配对码或服务器配置。不要使用第三方脚本，也不要把下载命令直接管道给 root shell。": "Paket instalasi dibuat otomatis dari versi situs saat ini dan tidak memuat kunci, akun, kode pemasangan, atau konfigurasi server. Jangan gunakan skrip pihak ketiga atau menyalurkan perintah unduhan langsung ke root shell.",
    "首期每个 Agent 只托管一张 RTX 4090 或 H100，禁止 MIG 和多租户切片。多卡服务器必须先用 `nvidia-smi` 明确选择一张物理卡；其余 GPU 不会被 Agent 使用。机器必须具备 NVIDIA 驱动、Docker Engine、NVIDIA Container Toolkit、稳定公网地址和最多 200 个预留端口。": "Pada tahap awal, setiap Agent hanya mengelola satu RTX 4090 atau H100; MIG dan pemisahan multi-tenant dilarang. Pada server multi-GPU, pilih satu kartu fisik secara eksplisit dengan `nvidia-smi`; GPU lain tidak digunakan Agent. Host memerlukan driver NVIDIA, Docker Engine, NVIDIA Container Toolkit, alamat publik stabil, dan maksimal 200 port cadangan.",
    "安装器会检查 `nvidia-smi`、Docker Unix Socket、Node.js 和 systemd；缺失任意一项都会退出，不会登记虚假设备。": "Pemasang memeriksa `nvidia-smi`, Docker Unix Socket, Node.js, dan systemd. Jika salah satu tidak ada, proses berhenti dan tidak mendaftarkan perangkat palsu.",
    "只有 `sha256sum` 返回 OK、文件清单与页面版本一致时才继续。安装包内的 `release-manifest.json` 还记录每个源文件的摘要和网站提交版本。": "Lanjutkan hanya jika `sha256sum` menghasilkan OK dan daftar file sesuai versi halaman. `release-manifest.json` di dalam paket juga mencatat digest setiap file sumber dan revisi situs.",
    "体检不安装服务、不改配置，也不会启动容器；它只检查 Ubuntu、系统级 Node.js、单卡 GPU、Docker NVIDIA Runtime、可用容量和整段本机端口。输出中的 `controlPlaneReachability: PENDING` 是正常的，公网入口必须等配对后由 Cloud 发起一次性挑战复验。安装完成时，只有本机 root Actuator 会启动；联网的 Host Agent 仍保持停止。": "Pemeriksaan awal tidak memasang layanan, mengubah konfigurasi, atau menjalankan container. Pemeriksaan hanya memeriksa Ubuntu, Node.js sistem, satu GPU, Docker NVIDIA Runtime, kapasitas tersedia, dan seluruh rentang port lokal. `controlPlaneReachability: PENDING` adalah normal; akses publik diverifikasi ulang oleh tantangan satu kali dari Cloud setelah pemasangan. Setelah instalasi hanya root Actuator lokal yang berjalan; Host Agent berjaringan tetap berhenti.",
    "登录后进入供应商控制台，提交主体与设备权属资料，等待管理员批准。": "Setelah masuk, buka konsol pemasok, kirim informasi identitas dan bukti kepemilikan perangkat, lalu tunggu persetujuan administrator.",
    "在“资源 → 登记新资源”签发一次性 JSON。它只在五分钟内有效，成功注册后立即失效。": "Terbitkan JSON sekali pakai di “Sumber daya → Daftarkan sumber daya baru”. JSON berlaku lima menit dan langsung kedaluwarsa setelah pendaftaran berhasil.",
    "把 JSON 放进 Agent 专属目录并设为 `0600`。Agent 会拒绝相对路径、软链接、其他所有者或可被组/其他用户读取的文件。": "Letakkan JSON di direktori khusus Agent dengan mode `0600`. Agent menolak path relatif, symlink, pemilik lain, atau file yang dapat dibaca grup/pengguna lain.",
    "只有最后一条命令返回 `connection.verified` 才表示 Cloud 已接受设备的第一条签名连接检查。此命令以 OFFLINE 状态报告，不会领取验真或租赁任务；网页会自动显示“连接已验证，等待启动服务”。": "Hanya hasil `connection.verified` dari perintah terakhir yang menandakan Cloud menerima pemeriksaan koneksi bertanda tangan pertama perangkat. Perintah melapor sebagai OFFLINE dan tidak mengambil tugas verifikasi atau sewa; halaman otomatis menampilkan koneksi telah diverifikasi dan menunggu layanan dimulai.",
    "从供应商控制台复制完整的 `ghcr.io/...@sha256:...` 镜像摘要，先按摘要拉取，再把 `KAI_HOSTING_APPROVED_IMAGES` 和配对时同一张卡的 `KAI_HOST_GPU_UUID` 写入 `/etc/kai-host-actuator.env`。`latest`、普通 tag 和任意第三方仓库都会被拒绝；未被 root 配置批准的 GPU 同样无法分配。": "Salin digest image lengkap `ghcr.io/...@sha256:...` dari konsol pemasok dan pull berdasarkan digest. Kemudian tulis `KAI_HOSTING_APPROVED_IMAGES` dan `KAI_HOST_GPU_UUID` kartu yang sama saat pemasangan ke `/etc/kai-host-actuator.env`. `latest`, tag biasa, registry pihak ketiga, dan GPU yang tidak disetujui konfigurasi root akan ditolak.",
    "先配置批准镜像并启动常驻服务。网页看到在线心跳后再创建验真任务；平台会核对 GPU 身份、CUDA、显存、存储、不可变工作负载镜像、网络和端口可达性。证据过期、镜像策略变化、规格变化、Agent 离线或清理失败会自动暂停报价；清理失败的设备保持 DRAINING，不能再次出租。": "Konfigurasikan image yang disetujui dan jalankan layanan tetap. Buat tugas verifikasi setelah halaman menampilkan heartbeat online. Platform memeriksa identitas GPU, CUDA, memori, penyimpanan, image workload tetap, jaringan, dan keterjangkauan port. Bukti kedaluwarsa, perubahan kebijakan image atau spesifikasi, Agent offline, atau kegagalan pembersihan akan menjeda penawaran; perangkat yang gagal dibersihkan tetap DRAINING dan tidak dapat disewakan lagi.",
  },
  ms: {
    "安装包由当前网站版本自动生成，不包含密钥、账号、配对码或服务器配置。不要使用第三方脚本，也不要把下载命令直接管道给 root shell。": "Pakej pemasangan dijana automatik daripada versi laman semasa dan tidak mengandungi kunci, akaun, kod gandingan atau konfigurasi pelayan. Jangan gunakan skrip pihak ketiga atau salurkan arahan muat turun terus ke root shell.",
    "首期每个 Agent 只托管一张 RTX 4090 或 H100，禁止 MIG 和多租户切片。多卡服务器必须先用 `nvidia-smi` 明确选择一张物理卡；其余 GPU 不会被 Agent 使用。机器必须具备 NVIDIA 驱动、Docker Engine、NVIDIA Container Toolkit、稳定公网地址和最多 200 个预留端口。": "Pada peringkat awal, setiap Agent hanya mengurus satu RTX 4090 atau H100; MIG dan pembahagian berbilang penyewa dilarang. Pada pelayan berbilang GPU, pilih satu kad fizikal dengan jelas menggunakan `nvidia-smi`; GPU lain tidak digunakan oleh Agent. Hos memerlukan pemacu NVIDIA, Docker Engine, NVIDIA Container Toolkit, alamat awam stabil dan sehingga 200 port simpanan.",
    "安装器会检查 `nvidia-smi`、Docker Unix Socket、Node.js 和 systemd；缺失任意一项都会退出，不会登记虚假设备。": "Pemasang memeriksa `nvidia-smi`, Docker Unix Socket, Node.js dan systemd. Jika mana-mana satu tiada, proses akan berhenti dan tidak mendaftarkan peranti palsu.",
    "只有 `sha256sum` 返回 OK、文件清单与页面版本一致时才继续。安装包内的 `release-manifest.json` 还记录每个源文件的摘要和网站提交版本。": "Teruskan hanya apabila `sha256sum` mengembalikan OK dan senarai fail sepadan dengan versi halaman. `release-manifest.json` dalam pakej turut merekodkan digest setiap fail sumber dan semakan laman.",
    "体检不安装服务、不改配置，也不会启动容器；它只检查 Ubuntu、系统级 Node.js、单卡 GPU、Docker NVIDIA Runtime、可用容量和整段本机端口。输出中的 `controlPlaneReachability: PENDING` 是正常的，公网入口必须等配对后由 Cloud 发起一次性挑战复验。安装完成时，只有本机 root Actuator 会启动；联网的 Host Agent 仍保持停止。": "Pemeriksaan awal tidak memasang perkhidmatan, mengubah konfigurasi atau memulakan container. Ia hanya memeriksa Ubuntu, Node.js sistem, satu GPU, Docker NVIDIA Runtime, kapasiti tersedia dan keseluruhan julat port setempat. `controlPlaneReachability: PENDING` adalah normal; akses awam akan disahkan semula melalui cabaran sekali daripada Cloud selepas gandingan. Selepas pemasangan, hanya root Actuator setempat bermula; Host Agent berangkaian kekal berhenti.",
    "登录后进入供应商控制台，提交主体与设备权属资料，等待管理员批准。": "Selepas log masuk, buka konsol pembekal, serahkan maklumat identiti dan bukti pemilikan peranti, kemudian tunggu kelulusan pentadbir.",
    "在“资源 → 登记新资源”签发一次性 JSON。它只在五分钟内有效，成功注册后立即失效。": "Keluarkan JSON sekali guna di “Sumber → Daftar sumber baharu”. JSON sah selama lima minit dan tamat serta-merta selepas pendaftaran berjaya.",
    "把 JSON 放进 Agent 专属目录并设为 `0600`。Agent 会拒绝相对路径、软链接、其他所有者或可被组/其他用户读取的文件。": "Letakkan JSON dalam direktori khusus Agent dengan mod `0600`. Agent menolak laluan relatif, pautan simbolik, pemilik lain atau fail yang boleh dibaca kumpulan/pengguna lain.",
    "只有最后一条命令返回 `connection.verified` 才表示 Cloud 已接受设备的第一条签名连接检查。此命令以 OFFLINE 状态报告，不会领取验真或租赁任务；网页会自动显示“连接已验证，等待启动服务”。": "Hanya apabila arahan terakhir mengembalikan `connection.verified`, Cloud telah menerima semakan sambungan bertandatangan pertama peranti. Arahan melaporkan status OFFLINE dan tidak mengambil tugas pengesahan atau sewaan; halaman akan memaparkan sambungan disahkan dan menunggu perkhidmatan dimulakan.",
    "从供应商控制台复制完整的 `ghcr.io/...@sha256:...` 镜像摘要，先按摘要拉取，再把 `KAI_HOSTING_APPROVED_IMAGES` 和配对时同一张卡的 `KAI_HOST_GPU_UUID` 写入 `/etc/kai-host-actuator.env`。`latest`、普通 tag 和任意第三方仓库都会被拒绝；未被 root 配置批准的 GPU 同样无法分配。": "Salin digest imej lengkap `ghcr.io/...@sha256:...` daripada konsol pembekal dan pull berdasarkan digest. Kemudian tulis `KAI_HOSTING_APPROVED_IMAGES` serta `KAI_HOST_GPU_UUID` kad yang sama ketika gandingan ke `/etc/kai-host-actuator.env`. `latest`, tag biasa, repositori pihak ketiga dan GPU yang tidak diluluskan konfigurasi root akan ditolak.",
    "先配置批准镜像并启动常驻服务。网页看到在线心跳后再创建验真任务；平台会核对 GPU 身份、CUDA、显存、存储、不可变工作负载镜像、网络和端口可达性。证据过期、镜像策略变化、规格变化、Agent 离线或清理失败会自动暂停报价；清理失败的设备保持 DRAINING，不能再次出租。": "Konfigurasikan imej yang diluluskan dan mulakan perkhidmatan tetap. Cipta tugas pengesahan selepas halaman menunjukkan heartbeat dalam talian. Platform menyemak identiti GPU, CUDA, memori, storan, imej workload kekal, rangkaian dan kebolehcapaian port. Bukti tamat tempoh, perubahan dasar imej atau spesifikasi, Agent luar talian atau kegagalan pembersihan akan menjeda tawaran; peranti yang gagal dibersihkan kekal DRAINING dan tidak boleh disewa lagi.",
  },
};

function localizeText(locale: Locale, value: string) {
  if (locale === "zh-CN") return value;
  const trimmed = value.trim();
  const translated = (locale === "en" ? undefined : CORE[locale][trimmed] ?? BODY[locale][trimmed]) ?? EN[trimmed];
  return translated ? value.replace(trimmed, translated) : value;
}

function localizeNode(locale: Locale, node: ReactNode): ReactNode {
  if (typeof node === "string") return localizeText(locale, node);
  if (!isValidElement(node)) return node;
  const element = node as ReactElement<Record<string, unknown>>;
  const next: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(element.props)) {
    next[key] = key === "children"
      ? Children.map(value as ReactNode, (child) => localizeNode(locale, child))
      : typeof value === "string" ? localizeText(locale, value) : value;
  }
  return cloneElement(element, next);
}

function Command({ children }: { children: string }) {
  return <pre className={styles.commandBlock} tabIndex={0}><code>{children}</code></pre>;
}

export default async function HostAgentGuidePage() {
  const locale = await getRequestLocale();
  return localizeNode(locale,
    <div className={`${styles.docsPage} ${styles.agentGuide}`}>
      <div className={styles.docsTopbar}>
        <div><span>KAI Cloud Docs</span><b>Host Agent 安装与配对</b></div>
        <div><Link href="/hosting/personal-gpu">上架要求</Link><Link href="/login?returnTo=%2Fsupply%2Fresources%2Fnew">进入供应商控制台</Link></div>
      </div>
      <article className={`${styles.article} ${styles.articleStandalone}`}>
        <header className={styles.articleHero}>
          <p>HOST AGENT · {AGENT_VERSION}</p>
          <h1>先校验安装包，再让一台真实 GPU 接入平台。</h1>
          <p>安装包由当前网站版本自动生成，不包含密钥、账号、配对码或服务器配置。不要使用第三方脚本，也不要把下载命令直接管道给 root shell。</p>
          <div className={styles.choiceGrid}>
            <a download href={`/downloads/${ARCHIVE}`}><span>安装包</span><strong>下载 {ARCHIVE}</strong><small>Ubuntu · Node.js 24.15+ · systemd</small></a>
            <a download href={`/downloads/${ARCHIVE}.sha256`}><span>完整性</span><strong>下载 SHA-256 校验文件</strong><small>校验失败时立即停止</small></a>
          </div>
        </header>

        <section>
          <div className={styles.sectionLabel}>01 · REQUIREMENTS</div>
          <h2>准备一台首期支持的主机</h2>
          <p className={styles.lead}>首期每个 Agent 只托管一张 RTX 4090 或 H100，禁止 MIG 和多租户切片。多卡服务器必须先用 `nvidia-smi` 明确选择一张物理卡；其余 GPU 不会被 Agent 使用。机器必须具备 NVIDIA 驱动、Docker Engine、NVIDIA Container Toolkit、稳定公网地址和最多 200 个预留端口。</p>
          <div className={styles.note}><strong>不会在普通云服务器上假装 GPU</strong><p>安装器会检查 `nvidia-smi`、Docker Unix Socket、Node.js 和 systemd；缺失任意一项都会退出，不会登记虚假设备。</p></div>
        </section>

        <section>
          <div className={styles.sectionLabel}>02 · VERIFY PACKAGE</div>
          <h2>校验并审阅安装包</h2>
          <Command>{`cd ~/Downloads\nsha256sum --check ${ARCHIVE}.sha256\ntar -tzf ${ARCHIVE}\ntar -xzf ${ARCHIVE}\ncd kai-host-agent-${AGENT_VERSION}\nless release-manifest.json\nless install.sh`}</Command>
          <p>只有 `sha256sum` 返回 OK、文件清单与页面版本一致时才继续。安装包内的 `release-manifest.json` 还记录每个源文件的摘要和网站提交版本。</p>
        </section>

        <section>
          <div className={styles.sectionLabel}>03 · PREFLIGHT & INSTALL</div>
          <h2>先做只读体检，再安装受限服务</h2>
          <Command>{`nvidia-smi --query-gpu=uuid,name,memory.total --format=csv,noheader\nsudo node ./src/preflight.mjs \\\n  --public-host "gpu.example.com" \\\n  --ssh-port-start "22000" \\\n  --ssh-port-end "22019" \\\n  --gpu-uuid "GPU-从上一条命令复制" \\\n  --storage-path "/var/lib"\nsudo ./install.sh\nsudo -u kai-host-agent -- kai-host-agent doctor \\\n  --public-host "gpu.example.com" \\\n  --ssh-port-start "22000" \\\n  --ssh-port-end "22019" \\\n  --gpu-uuid "GPU-同一张物理卡"`}</Command>
          <p>体检不安装服务、不改配置，也不会启动容器；它只检查 Ubuntu、系统级 Node.js、单卡 GPU、Docker NVIDIA Runtime、可用容量和整段本机端口。输出中的 `controlPlaneReachability: PENDING` 是正常的，公网入口必须等配对后由 Cloud 发起一次性挑战复验。安装完成时，只有本机 root Actuator 会启动；联网的 Host Agent 仍保持停止。</p>
        </section>

        <section>
          <div className={styles.sectionLabel}>04 · PAIR</div>
          <h2>用五分钟一次性凭证完成配对</h2>
          <ol className={styles.steps}>
            <li><span>1</span><div><h3>完成供应商审核</h3><p>登录后进入供应商控制台，提交主体与设备权属资料，等待管理员批准。</p></div></li>
            <li><span>2</span><div><h3>签发配对内容</h3><p>在“资源 → 登记新资源”签发一次性 JSON。它只在五分钟内有效，成功注册后立即失效。</p></div></li>
            <li><span>3</span><div><h3>通过私有文件配对</h3><p>把 JSON 放进 Agent 专属目录并设为 `0600`。Agent 会拒绝相对路径、软链接、其他所有者或可被组/其他用户读取的文件。</p></div></li>
          </ol>
          <Command>{`sudo install -o kai-host-agent -g kai-host-agent -m 0600 pairing.json /var/lib/kai-host-agent/pairing.json\nsudo -u kai-host-agent -- kai-host-agent pair \\\n  --pairing-file /var/lib/kai-host-agent/pairing.json \\\n  --display-name "H100 服务器 01" \\\n  --public-host "gpu.example.com" \\\n  --ssh-port-start "22000" \\\n  --ssh-port-end "22019" \\\n  --gpu-uuid "GPU-同一张物理卡"\nsudo shred -u /var/lib/kai-host-agent/pairing.json\nsudo -u kai-host-agent -- kai-host-agent check-connection`}</Command>
          <p>只有最后一条命令返回 `connection.verified` 才表示 Cloud 已接受设备的第一条签名连接检查。此命令以 OFFLINE 状态报告，不会领取验真或租赁任务；网页会自动显示“连接已验证，等待启动服务”。</p>
        </section>

        <section>
          <div className={styles.sectionLabel}>05 · APPROVED IMAGE & START</div>
          <h2>配置平台批准的不可变镜像</h2>
          <p>从供应商控制台复制完整的 `ghcr.io/...@sha256:...` 镜像摘要，先按摘要拉取，再把 `KAI_HOSTING_APPROVED_IMAGES` 和配对时同一张卡的 `KAI_HOST_GPU_UUID` 写入 `/etc/kai-host-actuator.env`。`latest`、普通 tag 和任意第三方仓库都会被拒绝；未被 root 配置批准的 GPU 同样无法分配。</p>
          <Command>{`sudo docker pull "ghcr.io/mandow123/kai-cloud-gpu-workload@sha256:<平台显示的64位摘要>"\nsudoedit /etc/kai-host-actuator.env\nsudo systemctl restart kai-host-actuator\nsudo systemctl enable --now kai-host-agent\nsudo systemctl status kai-host-agent --no-pager`}</Command>
        </section>

        <section>
          <div className={styles.sectionLabel}>06 · VERIFY & RECOVERY</div>
          <h2>回到控制台完成验真</h2>
          <p>先配置批准镜像并启动常驻服务。网页看到在线心跳后再创建验真任务；平台会核对 GPU 身份、CUDA、显存、存储、不可变工作负载镜像、网络和端口可达性。证据过期、镜像策略变化、规格变化、Agent 离线或清理失败会自动暂停报价；清理失败的设备保持 DRAINING，不能再次出租。</p>
          <Link className={styles.actionLink} href="/login?returnTo=%2Fsupply%2Fresources">查看设备与验真状态 →</Link>
        </section>
      </article>
    </div>
  ) as ReactElement;
}
