export const CARD_HOUR_SCHEMA_VERSION = 8;

export const cardHourSchemaStatements = [
  `CREATE TABLE IF NOT EXISTS card_hour_schema_migrations (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS card_hour_wallets (
    organization_id TEXT PRIMARY KEY,
    available_micros INTEGER NOT NULL DEFAULT 0 CHECK (available_micros >= 0),
    held_micros INTEGER NOT NULL DEFAULT 0 CHECK (held_micros >= 0),
    lifetime_topup_micros INTEGER NOT NULL DEFAULT 0 CHECK (lifetime_topup_micros >= 0),
    lifetime_spent_micros INTEGER NOT NULL DEFAULT 0 CHECK (lifetime_spent_micros >= 0),
    version INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS card_hour_ledger_batches (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    operation TEXT NOT NULL CHECK (operation IN ('TOPUP','ORDER_CAPTURE','ORDER_REFUND','BUYBACK_HOLD','BUYBACK_RELEASE','RENTAL_INCOME','MANAGED_GPU_INCOME','COMMISSION_INCOME','COMMISSION_REVERSAL')),
    business_key TEXT NOT NULL UNIQUE,
    amount_micros INTEGER NOT NULL CHECK (amount_micros > 0),
    status TEXT NOT NULL CHECK (status = 'POSTED'),
    metadata_json TEXT NOT NULL,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS card_hour_ledger_entries (
    id TEXT PRIMARY KEY,
    batch_id TEXT NOT NULL,
    organization_id TEXT,
    account_code TEXT NOT NULL,
    side TEXT NOT NULL CHECK (side IN ('DEBIT','CREDIT')),
    amount_micros INTEGER NOT NULL CHECK (amount_micros > 0),
    balance_after_micros INTEGER,
    created_at TEXT NOT NULL,
    FOREIGN KEY (batch_id) REFERENCES card_hour_ledger_batches(id)
  )`,
  `CREATE INDEX IF NOT EXISTS card_hour_ledger_org_time_idx ON card_hour_ledger_entries(organization_id, created_at DESC)`,
  `CREATE TRIGGER IF NOT EXISTS card_hour_batches_immutable_update BEFORE UPDATE ON card_hour_ledger_batches BEGIN SELECT RAISE(ABORT, 'card hour batch immutable'); END`,
  `CREATE TRIGGER IF NOT EXISTS card_hour_batches_immutable_delete BEFORE DELETE ON card_hour_ledger_batches BEGIN SELECT RAISE(ABORT, 'card hour batch immutable'); END`,
  `CREATE TRIGGER IF NOT EXISTS card_hour_entries_immutable_update BEFORE UPDATE ON card_hour_ledger_entries BEGIN SELECT RAISE(ABORT, 'card hour entry immutable'); END`,
  `CREATE TRIGGER IF NOT EXISTS card_hour_entries_immutable_delete BEFORE DELETE ON card_hour_ledger_entries BEGIN SELECT RAISE(ABORT, 'card hour entry immutable'); END`,
  `CREATE TABLE IF NOT EXISTS card_hour_topup_orders (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    account_id TEXT NOT NULL,
    card_hour_micros INTEGER NOT NULL CHECK (card_hour_micros >= 5000000 AND card_hour_micros % 5000000 = 0),
    amount_cents INTEGER NOT NULL CHECK (amount_cents > 0),
    currency TEXT NOT NULL CHECK (currency = 'CNY'),
    provider TEXT NOT NULL CHECK (provider IN ('ALIPAY','QIXIANG_PAY')),
    provider_merchant_ref TEXT,
    provider_payment_type TEXT CHECK (provider_payment_type IS NULL OR provider_payment_type IN ('alipay','wxpay')),
    status TEXT NOT NULL CHECK (status IN ('PROCESSING','PENDING','CAPTURED','CLOSED','RECONCILIATION_REQUIRED')),
    idempotency_key TEXT NOT NULL,
    payload_hash TEXT NOT NULL,
    provider_transaction_id TEXT,
    checkout_url TEXT,
    checkout_created_at TEXT,
    expires_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (organization_id, idempotency_key),
    UNIQUE (provider, provider_transaction_id),
    CHECK ((provider = 'ALIPAY' AND provider_merchant_ref IS NULL AND provider_payment_type IS NULL)
      OR (provider = 'QIXIANG_PAY' AND provider_merchant_ref IS NOT NULL AND provider_payment_type IS NOT NULL)),
    CHECK ((checkout_url IS NULL AND checkout_created_at IS NULL) OR (checkout_url IS NOT NULL AND checkout_created_at IS NOT NULL))
  )`,
  `CREATE INDEX IF NOT EXISTS card_hour_topups_org_time_idx ON card_hour_topup_orders(organization_id, created_at DESC)`,
  `CREATE TABLE IF NOT EXISTS card_hour_topup_events (
    id TEXT PRIMARY KEY,
    topup_order_id TEXT NOT NULL,
    provider_event_id TEXT NOT NULL UNIQUE,
    provider_transaction_id TEXT NOT NULL,
    event_type TEXT NOT NULL CHECK (event_type IN ('CAPTURED','CLOSED')),
    amount_cents INTEGER NOT NULL,
    payload_digest TEXT NOT NULL,
    occurred_at TEXT NOT NULL,
    received_at TEXT NOT NULL,
    FOREIGN KEY (topup_order_id) REFERENCES card_hour_topup_orders(id)
  )`,
  `CREATE TABLE IF NOT EXISTS card_hour_topup_reconciliation_claims (
    topup_order_id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    claim_token TEXT,
    claimed_at TEXT,
    next_query_at TEXT NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    updated_at TEXT NOT NULL,
    FOREIGN KEY (topup_order_id) REFERENCES card_hour_topup_orders(id),
    CHECK ((claim_token IS NULL AND claimed_at IS NULL) OR (claim_token IS NOT NULL AND claimed_at IS NOT NULL))
  )`,
  `CREATE INDEX IF NOT EXISTS card_hour_topup_reconciliation_due_idx ON card_hour_topup_reconciliation_claims(next_query_at,claimed_at)`,
  `CREATE TABLE IF NOT EXISTS card_hour_topup_reconciliation_requests (
    organization_id TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    topup_order_id TEXT NOT NULL,
    payload_hash TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (organization_id,idempotency_key),
    FOREIGN KEY (topup_order_id) REFERENCES card_hour_topup_orders(id)
  )`,
  `CREATE INDEX IF NOT EXISTS card_hour_topup_reconciliation_requests_order_idx ON card_hour_topup_reconciliation_requests(topup_order_id,created_at DESC)`,
  `CREATE TABLE IF NOT EXISTS card_hour_qixiang_query_protection (
    credential_id TEXT PRIMARY KEY,
    window_started_at TEXT NOT NULL,
    request_count INTEGER NOT NULL DEFAULT 0 CHECK (request_count >= 0),
    consecutive_failures INTEGER NOT NULL DEFAULT 0 CHECK (consecutive_failures >= 0),
    circuit_open_until TEXT,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS card_hour_paid_entitlement_lots (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    topup_order_id TEXT NOT NULL UNIQUE,
    granted_micros INTEGER NOT NULL CHECK (granted_micros > 0),
    available_micros INTEGER NOT NULL CHECK (available_micros >= 0),
    held_micros INTEGER NOT NULL DEFAULT 0 CHECK (held_micros >= 0),
    spent_micros INTEGER NOT NULL DEFAULT 0 CHECK (spent_micros >= 0),
    expired_micros INTEGER NOT NULL DEFAULT 0 CHECK (expired_micros >= 0),
    granted_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (topup_order_id) REFERENCES card_hour_topup_orders(id),
    CHECK (available_micros + held_micros + spent_micros + expired_micros = granted_micros)
  )`,
  `CREATE INDEX IF NOT EXISTS card_hour_paid_entitlement_expiry_idx ON card_hour_paid_entitlement_lots(expires_at,organization_id) WHERE available_micros > 0`,
  `CREATE TABLE IF NOT EXISTS card_hour_paid_entitlement_hold_allocations (
    hold_type TEXT NOT NULL CHECK (hold_type IN ('HOSTING_V2','MANUAL_ORDER_V1')),
    hold_id TEXT NOT NULL,
    lot_id TEXT NOT NULL,
    allocated_micros INTEGER NOT NULL CHECK (allocated_micros > 0),
    held_micros INTEGER NOT NULL CHECK (held_micros >= 0),
    spent_micros INTEGER NOT NULL DEFAULT 0 CHECK (spent_micros >= 0),
    released_micros INTEGER NOT NULL DEFAULT 0 CHECK (released_micros >= 0),
    expired_micros INTEGER NOT NULL DEFAULT 0 CHECK (expired_micros >= 0),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (hold_type,hold_id,lot_id),
    FOREIGN KEY (lot_id) REFERENCES card_hour_paid_entitlement_lots(id),
    CHECK (held_micros + spent_micros + released_micros + expired_micros = allocated_micros)
  )`,
  `CREATE INDEX IF NOT EXISTS card_hour_paid_entitlement_hold_lot_idx ON card_hour_paid_entitlement_hold_allocations(lot_id,held_micros)`,
  `CREATE TABLE IF NOT EXISTS card_hour_paid_entitlement_events (
    id TEXT PRIMARY KEY,
    lot_id TEXT NOT NULL,
    organization_id TEXT NOT NULL,
    event_type TEXT NOT NULL CHECK (event_type IN ('GRANTED','EXPIRED')),
    amount_micros INTEGER NOT NULL CHECK (amount_micros > 0),
    occurred_at TEXT NOT NULL,
    FOREIGN KEY (lot_id) REFERENCES card_hour_paid_entitlement_lots(id)
  )`,
  `CREATE INDEX IF NOT EXISTS card_hour_paid_entitlement_events_org_time_idx ON card_hour_paid_entitlement_events(organization_id,occurred_at DESC)`,
  `CREATE TRIGGER IF NOT EXISTS card_hour_paid_entitlement_events_immutable_update BEFORE UPDATE ON card_hour_paid_entitlement_events BEGIN SELECT RAISE(ABORT, 'paid entitlement event immutable'); END`,
  `CREATE TRIGGER IF NOT EXISTS card_hour_paid_entitlement_events_immutable_delete BEFORE DELETE ON card_hour_paid_entitlement_events BEGIN SELECT RAISE(ABORT, 'paid entitlement event immutable'); END`,
  `CREATE TABLE IF NOT EXISTS card_hour_topup_appeals (
    id TEXT PRIMARY KEY,
    case_number TEXT NOT NULL UNIQUE,
    topup_order_id TEXT NOT NULL,
    organization_id TEXT NOT NULL,
    account_id TEXT NOT NULL,
    reason TEXT NOT NULL CHECK (reason IN ('PENDING_TIMEOUT','CLOSED_BUT_CHARGED','RECONCILIATION_REQUIRED')),
    description TEXT NOT NULL CHECK (length(description) BETWEEN 10 AND 2000),
    status TEXT NOT NULL CHECK (status IN ('OPEN','UNDER_REVIEW','RESOLVED','CLOSED')),
    resolution_note TEXT,
    assigned_admin_principal_id TEXT,
    idempotency_key TEXT NOT NULL,
    payload_hash TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    resolved_at TEXT,
    closed_at TEXT,
    UNIQUE (organization_id, topup_order_id),
    UNIQUE (organization_id, idempotency_key),
    FOREIGN KEY (topup_order_id) REFERENCES card_hour_topup_orders(id),
    CHECK ((status IN ('RESOLVED','CLOSED') AND resolution_note IS NOT NULL) OR (status IN ('OPEN','UNDER_REVIEW') AND resolution_note IS NULL))
  )`,
  `CREATE INDEX IF NOT EXISTS card_hour_topup_appeals_admin_idx ON card_hour_topup_appeals(status,updated_at DESC)`,
  `CREATE INDEX IF NOT EXISTS card_hour_topup_appeals_org_idx ON card_hour_topup_appeals(organization_id,updated_at DESC)`,
  `CREATE TABLE IF NOT EXISTS card_hour_topup_appeal_events (
    id TEXT PRIMARY KEY,
    appeal_id TEXT NOT NULL,
    event_type TEXT NOT NULL CHECK (event_type IN ('CREATE','START_REVIEW','RESOLVE','CLOSE')),
    actor_principal_id TEXT NOT NULL,
    payload_hash TEXT NOT NULL,
    occurred_at TEXT NOT NULL,
    FOREIGN KEY (appeal_id) REFERENCES card_hour_topup_appeals(id)
  )`,
  `CREATE INDEX IF NOT EXISTS card_hour_topup_appeal_events_case_idx ON card_hour_topup_appeal_events(appeal_id,occurred_at)`,
  `CREATE TRIGGER IF NOT EXISTS card_hour_topup_appeal_events_immutable_update BEFORE UPDATE ON card_hour_topup_appeal_events BEGIN SELECT RAISE(ABORT, 'topup appeal event immutable'); END`,
  `CREATE TRIGGER IF NOT EXISTS card_hour_topup_appeal_events_immutable_delete BEFORE DELETE ON card_hour_topup_appeal_events BEGIN SELECT RAISE(ABORT, 'topup appeal event immutable'); END`,
  `CREATE TABLE IF NOT EXISTS card_hour_topup_appeal_member_reads (
    appeal_id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    seen_version INTEGER NOT NULL CHECK (seen_version > 0),
    seen_at TEXT NOT NULL,
    FOREIGN KEY (appeal_id) REFERENCES card_hour_topup_appeals(id)
  )`,
  `CREATE INDEX IF NOT EXISTS card_hour_topup_appeal_member_reads_org_idx ON card_hour_topup_appeal_member_reads(organization_id,seen_at DESC)`,
  `CREATE TABLE IF NOT EXISTS card_hour_order_payments (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    account_id TEXT NOT NULL,
    source_system TEXT NOT NULL CHECK (source_system IN ('SUPPLY_PILOT','EXCHANGE')),
    order_id TEXT NOT NULL,
    amount_micros INTEGER NOT NULL CHECK (amount_micros > 0),
    cny_reference_cents INTEGER NOT NULL CHECK (cny_reference_cents > 0),
    rate_numerator INTEGER NOT NULL CHECK (rate_numerator = 501),
    rate_denominator INTEGER NOT NULL CHECK (rate_denominator = 500),
    status TEXT NOT NULL CHECK (status IN ('CAPTURED','PARTIAL_REFUND','REFUNDED')),
    idempotency_key TEXT NOT NULL,
    payload_hash TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (source_system, order_id),
    UNIQUE (organization_id, idempotency_key)
  )`,
  `CREATE INDEX IF NOT EXISTS card_hour_payments_org_time_idx ON card_hour_order_payments(organization_id, created_at DESC)`,
  `CREATE TABLE IF NOT EXISTS card_hour_referral_codes (
    organization_id TEXT PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS card_hour_referral_attributions (
    invitee_organization_id TEXT PRIMARY KEY,
    referrer_organization_id TEXT NOT NULL,
    referral_code TEXT NOT NULL,
    created_at TEXT NOT NULL,
    CHECK (invitee_organization_id <> referrer_organization_id),
    FOREIGN KEY (referral_code) REFERENCES card_hour_referral_codes(code)
  )`,
  `CREATE TABLE IF NOT EXISTS card_hour_income_accruals (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    income_type TEXT NOT NULL CHECK (income_type IN ('RENTAL','COMMISSION')),
    source_system TEXT NOT NULL,
    source_id TEXT NOT NULL,
    amount_micros INTEGER NOT NULL CHECK (amount_micros > 0),
    status TEXT NOT NULL CHECK (status IN ('PENDING','VESTED','REVERSED')),
    created_at TEXT NOT NULL,
    vested_at TEXT,
    UNIQUE (income_type, source_system, source_id, organization_id)
  )`,
  `CREATE INDEX IF NOT EXISTS card_hour_income_org_time_idx ON card_hour_income_accruals(organization_id, created_at DESC)`,
  `CREATE TABLE IF NOT EXISTS card_hour_buyback_orders (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    account_id TEXT NOT NULL,
    amount_micros INTEGER NOT NULL CHECK (amount_micros >= 5000000 AND amount_micros % 5000000 = 0),
    status TEXT NOT NULL CHECK (status IN ('REQUESTED','APPROVED','PROCESSING','PAID','REJECTED','CANCELLED','FAILED')),
    payout_rate_numerator INTEGER,
    payout_rate_denominator INTEGER,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS card_hour_order_holds (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    account_id TEXT NOT NULL,
    source_system TEXT NOT NULL CHECK (source_system = 'HOSTING_V2'),
    order_id TEXT NOT NULL,
    amount_micros INTEGER NOT NULL CHECK (amount_micros > 0),
    settled_micros INTEGER CHECK (settled_micros IS NULL OR (settled_micros > 0 AND settled_micros <= amount_micros)),
    status TEXT NOT NULL CHECK (status IN ('HELD','SETTLED','RELEASED')),
    idempotency_key TEXT NOT NULL,
    payload_hash TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(source_system, order_id),
    UNIQUE(organization_id, idempotency_key)
  )`,
  `CREATE TABLE IF NOT EXISTS card_hour_hold_events (
    id TEXT PRIMARY KEY,
    hold_id TEXT NOT NULL,
    event_type TEXT NOT NULL CHECK (event_type IN ('HELD','SETTLED','RELEASED')),
    amount_micros INTEGER NOT NULL CHECK (amount_micros > 0),
    payload_hash TEXT NOT NULL,
    occurred_at TEXT NOT NULL,
    UNIQUE(hold_id,event_type),
    FOREIGN KEY (hold_id) REFERENCES card_hour_order_holds(id)
  )`,
  `CREATE TABLE IF NOT EXISTS hosting_v2_supplier_fee_volume_events (
    id TEXT PRIMARY KEY,
    supplier_organization_id TEXT NOT NULL,
    contract_id TEXT NOT NULL,
    event_type TEXT NOT NULL CHECK (event_type IN ('SETTLEMENT','REFUND','REVERSAL')),
    amount_micros INTEGER NOT NULL CHECK (amount_micros > 0),
    source_event_id TEXT NOT NULL UNIQUE,
    payload_digest TEXT NOT NULL,
    occurred_at TEXT NOT NULL,
    created_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS hosting_v2_fee_volume_supplier_time_idx ON hosting_v2_supplier_fee_volume_events(supplier_organization_id,occurred_at,source_event_id)`,
  `CREATE INDEX IF NOT EXISTS hosting_v2_fee_volume_contract_time_idx ON hosting_v2_supplier_fee_volume_events(contract_id,occurred_at,source_event_id)`,
  `CREATE TRIGGER IF NOT EXISTS hosting_v2_fee_volume_immutable_update BEFORE UPDATE ON hosting_v2_supplier_fee_volume_events BEGIN SELECT RAISE(ABORT, 'hosting fee volume event immutable'); END`,
  `CREATE TRIGGER IF NOT EXISTS hosting_v2_fee_volume_immutable_delete BEFORE DELETE ON hosting_v2_supplier_fee_volume_events BEGIN SELECT RAISE(ABORT, 'hosting fee volume event immutable'); END`,
  `CREATE TABLE IF NOT EXISTS card_hour_trial_grants (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    amount_micros INTEGER NOT NULL CHECK (amount_micros >= 1000000),
    reason TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('REQUESTED','APPROVED','REJECTED','POSTED')),
    requested_by TEXT NOT NULL,
    approved_by TEXT,
    decision_payload_hash TEXT,
    idempotency_key TEXT NOT NULL,
    payload_hash TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(requested_by,idempotency_key)
  )`,
] as const;
