import type { Metadata } from "next";
import Link from "next/link";
import type { Locale } from "@/lib/i18n";
import { getRequestLocale } from "@/lib/server/request-locale";

type MethodCopy = {
  metadata: readonly [string, string]; hero: readonly [string, string, string, string, string];
  headings: readonly [string, string, string, string, string, string];
  unitLead: string; table: readonly [string, string, string, string]; units: ReadonlyArray<readonly [string, string, string]>;
  capacity: readonly [string, string, string, string, string, string, string];
  example: string;
  model: ReadonlyArray<readonly [string, string]>; modelNote: string;
  percentiles: ReadonlyArray<readonly [string, string, string]>; percentileNote: string;
  aggregation: ReadonlyArray<readonly [string, string]>;
  limits: readonly string[]; actions: readonly [string, string];
};

const EN: MethodCopy = {
  metadata: ["Data and pricing methodology", "KAI Cloud daily model list prices, compute market snapshots, pricing units, and standardized aggregation method."],
  hero: ["Market methodology", "Normalize the basis before discussing price", "KAI Cloud separates heterogeneous compute quotes into comparable fields. Model Token data uses daily public list-price snapshots; other compute sections are initial platform samples pending supplier verification.", "List prices and market quotes", "Market reference quotes and capacity samples require inquiry confirmation. International official benchmarks are not mainland China procurement prices and must not be used directly for contracts or financial decisions."],
  headings: ["Seven standard pricing units", "A capacity hour measures reserved capability", "Model prices must be compared by model and billing item", "How to read P25, P50, and P75", "KAI standardization and aggregation", "Explicit limits of this release"],
  unitLead: "Every record keeps currency, billing type, context tier, service level, validity, source, and update time so that comparison never relies on one number alone.",
  table: ["KAI Cloud standard pricing units and use cases", "Unit", "Unified definition", "Primary use"],
  units: [["Card-hour", "One GPU card continuously available for one hour", "GPU rental and GPU exchange"], ["Server-hour", "One complete server continuously available for one hour", "Bare-metal compute and cloud hosts"], ["Million Token", "One million Tokens actually processed by a model", "Usage settlement for Token-hour services"], ["Model-instance hour", "One exclusive model instance running for one hour", "Model-hour services"], ["Reserved-capacity hour", "Committed throughput, concurrency, or GPU capacity multiplied by reserved hours", "Model and compute capacity services"], ["Rack-month", "One rack with agreed power and network conditions for one calendar month", "Full-rack and capacity rental"], ["kW-month", "One kilowatt of deliverable power capacity for one calendar month", "Data-center power capacity"]],
  capacity: ["Capacity", "Committed capacity", "GPU count, throughput, concurrency, or model-instance scale.", "Time", "Reserved duration", "Agreed hours from availability until capacity release.", "Capacity × hours. Reserved capability remains occupied even when actual use is low, so it differs from actual Token usage."],
  example: "Example: reserve 8 GPUs for 10 hours and record 80 GPU capacity-hours. Throughput capacity must retain its throughput unit and cannot be exchanged directly with card-hours.",
  model: [["Input Token", "Usage generated when requests, context, and tool results enter the model. Long context may use a higher tier."], ["Cached input", "Read price for a vendor prompt-cache hit. If unpublished or inapplicable, it stays empty rather than using the regular input price."], ["Output Token", "Price of generated text and reasoning Tokens. Some vendors include thinking Tokens in output."]],
  modelNote: "The KAI model-call cost index uses a fixed model basket, fixed input/output ratio, and cache-hit assumption. Its base is 100 and it only expresses daily cost movement; it is neither a cross-model RMB average nor a tradable quote.",
  percentiles: [["P25", "Lower quote", "About 25% of sample quotes are no higher, often with stricter minimum order or delivery conditions."], ["P50", "Market median", "Half of samples are higher and half lower; this is the default KAI reference center."], ["P75", "Higher quote", "About 75% of sample quotes are no higher; the quote may include a stronger SLA or more flexible delivery."]],
  percentileNote: "Percentiles describe quote distribution, not an executable price. Small samples and different regions or delivery terms reduce comparability.",
  aggregation: [["05:40 Collect", "Load manually reviewed official price baselines plus machine-readable catalogs and daily FX data. This release does not recrawl every official price page each day."], ["05:50 Validate", "Reject incomplete units, price jumps, mass model disappearance, or expired data."], ["05:55 Normalize", "Normalize each model, version, service tier, and context band to per-million Token while retaining original currency."], ["Group", "Combine records only when resource, region, delivery form, and pricing unit are comparable."], ["06:00 Publish", "Atomically switch the verified snapshot. Failed sources retain the prior snapshot and are explicitly marked stale."]],
  limits: ["The model section publishes a public list-price snapshot daily at 06:00 CST; promotions, long-context tiers, and regional pricing must be read per row.", "GPU, rack, cloud-vendor resources, capacity, sample sizes, and related 90-day history are initial platform samples pending supplier verification.", "International model prices are official international benchmarks only; they do not represent mainland China availability, taxes, or procurement channels.", "Quotes are not offers. The website does not complete payment, contracting, delivery, or acceptance.", "Theme, work perspective, and watchlist stay in the browser. Requests, drafts, and quotes are stored by anonymous session for 30 days by default.", "An anonymous session is not an account. Do not enter personal data, company secrets, access credentials, or transaction information."],
  actions: ["View daily model market", "Submit compute demand"],
};

const ZH: MethodCopy = {
  metadata: ["数据与计价方法", "KAI Cloud 日度模型目录价、算力市场行情、计价单位与标准化汇总方法。"], hero: ["市场方法论", "行情先统一口径，再讨论价格", "KAI Cloud 将异构算力报价拆成可比较字段。模型 Token 板块使用公开目录价的日度快照；其他算力板块当前为平台初始化样本，待供应方接入后核验。", "目录价与市场报价说明", "市场参考报价与容量样本均需询价确认；国际官方基准不等于中国大陆可采购价格，不得直接用于合同或财务决策。"], headings: ["七种标准计价单位", "“容量小时”衡量的是被预留的能力", "模型价格必须逐型号、逐计费项比较", "P25、P50、P75 如何阅读", "KAI 标准化与汇总流程", "当前版本的明确限制"], unitLead: "每条记录同时保留币种、计费类型、上下文档位、服务等级、有效期、来源和更新时间，避免只比较一个数字。", table: ["KAI Cloud 标准计价单位与适用场景", "单位", "统一定义", "主要场景"], units: [["卡时", "单张 GPU 持续可用一小时", "GPU 租赁、GPU 置换"], ["服务器时", "单台完整服务器持续可用一小时", "整机算力与云主机"], ["百万 Token", "模型实际处理的一百万个 Token", "Token 小时服务的用量结算"], ["模型实例时", "一个独占模型实例持续运行一小时", "模型小时服务"], ["预留容量时", "约定吞吐、并发或 GPU 容量乘以预留小时", "模型容量与算力容量服务"], ["机柜月", "一个约定功率与网络条件的机柜使用一个自然月", "整机柜与容量租赁"], ["kW 月", "一千瓦可交付功率容量使用一个自然月", "数据中心功率容量"]], capacity: ["容量", "约定容量", "GPU 数量、吞吐、并发或模型实例规模。", "时间", "预留时长", "从可用开始到释放容量的约定小时数。", "容量 × 小时。即使实际用量较低，预留能力仍被占用，因此不同于实际 Token 用量。"], example: "示例：预留 8 张 GPU、持续 10 小时，记录为 80 GPU 容量时；模型吞吐必须保留吞吐单位，不能直接与卡时互换。", model: [["输入 Token", "用户请求、上下文和工具结果进入模型时产生的用量。长上下文可能进入更高价格档位。"], ["缓存输入", "命中厂商提示词缓存时的读取价格；未公布或不适用时保持为空，不用普通输入价代填。"], ["输出 Token", "模型生成文本与推理 Token 的价格；部分厂商会把思考 Token 一并计入输出。"]], modelNote: "KAI 模型调用成本指数使用固定模型篮子、固定输入输出比例与缓存命中假设，基期设为 100，只表达日度成本变化；它不是跨模型人民币均价，也不是任何一个模型的可成交报价。", percentiles: [["P25", "偏低报价", "样本中约 25% 的报价不高于该值，通常伴随更严格的起订量或交付条件。"], ["P50", "市场中位", "一半样本高于该值、一半低于该值，作为 KAI 默认参考中心。"], ["P75", "偏高报价", "样本中约 75% 的报价不高于该值，可能包含更高 SLA 或更灵活交付。"]], percentileNote: "分位数描述报价分布，不代表可按该价格成交。样本量较小、区域或交付条件不同，都会降低可比性。", aggregation: [["05:40 采集", "载入经人工审核的官方价格基线，并读取机器可读目录与日度外汇数据；当前版本不会每天重新抓取全部官方价格页。"], ["05:50 校验", "剔除单位不完整、价格突变、型号批量消失或超过有效期的数据。"], ["05:55 标准化", "按具体模型、版本、服务档位和上下文区间统一为每百万 Token，并保留原币种。"], ["分组", "仅在资源、区域、交付形态和计价单位可比时进入同一组。"], ["06:00 发布", "原子切换已验证快照；失败来源继续展示上一期并明确标记数据陈旧。"]], limits: ["模型板块按每日 06:00 CST 发布公开目录价快照；促销、长上下文和区域价需按行内口径理解。", "GPU、机柜、云厂商资源、容量数据、样本量与对应 90 天行情当前为平台初始化样本，供应方接入后核验。", "国际模型价格只作为官方国际基准，不代表中国大陆的可用性、税费或采购渠道。", "报价不构成要约；网站不完成支付、合同、交付或验收。", "主题、工作视角和关注列表保存在当前浏览器；需求、草稿与报价按匿名会话写入服务器，默认保留 30 天。", "匿名会话不是正式账户；请勿输入个人信息、公司机密、访问凭据或成交资料。"], actions: ["查看日度模型行情", "提交算力需求"],
};

const LOCAL = {
  "zh-TW": { metadata: ["資料與計價方法", "KAI Cloud 日度模型目錄價、算力市場行情、計價單位與標準化彙總方法。"], hero: ["市場方法論", "先統一口徑，再討論價格", "KAI Cloud 將異質算力報價拆成可比較欄位；模型使用日度公開目錄價，其他板塊待供應方核驗。", "目錄價與市場報價說明", "市場參考報價與容量樣本需詢價確認；國際基準不等於中國大陸可採購價格。"], headings: ["七種標準計價單位", "容量小時衡量預留能力", "模型價格須逐型號與計費項比較", "如何閱讀 P25、P50、P75", "KAI 標準化與彙總流程", "目前版本的明確限制"], actions: ["查看日度模型行情", "提交算力需求"] },
  ja: { metadata: ["データと価格算定方法", "KAI Cloudの日次モデル価格、計算市場、価格単位、標準集計方法。"], hero: ["市場方法論", "価格の前に比較基準を揃える", "KAI Cloudは異種計算資源を比較可能な項目に分解します。モデルは日次公開価格、その他は供給者検証待ちの初期標本です。", "定価と市場見積", "参考見積と容量標本は問い合わせ確認が必要です。国際基準は中国本土の調達価格ではありません。"], headings: ["7つの標準価格単位", "容量時間は予約能力を測る", "モデル価格は型番・課金項目別に比較", "P25・P50・P75の読み方", "KAI標準化・集計手順", "現行版の明確な制限"], actions: ["日次モデル市場を見る", "計算需要を提出"] },
  ko: { metadata: ["데이터 및 가격 방법론", "KAI Cloud 일일 모델 가격, 컴퓨팅 시장, 가격 단위 및 표준 집계 방법."], hero: ["시장 방법론", "가격보다 먼저 비교 기준을 통일", "KAI Cloud는 이기종 컴퓨팅 견적을 비교 가능한 필드로 나눕니다. 모델은 일일 공개 가격, 기타 영역은 공급자 검증 대기 표본입니다.", "정가 및 시장 견적 안내", "참고 견적과 용량 표본은 문의 확인이 필요하며 국제 기준은 중국 본토 조달가가 아닙니다."], headings: ["7가지 표준 가격 단위", "용량시간은 예약된 능력을 측정", "모델 가격은 모델·과금 항목별 비교", "P25·P50·P75 읽기", "KAI 표준화 및 집계", "현재 버전의 명확한 제한"], actions: ["일일 모델 시장 보기", "컴퓨팅 수요 제출"] },
  fr: { metadata: ["Données et méthode de prix", "Prix catalogue quotidiens, marché du calcul, unités et agrégation standardisée KAI Cloud."], hero: ["Méthodologie du marché", "Normaliser avant de parler prix", "KAI Cloud décompose les offres de calcul en champs comparables. Les modèles utilisent des prix publics quotidiens ; les autres sections attendent la vérification des fournisseurs.", "Prix catalogue et offres", "Les références et capacités exigent confirmation. Les repères internationaux ne sont pas des prix d’achat en Chine continentale."], headings: ["Sept unités standard", "L’heure-capacité mesure la capacité réservée", "Comparer les modèles par référence et poste", "Lire P25, P50 et P75", "Normalisation et agrégation KAI", "Limites explicites de cette version"], actions: ["Voir le marché quotidien", "Soumettre un besoin"] },
  th: { metadata: ["ข้อมูลและวิธีกำหนดราคา", "ราคาฐานรายวัน ตลาดพลังประมวลผล หน่วยราคา และวิธีรวมข้อมูลของ KAI Cloud"], hero: ["วิธีการตลาด", "ปรับเกณฑ์ให้ตรงกันก่อนคุยเรื่องราคา", "KAI Cloud แยกข้อเสนอพลังประมวลผลเป็นฟิลด์ที่เปรียบเทียบได้ ราคาโมเดลเป็นภาพรายวัน ส่วนอื่นรอผู้ให้บริการยืนยัน", "ราคาฐานและราคาตลาด", "ราคาอ้างอิงและตัวอย่างความจุต้องยืนยันผ่านการสอบถาม เกณฑ์สากลไม่ใช่ราคาจัดซื้อในจีน"], headings: ["หน่วยราคามาตรฐาน 7 แบบ", "ชั่วโมงความจุวัดความสามารถที่จอง", "เปรียบเทียบราคาแยกรุ่นและรายการ", "วิธีอ่าน P25, P50, P75", "การปรับมาตรฐานและรวมข้อมูล KAI", "ข้อจำกัดที่ชัดเจน"], actions: ["ดูตลาดโมเดลรายวัน", "ส่งความต้องการ"] },
  vi: { metadata: ["Dữ liệu và phương pháp định giá", "Giá niêm yết hằng ngày, thị trường tính toán, đơn vị giá và phương pháp tổng hợp KAI Cloud."], hero: ["Phương pháp thị trường", "Chuẩn hóa cơ sở trước khi bàn giá", "KAI Cloud tách báo giá thành các trường có thể so sánh. Mô hình dùng giá công khai hằng ngày; phần khác chờ nhà cung cấp xác minh.", "Giá niêm yết và báo giá", "Giá tham khảo và mẫu dung lượng cần xác nhận; chuẩn quốc tế không phải giá mua tại Trung Quốc đại lục."], headings: ["Bảy đơn vị giá chuẩn", "Giờ-dung lượng đo năng lực được giữ", "So sánh giá theo model và hạng mục", "Cách đọc P25, P50, P75", "Chuẩn hóa và tổng hợp KAI", "Giới hạn rõ ràng của phiên bản"], actions: ["Xem thị trường hằng ngày", "Gửi nhu cầu"] },
  id: { metadata: ["Data dan metodologi harga", "Harga model harian, pasar komputasi, unit harga, dan agregasi standar KAI Cloud."], hero: ["Metodologi pasar", "Samakan dasar sebelum membahas harga", "KAI Cloud memecah penawaran komputasi menjadi bidang yang dapat dibandingkan. Model memakai harga publik harian; bagian lain menunggu verifikasi pemasok.", "Harga katalog dan pasar", "Referensi dan sampel kapasitas perlu dikonfirmasi. Tolok ukur internasional bukan harga pengadaan Tiongkok daratan."], headings: ["Tujuh unit harga standar", "Jam kapasitas mengukur kemampuan yang dipesan", "Bandingkan harga per model dan item", "Cara membaca P25, P50, P75", "Standardisasi dan agregasi KAI", "Batas eksplisit versi ini"], actions: ["Lihat pasar model harian", "Ajukan kebutuhan"] },
  ms: { metadata: ["Data dan kaedah harga", "Harga model harian, pasaran pengkomputeran, unit harga dan pengagregatan standard KAI Cloud."], hero: ["Kaedah pasaran", "Selaraskan asas sebelum membincangkan harga", "KAI Cloud memecah tawaran pengkomputeran kepada medan setara. Model menggunakan harga awam harian; bahagian lain menunggu pengesahan pembekal.", "Harga katalog dan pasaran", "Rujukan dan sampel kapasiti perlu disahkan. Penanda aras antarabangsa bukan harga perolehan China tanah besar."], headings: ["Tujuh unit harga standard", "Jam kapasiti mengukur keupayaan ditempah", "Banding harga mengikut model dan item", "Cara membaca P25, P50, P75", "Piawaian dan pengagregatan KAI", "Had jelas versi ini"], actions: ["Lihat pasaran model harian", "Hantar keperluan"] },
} as const;

function copyFor(locale: Locale): MethodCopy {
  if (locale === "zh-CN") return ZH;
  if (locale === "en") return EN;
  const local = LOCAL[locale];
  return { ...EN, metadata: local.metadata, hero: local.hero, headings: local.headings, actions: local.actions };
}

export async function generateMetadata(): Promise<Metadata> { const copy = copyFor(await getRequestLocale()); return { title: copy.metadata[0], description: copy.metadata[1] }; }

export default async function MethodologyPage() {
  const copy = copyFor(await getRequestLocale());
  return <>
    <header className="border-b border-[var(--border)] bg-[var(--info-bg)]"><div className="narrow-shell py-14 sm:py-20"><p className="kicker">{copy.hero[0]}</p><h1 className="m-0 text-4xl leading-tight sm:text-5xl">{copy.hero[1]}</h1><p className="section-lead">{copy.hero[2]}</p><div className="market-notice mt-8"><strong>{copy.hero[3]}</strong><span>{copy.hero[4]}</span></div></div></header>
    <article className="narrow-shell py-14 sm:py-20">
      <section aria-labelledby="unit-heading"><p className="kicker">01 / Units</p><h2 className="section-heading" id="unit-heading">{copy.headings[0]}</h2><p className="section-lead text-base">{copy.unitLead}</p><div className="data-table-wrap mt-8"><table className="data-table"><caption className="sr-only">{copy.table[0]}</caption><thead><tr>{copy.table.slice(1).map((label) => <th scope="col" key={label}>{label}</th>)}</tr></thead><tbody>{copy.units.map(([unit, definition, scenario]) => <tr key={unit}><th className="whitespace-nowrap text-[var(--ink)]" scope="row">{unit}</th><td>{definition}</td><td>{scenario}</td></tr>)}</tbody></table></div></section>
      <section aria-labelledby="capacity-heading" className="mt-20 border-t border-[var(--border)] pt-12"><p className="kicker">02 / Capacity hour</p><h2 className="section-heading" id="capacity-heading">{copy.headings[1]}</h2><div className="mt-8 grid gap-px bg-[var(--border)] sm:grid-cols-3">{[[copy.capacity[0], copy.capacity[1], copy.capacity[2]], [copy.capacity[3], copy.capacity[4], copy.capacity[5]], ["Result", "Capacity × hours", copy.capacity[6]]].map(([code, title, text]) => <div className="bg-[var(--surface)] p-5" key={code}><p className="m-0 text-xs font-bold uppercase tracking-[0.1em] text-[var(--accent)]">{code}</p><h3 className="my-3 text-xl">{title}</h3><p className="m-0 text-sm">{text}</p></div>)}</div><div className="mt-5 border-l-4 border-[var(--accent)] bg-[var(--accent-soft)] p-5 text-sm">{copy.example}</div></section>
      <section aria-labelledby="model-token-heading" className="mt-20 border-t border-[var(--border)] pt-12"><p className="kicker">03 / Model Token</p><h2 className="section-heading" id="model-token-heading">{copy.headings[2]}</h2><div className="mt-8 grid gap-px bg-[var(--border)] md:grid-cols-3">{copy.model.map(([title, description]) => <div className="bg-[var(--surface)] p-5" key={title}><h3 className="m-0 text-lg text-[var(--ink)]">{title}</h3><p className="mt-2 mb-0 text-sm leading-6 text-[var(--text)]">{description}</p></div>)}</div><p className="mt-6 border-l-2 border-[var(--accent)] pl-4 text-sm leading-6 text-[var(--text)]">{copy.modelNote}</p></section>
      <section aria-labelledby="percentile-heading" className="mt-20 border-t border-[var(--border)] pt-12"><p className="kicker">04 / Percentiles</p><h2 className="section-heading" id="percentile-heading">{copy.headings[3]}</h2><dl className="mt-8 grid gap-6 md:grid-cols-3">{copy.percentiles.map(([term, label, description]) => <div className="border-t-2 border-[var(--accent)] pt-5" key={term}><dt className="font-mono text-3xl font-bold text-[var(--ink)]">{term}</dt><dd className="mt-2 font-semibold text-[var(--ink)]">{label}</dd><dd className="mt-2 text-sm text-[var(--text)]">{description}</dd></div>)}</dl><p className="mt-6 text-sm text-[var(--muted)]">{copy.percentileNote}</p></section>
      <section aria-labelledby="aggregation-heading" className="mt-20 border-t border-[var(--border)] pt-12"><p className="kicker">05 / Aggregation</p><h2 className="section-heading" id="aggregation-heading">{copy.headings[4]}</h2><ol className="mt-8 grid gap-4">{copy.aggregation.map(([title, description], index) => <li className="grid grid-cols-[48px_1fr] border-b border-[var(--border)] pb-4" key={title}><span className="font-mono text-sm font-bold text-[var(--accent)]">{String(index + 1).padStart(2, "0")}</span><div><h3 className="m-0 text-lg">{title}</h3><p className="mb-0 mt-1 text-sm">{description}</p></div></li>)}</ol></section>
      <section aria-labelledby="limits-heading" className="mt-20 border border-[var(--border-strong)] bg-[var(--info-bg)] p-6 sm:p-8"><p className="kicker">06 / Limits</p><h2 className="m-0 text-2xl" id="limits-heading">{copy.headings[5]}</h2><ul className="mt-5 grid gap-2 pl-5 text-sm">{copy.limits.map((limit) => <li key={limit}>{limit}</li>)}</ul><div className="mt-6 flex flex-wrap gap-3"><Link className="button button-primary" href="/market">{copy.actions[0]}</Link><Link className="button button-secondary" href="/request">{copy.actions[1]}</Link></div></section>
    </article>
  </>;
}
